/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/coupons": {
    /**
     * 내 쿠폰 가져오기
     * @description  ## 부가설명 및 특이사항
     *  로그인한 사용자가 보유한 쿠폰중 사용가능한 쿠폰과 이미 사용한 쿠폰을 구분하여 조회합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
     */
    get: operations["get-my-coupons"];
  };
  "/coupons/issuable": {
    /**
     * 발급 가능한 쿠폰 조회하기
     * @description  ## 부가설명 및 특이사항
     *  상품과 상관없이 오늘 날짜 기준으로 다운로드 가능한 쿠폰을 모두 조회합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png?autox150'></a>
     */
    get: operations["get-issuable-coupons"];
  };
  "/coupons/summary": {
    /**
     * 내 쿠폰 요약정보 가져오기
     * @description  ## 부가설명 및 특이사항
     *  로그인한 사용자가 보유한 쿠폰의 정보를 요약하여 조회합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png?autox150'></a>
     */
    get: operations["get-my-coupon-summary"];
  };
  "/coupons/register-code/{promotionCode}": {
    /**
     * 코드 쿠폰 발급하기
     * @description  ## 부가설명 및 특이사항
     *  등록된 프로모션 코드를 이용해 쿠폰을 발급받습니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png?autox150'></a>
     */
    post: operations["post-register-code-download"];
  };
  "/coupons/{couponNo}/download": {
    /**
     * 쿠폰 발급하기
     * @description  ## 부가설명 및 특이사항
     *  선택한 쿠폰번호에 해당하는 다운로드 쿠폰을 발급받습니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png?autox150'></a>
     */
    post: operations["post-download-coupons"];
  };
  "/coupons/{couponNo}/exclude-targets": {
    /**
     * 쿠폰번호로 제외 대상 조회하기
     * @description  ## 부가설명 및 특이사항
     *  선택한 쿠폰번호에 해당하는 제외 대상의 목록을 조회합니다.
     */
    get: operations["get-coupon-exclude-target"];
  };
  "/coupons/{couponNo}/targets": {
    /**
     * 쿠폰번호로 대상 조회하기
     * @description  ## 부가설명 및 특이사항
     *  선택한 쿠폰번호에 해당하는 대상의 목록을 조회합니다.
     */
    get: operations["get-coupon-target"];
  };
  "/coupons/events/{eventNo}/download": {
    /**
     * 기획전 번호로 쿠폰 발급하기
     * @description  ## 부가설명 및 특이사항
     *  해당 기획전에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
     */
    post: operations["post-download-coupon-by-event"];
  };
  "/coupons/products/{productNo}/download": {
    /**
     * 상품 번호로 쿠폰 발급하기
     * @description  ## 부가설명 및 특이사항
     *  해당 상품에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
     */
    post: operations["post-download-coupon-by-product"];
  };
  "/coupons/products/{productNo}/issuable/coupons": {
    /**
     * 상품 번호로 발급 가능한 쿠폰 조회하기
     * @description  ## 부가설명 및 특이사항
     *  해당 상품 상세정보에서 다운로드 할수 있는 모든 쿠폰을 조회합니다.
     *
     *  ## 화면 예시
     *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150'></a>
     */
    get: operations["get-issuable-coupon-by-products"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "coupons-summary1109451763": {
      /**
       * @description 사용/기간만료 쿠폰 개수
       * @example 1
       */
      expiringCouponCnt?: number;
      /**
       * @description 사용가능 쿠폰 개수
       * @example 1
       */
      usableCouponCnt?: number;
    };
    "coupons-products-productNo-download-112148540": {
      /**
       * @description 채널 타입
       * @example NAVER_EP, FACEBOOK
       */
      channelType?: string;
    };
    "coupons-1604558997": {
      /**
       * @description 총 쿠폰 개수
       * @example 14
       */
      totalCount?: number;
      /** @description 쿠폰 내역 */
      items?: ({
          /**
           * @description 쿠폰 발급 사유
           * @example 행사
           */
          reason?: string;
          /**
           * @description 할인율
           * @example 1
           */
          discountRate?: number;
          /**
           * @description 할인금액
           * @example 5000
           */
          discountAmt?: number;
          /**
           * @description 쿠폰 명
           * @example 5월 기획전 쿠폰
           */
          couponName?: string;
          /**
           * @description 쿠폰 발급 번호
           * @example 1
           */
          couponIssueNo?: number;
          /**
           * @description 최소판매금액기준
           * @example 10000
           */
          minSalePrice?: number;
          /**
           * @description 배송비무료여부
           * @example false
           */
          freeDelivery?: boolean;
          /**
           * @description 최대할인금액(정률에서)
           * @example 10000
           */
          maxDiscountAmt?: number;
          /**
           * @description 사용여부 (true: 사용함 / false: 사용하지 않음)
           * @example false
           */
          used?: boolean;
          /**
           * @description 사용종료일
           * @example yyyy-MM-dd HH:mm:ss
           */
          useEndYmdt?: string;
          /**
           * @description 장바구니 쿠폰 사용 가능여부 (true: 사용 가능 / false: 사용 불가능)
           * @example true
           */
          cartCouponUsable?: boolean;
          /**
           * @description 쿠폰 유형
           * @example PRODUCT
           * @enum {string}
           */
          couponType?: "PRODUCT: 상품적용 쿠폰" | "CART: 주문적용 쿠폰" | "CART_DELIVERY: 장바구니 배송비 할인";
          /**
           * @description 상품쿠폰 사용 가능여부 (true: 사용 가능 / false: 사용 불가능)
           * @example true
           */
          productCouponUsable?: boolean;
          /**
           * @description 발급일
           * @example yyyy-MM-dd HH:mm:ss
           */
          issueYmdt?: string;
          /**
           * @description 정액 여부 (true: 정액 / false: 정률)
           * @example true
           */
          fixedAmt?: boolean;
          /**
           * @description 사용가능 결제수단 리스트
           * @example [PAYCO, NAVER_EASY_PAY, CREDIT_CARD, REALTIME_ACCOUNT_TRANSFER, VIRTUAL_ACCOUNT, ESCROW_REALTIME_ACCOUNT_TRANSFER, ESCROW_VIRTUAL_ACCOUNT]
           */
          limitPayTypes?: ("CREDIT_CARD: 신용카드" | "ACCOUNT: 무통장입금" | "MOBILE: 휴대폰결제" | "REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체" | "VIRTUAL_ACCOUNT: 가상계좌" | "GIFT: 상품권" | "ATM: ATM" | "PAYCO: PAYCO" | "ZERO_PAY: 0원결제" | "ACCUMULATION: 적립금 전액 사용" | "PHONE_BILL: 전화결제" | "POINT: 포인트결제" | "YPAY: 옐로페이" | "KPAY: 케이페이" | "PAYPIN: 페이핀" | "INIPAY: INIPay 간편결제" | "PAYPAL: PayPal" | "STRIPE: STRIPE" | "NAVER_PAY: 네이버페이 주문형" | "KAKAO_PAY: 카카오페이" | "NAVER_EASY_PAY: 네이버페이 결제형" | "SAMSUNG_PAY: 삼성페이" | "CHAI: 차이" | "TOSS_PAY: 토스페이" | "SK_PAY: SK페이" | "APPLE_PAY: 애플페이" | "ESCROW_REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체-에스크로" | "ESCROW_VIRTUAL_ACCOUNT: 가상계좌-에스크로" | "VERITRANS_CARD: Veritrans CreditCard" | "TOASTCAM: 토스트캠" | "UNION_PAY: UnionPay" | "ALIPAY: Alipay Plus" | "WECHAT_PAY: WeChat Pay" | "ETC: 기타결제수단")[];
          /**
           * @description 사용가능 결제수단
           * @example PAYCO
           * @enum {string}
           */
          limitPayType?: "CREDIT_CARD: 신용카드" | "ACCOUNT: 무통장입금" | "MOBILE: 휴대폰결제" | "REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체" | "VIRTUAL_ACCOUNT: 가상계좌" | "GIFT: 상품권" | "ATM: ATM" | "PAYCO: PAYCO" | "ZERO_PAY: 0원결제" | "ACCUMULATION: 적립금 전액 사용" | "PHONE_BILL: 전화결제" | "POINT: 포인트결제" | "YPAY: 옐로페이" | "KPAY: 케이페이" | "PAYPIN: 페이핀" | "INIPAY: INIPay 간편결제" | "PAYPAL: PayPal" | "STRIPE: STRIPE" | "NAVER_PAY: 네이버페이 주문형" | "KAKAO_PAY: 카카오페이" | "NAVER_EASY_PAY: 네이버페이 결제형" | "SAMSUNG_PAY: 삼성페이" | "CHAI: 차이" | "TOSS_PAY: 토스페이" | "SK_PAY: SK페이" | "APPLE_PAY: 애플페이" | "ESCROW_REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체-에스크로" | "ESCROW_VIRTUAL_ACCOUNT: 가상계좌-에스크로" | "VERITRANS_CARD: Veritrans CreditCard" | "TOASTCAM: 토스트캠" | "UNION_PAY: UnionPay" | "ALIPAY: Alipay Plus" | "WECHAT_PAY: WeChat Pay" | "ETC: 기타결제수단";
          /**
           * @description 사용일시
           * @example yyyy-MM-dd HH:mm:ss
           */
          useYmdt?: string;
          /**
           * @description 쿠폰 번호
           * @example 1
           */
          couponNo?: number;
          /**
           * @description 할인쿠폰 대상 타입
           * @example PRODUCT
           * @enum {string}
           */
          couponTargetType?: "ALL_PRODUCT: 전상품" | "PRODUCT: 개별상품" | "BRAND: 브랜드" | "CATEGORY: 카테고리" | "PARTNER: 파트너사";
          /**
           * @description 적립금 적립 불가 여부 (true: 적립 불가능 / false: 적립 가능)
           * @example true
           */
          skipsAccumulation?: boolean;
          /**
           * @description deprecated(더 이상 제공하지 않는 개체항목입니다)
           * 선택된 쿠폰 외 다른 쿠폰 사용 가능여부 (true: 사용 가능 / false: 사용 불가능)
           * @example true
           */
          otherCouponUsable?: boolean;
          /**
           * @description 사용가능 플랫폼
           * @example PC,MOBILE_WEB,MOBILE_APP
           */
          usablePlatforms?: ("PC: PC" | "MOBILE_WEB: MOBILE WEB" | "MOBILE_APP: MOBLIE APP")[];
          /**
           * @description 배송비쿠폰일경우 최소 배송비
           * @example 2500
           */
          minDeliveryAmt?: number;
          /**
           * @description 최대판매금액기준
           * @example 30000
           */
          maxSalePrice?: number;
          /**
           * @description deprecated(더 이상 제공하지 않는 개체항목입니다)
           * 정액 여부 (true: 정액 / false: 정률)
           * @example true
           */
          fiexdAmt?: boolean;
          /**
           * @description 사용 가능 회원 등급
           * @example [VIP, VVIP]
           */
          memberGradeNames?: string[];
          /**
           * @description 사용 가능 회원 그룹
           * @example [임원, 직원]
           */
          memberGroupNames?: string[];
        })[];
    };
    /** @description 다운로드 가능 쿠폰 목록 */
    "coupons-issuable1175218347": ({
        /**
         * @description 다운로드 가능여부 (true: 다운로드 가능 / false: 다운로드 불가능)
         * @example true
         */
        downloadable?: boolean;
        /**
         * @description 쿠폰 이름
         * @example NCP 오픈기념 쿠폰
         */
        couponName?: string;
        /** @description 할인정보 */
        discountInfo?: {
          /**
           * @description 쿠폰 할인율
           * @example 10
           */
          discountRate?: number;
          /**
           * @description 쿠폰 할인액
           * @example 10000
           */
          discountAmt?: number;
          /**
           * @description 타 쿠폰과 함께 사용가능 여부 (true: 사용 가능 / false: 사용 불가능)
           * @example false
           */
          useOtherCoupon?: boolean;
          /**
           * @description 적립급 지급 불가 여부 (true: 지급 가능 / false: 지급 불가능)
           * @example false
           */
          skippedAccumulationAmt?: boolean;
          /**
           * @description 상품 쿠폰 사용가능 여부 (true: 사용 가능 / false: 사용 불가능)
           * @example false
           */
          useProductCoupon?: boolean;
          /**
           * @description 배송비 무료 여부(배송비쿠폰인경우) (true: 무료 / false: 유료)
           * @example true
           */
          freeDelivery?: boolean;
          /**
           * @description 최대 할인액
           * @example 100
           */
          maxDiscountAmt?: number;
          /**
           * @description 장바구니 쿠폰 사용가능 여부 (true: 사용 가능 / false: 사용 불가능)
           * @example false
           */
          useCartCoupon?: boolean;
          /**
           * @description 정액여부 (true: 정액 / false: 정률 )
           * @example true
           */
          fixedAmt?: boolean;
        };
        /** @description 사용제약조건 */
        useConstraint?: {
          /**
           * @description 쿠폰 사용가능 결제수단
           * @example PAYCO
           * @enum {string}
           */
          limitPayType?: "CREDIT_CARD: 신용카드" | "ACCOUNT: 무통장입금" | "MOBILE: 휴대폰결제" | "REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체" | "VIRTUAL_ACCOUNT: 가상계좌" | "GIFT: 상품권" | "ATM: ATM" | "PAYCO: PAYCO" | "ZERO_PAY: 0원결제" | "ACCUMULATION: 적립금 전액 사용" | "PHONE_BILL: 전화결제" | "POINT: 포인트결제" | "YPAY: 옐로페이" | "KPAY: 케이페이" | "PAYPIN: 페이핀" | "INIPAY: INIPay 간편결제" | "PAYPAL: PayPal" | "STRIPE: STRIPE" | "NAVER_PAY: 네이버페이 주문형" | "KAKAO_PAY: 카카오페이" | "NAVER_EASY_PAY: 네이버페이 결제형" | "SAMSUNG_PAY: 삼성페이" | "CHAI: 차이" | "TOSS_PAY: 토스페이" | "SK_PAY: SK페이" | "APPLE_PAY: 애플페이" | "ESCROW_REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체-에스크로" | "ESCROW_VIRTUAL_ACCOUNT: 가상계좌-에스크로" | "VERITRANS_CARD: Veritrans CreditCard" | "TOASTCAM: 토스트캠" | "UNION_PAY: UnionPay" | "ALIPAY: Alipay Plus" | "WECHAT_PAY: WeChat Pay" | "ETC: 기타결제수단";
          /**
           * @description 사용가능 기간 - 쿠폰을 발급받은 날부터 (31은 월말까지, -1은 제한없음)
           * @example 1
           */
          useDays?: number;
          /**
           * @description 쿠폰 사용조건 최소 구매액
           * @example 1000
           */
          minSalePrice?: number;
          /**
           * @description 사용 사용종료 일
           * @example yyyy-MM-dd HH:mm:ss
           */
          useEndYmdt?: string;
          /**
           * @description 사용가능플랫폼
           * @example ["PC"]
           */
          usablePlatformTypes?: ("PC: PC" | "MOBILE_WEB: MOBILE WEB" | "MOBILE_APP: MOBLIE APP")[];
          /**
           * @description 쿠폰 사용조건 최소 배송비
           * @example 2500
           */
          minDeliveryAmt?: number;
          /**
           * @description 쿠폰 사용가능 결제수단 리스트
           * @example [PAYCO, NAVER_EASY_PAY]
           */
          limitPayTypes?: ("CREDIT_CARD: 신용카드" | "ACCOUNT: 무통장입금" | "MOBILE: 휴대폰결제" | "REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체" | "VIRTUAL_ACCOUNT: 가상계좌" | "GIFT: 상품권" | "ATM: ATM" | "PAYCO: PAYCO" | "ZERO_PAY: 0원결제" | "ACCUMULATION: 적립금 전액 사용" | "PHONE_BILL: 전화결제" | "POINT: 포인트결제" | "YPAY: 옐로페이" | "KPAY: 케이페이" | "PAYPIN: 페이핀" | "INIPAY: INIPay 간편결제" | "PAYPAL: PayPal" | "STRIPE: STRIPE" | "NAVER_PAY: 네이버페이 주문형" | "KAKAO_PAY: 카카오페이" | "NAVER_EASY_PAY: 네이버페이 결제형" | "SAMSUNG_PAY: 삼성페이" | "CHAI: 차이" | "TOSS_PAY: 토스페이" | "SK_PAY: SK페이" | "APPLE_PAY: 애플페이" | "ESCROW_REALTIME_ACCOUNT_TRANSFER: 실시간계좌이체-에스크로" | "ESCROW_VIRTUAL_ACCOUNT: 가상계좌-에스크로" | "VERITRANS_CARD: Veritrans CreditCard" | "TOASTCAM: 토스트캠" | "UNION_PAY: UnionPay" | "ALIPAY: Alipay Plus" | "WECHAT_PAY: WeChat Pay" | "ETC: 기타결제수단")[];
          /**
           * @description 쿠폰 사용조건 최대 구매액
           * @example 5000
           */
          maxSalePrice?: number;
        };
        /** @description 발급제약조건 */
        issueConstraint?: {
          /**
           * @description 1일내 발급 제한 수량
           * @example 1
           */
          dailyIssueLimitCnt?: number;
          /**
           * @description 1인당 발급 제한 수량(총기간)
           * @example 123
           */
          issuePerPersonLimitCnt?: number;
          /**
           * @description 발급대상 회원 등급
           * @example 홍길동
           */
          memberGradeName?: string;
          /**
           * @description 발행가능 플랫폼
           * @example ["PC"]
           */
          issuablePlatformTypes?: ("PC: PC" | "MOBILE_WEB: MOBILE WEB" | "MOBILE_APP: MOBLIE APP")[];
          /**
           * @description 발급대상 회원 등급 json
           * @example ["VIP"]
           */
          memberGradeNames?: string[];
          /**
           * @description 발급/사용 채널
           * @example NAVER_EP
           */
          channelTypes?: string[];
          /**
           * @description 1인당 발급 제한 수량(1일간)
           * @example 1
           */
          dailyIssuePerPersonLimitCnt?: number;
          /**
           * @description 1일내 발급 수량 제한 여부 (true: 제한 있음 / false: 제한 없음)
           * @example false
           */
          dailyIssueLimit?: boolean;
          /**
           * @description 1인당 발급 수량 제한 여부(true: 제한 있음 / false: 제한 없음)
           * @example true
           */
          issuePerPersonLimit?: boolean;
          /**
           * @description 발급대상 회원 그룹 json
           * @example ["임직원"]
           */
          memberGroupNames?: string[];
        };
        /**
         * @description 쿠폰 종류
         * @example PRODUCT
         * @enum {string}
         */
        couponType?: "PRODUCT: 상품적용 쿠폰" | "CART: 주문적용 쿠폰" | "CART_DELIVERY: 장바구니 배송비 할인";
        /** @description 쿠폰발급상태 */
        couponStatus?: {
          /**
           * @description 내가 발급 받은 개수
           * @example 1
           */
          myIssuedCnt?: number;
          /**
           * @description 총 발행수량
           * @example 1
           */
          totalIssuedCnt?: number;
          /**
           * @description 쿠폰 발행가능 수량
           * @example 1
           */
          totalIssuableCnt?: number;
          /**
           * @description 발급가능수량
           * @example 1
           */
          issuableCnt?: number;
          /**
           * @description 내가 발급 받은 개수(오늘)
           * @example 1
           */
          myIssuedCntToday?: number;
          /**
           * @description 총 발행수량(오늘) `1일 발급 제한이 있는 쿠폰만 해당 값 내려줍니다.`
           * @example 1
           */
          totalIssuedCntToday?: number;
        };
        /** @description 발급시간정보 */
        dateInfo?: {
          /**
           * @description 발급 제한 일
           * @example yyyy-MM-dd HH:mm:ss
           */
          issueEndYmdt?: string;
          /**
           * @description 발급 시작 일
           * @example yyyy-MM-dd HH:mm:ss
           */
          issueStartYmdt?: string;
          /**
           * @description 발급가능요일
           * @example [1,2,3,4,5,6,7]
           */
          issueDaysOfWeek?: string;
          /**
           * @description 발급 종료 시간
           * @example 12
           */
          issueEndHour?: number;
          /**
           * @description 발급 시작 시간
           * @example 12
           */
          issueStartHour?: number;
        };
        /**
         * @description 쿠폰 번호
         * @example 1
         */
        couponNo?: number;
        /**
         * @description 쿠폰 대상 종류
         * @example ALL_PRODUCT
         * @enum {string}
         */
        couponTargetType?: "ALL_PRODUCT: 전상품" | "PRODUCT: 개별상품" | "BRAND: 브랜드" | "CATEGORY: 카테고리" | "PARTNER: 파트너사";
        /**
         * @description deprecated(더 이상 제공하지 않는 개체항목입니다)
         * 제휴 방문처 타입
         * @example DIRECT
         */
        allianceRefererType?: string;
      })[];
    "coupons-couponNo-download822432082": {
      /**
       * @description 외부 채널 타입
       * @example NAVER_EP
       */
      channelType?: string;
    };
    "coupons-register-code-promotionCode-707212779": {
      /**
       * @description 쿠폰 명
       * @example 할인쿠폰
       */
      couponName?: string;
      /**
       * @description 쿠폰 발급 번호
       * @example 1
       */
      couponIssueNo?: number;
      /**
       * @description 쿠폰 번호
       * @example 1
       */
      couponNo?: number;
      /**
       * @description 사용종료일
       * @example yyyy-MM-dd HH:mm:ss
       */
      useEndYmdt?: string;
    };
    "coupons-couponNo-exclude-targets-901367319": {
      /**
       * @description 총 대상 개수
       * @example 10
       */
      totalCount?: number;
      /** @description 대상 내역 */
      items?: ({
          /**
           * @description 대상 이름
           * @example 생일 케이크
           */
          targetName?: string;
          /**
           * @description 대상 타입
           * @example PRODUCT
           * @enum {string}
           */
          targetType?: "ALL_PRODUCT: 전상품" | "PRODUCT: 개별상품" | "BRAND: 브랜드" | "CATEGORY: 카테고리" | "PARTNER: 파트너사";
          /**
           * @description 대상 번호
           * @example 1
           */
          targetNo?: number;
        })[];
    };
    "coupons-products-productNo-download-1626840969": {
      /** @description 발급 실패 쿠폰 목록 */
      issueFailCoupons?: {
          /**
           * @description 에러코드
           * @example C1004
           */
          errorCode?: string;
          /**
           * @description 쿠폰번호
           * @example 1
           */
          couponNo?: number;
          /**
           * @description 실패 메세지
           * @example 할인쿠폰이 모두 매진 되었습니다.
           */
          failMessage?: string;
        }[];
      /** @description 발급된 쿠폰목록 */
      issuedCoupons?: {
          /**
           * @description 쿠폰 명
           * @example 할인쿠폰
           */
          couponName?: string;
          /**
           * @description 쿠폰 발급 번호
           * @example 1
           */
          couponIssueNo?: number;
          /**
           * @description 쿠폰 번호
           * @example 1
           */
          couponNo?: number;
          /**
           * @description 사용종료일
           * @example yyyy-MM-dd HH:mm:ss
           */
          useEndYmdt?: string;
        }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 내 쿠폰 가져오기
   * @description  ## 부가설명 및 특이사항
   *  로그인한 사용자가 보유한 쿠폰중 사용가능한 쿠폰과 이미 사용한 쿠폰을 구분하여 조회합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  "get-my-coupons": {
    parameters: {
      query: {
        /**
         * @description 쿠폰 번호
         * @example [1, 2, 3]
         */
        couponNos?: string;
        /**
         * @description 내림차순 정렬 여부
         * @example false
         */
        desc?: string;
        /**
         * @description 검색 종료 일 (지정 하지 않을 시 오늘 날짜까지 조회)
         * @example yyyy-MM-dd
         */
        endYmd?: string;
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 30
         */
        pageSize: string;
        /**
         * @description 검색 시작 일 (지정 하지 않을 시 3개월 전 오늘 날짜부터 조회)
         * @example yyyy-MM-dd
         */
        startYmd?: string;
        /**
         * @description 사용가능 여부 (true: 사용 가능 / false: 사용 불가능 / null: 조건 없음)
         * @example true
         */
        usable?: string;
      };
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-1604558997"];
        };
      };
    };
  };
  /**
   * 발급 가능한 쿠폰 조회하기
   * @description  ## 부가설명 및 특이사항
   *  상품과 상관없이 오늘 날짜 기준으로 다운로드 가능한 쿠폰을 모두 조회합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png?autox150'></a>
   */
  "get-issuable-coupons": {
    parameters: {
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-issuable1175218347"];
        };
      };
    };
  };
  /**
   * 내 쿠폰 요약정보 가져오기
   * @description  ## 부가설명 및 특이사항
   *  로그인한 사용자가 보유한 쿠폰의 정보를 요약하여 조회합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png?autox150'></a>
   */
  "get-my-coupon-summary": {
    parameters: {
      query?: {
        /**
         * @description 만료일 - (현재 + 만료일)이 검색 조건에 포함됩니다.
         * @example 7
         */
        expireDay?: string;
      };
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-summary1109451763"];
        };
      };
    };
  };
  /**
   * 코드 쿠폰 발급하기
   * @description  ## 부가설명 및 특이사항
   *  등록된 프로모션 코드를 이용해 쿠폰을 발급받습니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png?autox150'></a>
   */
  "post-register-code-download": {
    parameters: {
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 프로모션 코드
         * @example 2020EVENT
         */
        promotionCode: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-register-code-promotionCode-707212779"];
        };
      };
    };
  };
  /**
   * 쿠폰 발급하기
   * @description  ## 부가설명 및 특이사항
   *  선택한 쿠폰번호에 해당하는 다운로드 쿠폰을 발급받습니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png?autox150'></a>
   */
  "post-download-coupons": {
    parameters: {
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 쿠폰번호
         * @example 1
         */
        couponNo: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["coupons-couponNo-download822432082"];
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-register-code-promotionCode-707212779"];
        };
      };
    };
  };
  /**
   * 쿠폰번호로 제외 대상 조회하기
   * @description  ## 부가설명 및 특이사항
   *  선택한 쿠폰번호에 해당하는 제외 대상의 목록을 조회합니다.
   */
  "get-coupon-exclude-target": {
    parameters: {
      query: {
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 50
         */
        pageSize: string;
      };
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 쿠폰 번호
         * @example 1
         */
        couponNo: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-couponNo-exclude-targets-901367319"];
        };
      };
    };
  };
  /**
   * 쿠폰번호로 대상 조회하기
   * @description  ## 부가설명 및 특이사항
   *  선택한 쿠폰번호에 해당하는 대상의 목록을 조회합니다.
   */
  "get-coupon-target": {
    parameters: {
      query: {
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 50
         */
        pageSize: string;
      };
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 쿠폰 번호
         * @example 1
         */
        couponNo: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-couponNo-exclude-targets-901367319"];
        };
      };
    };
  };
  /**
   * 기획전 번호로 쿠폰 발급하기
   * @description  ## 부가설명 및 특이사항
   *  해당 기획전에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  "post-download-coupon-by-event": {
    parameters: {
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 기획전 번호
         * @example 123
         */
        eventNo: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-products-productNo-download-1626840969"];
        };
      };
    };
  };
  /**
   * 상품 번호로 쿠폰 발급하기
   * @description  ## 부가설명 및 특이사항
   *  해당 상품에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  "post-download-coupon-by-product": {
    parameters: {
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 상품번호
         * @example 123412
         */
        productNo: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["coupons-products-productNo-download-112148540"];
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-products-productNo-download-1626840969"];
        };
      };
    };
  };
  /**
   * 상품 번호로 발급 가능한 쿠폰 조회하기
   * @description  ## 부가설명 및 특이사항
   *  해당 상품 상세정보에서 다운로드 할수 있는 모든 쿠폰을 조회합니다.
   *
   *  ## 화면 예시
   *  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150'></a>
   */
  "get-issuable-coupon-by-products": {
    parameters: {
      query?: {
        /**
         * @description 채널 타입
         * @example NAVER_EP, FACEBOOK
         */
        channelType?: string;
      };
      header: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version: string;
        /** @description 회원 엑세스 토큰 */
        accessToken?: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /**
         * @description 언어 (기본 값: ko)
         * @example PC
         */
        language?: string;
      };
      path: {
        /**
         * @description 상품번호
         * @example 1
         */
        productNo: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          "application/json": components["schemas"]["coupons-issuable1175218347"];
        };
      };
    };
  };
}
