/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '@/openapi-types/shopby-api-types/member-shop-public.d.ts';

export interface Get {
  /**
   * 쇼핑몰에서 가입 가능한 법인 목록 조회하기
   * @description ## 부가설명 및 특이사항
  clientId에 해당하는 쇼핑몰에 가입 가능한 법인 목록을 조회하는 API 입니다.
  
  name param 을 포함해서 회사 이름 키워드 검색도 가능합니다. (최대 10개)
  
  ex) /companies?name=nhn
   */
  '/companies': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 검색어 (회사 이름)
         * @example NHN
         */
        name: string;
      };
    };
    body?: never;
    data: components['schemas']['companies392849182'];
    error: any;
  };

  /**
   * 사업자회원 사업자등록번호 중복체크
   * @description ## 부가설명 및 특이사항
  **(셀바이 전용)**
  
  셀바이 사업자회원 가입 시 사업자등록번호 중복체크하는 API 입니다.
   */
  '/companies/business-exist': {
    params: {
      path?: never;
      query: {
        /**
         * @description 사업자등록번호 (10자리)
         * @example 1234567890
         */
        registration: string;
      };
    };
    body?: never;
    data: components['schemas']['companies-business-exist1596823314'];
    error: any;
  };

  /**
   * 회원 등급 정보 조회하기
   * @description ## 부가설명 및 특이사항
   회원 등급 번호를 통해 회원 등급 정보를 조회하는 API 입니다. <br>
   회원 등급 번호 미 입력 시 쇼핑몰에 등록된 모든 회원 등급 정보를 조회합니다.
   */
  '/member-grades': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 회원 등급 번호 리스트 (미 입력 시 쇼핑몰에 등록된 모든 회원 등급 정보를 조회합니다.)
         * @example 1,2,3
         */
        gradeNos: string;
      };
    };
    body?: never;
    data: components['schemas']['member-grades-1794093165'];
    error: any;
  };

  /**
   * 회원 그룹 정보 조회하기
   * @description ## 부가설명 및 특이사항
   회원 그룹 번호를 통해 회원 그룹 정보를 조회하는 API 입니다. <br>
   회원 그룹 번호 미 입력 시 쇼핑몰에 등록된 모든 그룹 정보를 조회합니다.
   */
  '/member-groups': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 회원 그룹 번호 리스트 (미 입력 시 쇼핑몰에 등록된 모든 그룹 정보를 조회합니다.)
         * @example 1,2,3
         */
        groupNos: string;
      };
    };
    body?: never;
    data: components['schemas']['member-groups-698297322'];
    error: any;
  };

  /**
   * 회원정보 조회하기
   * @description ## 부가설명 및 특이사항
   회원 정보를 조회합니다.
   */
  '/profile': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-401210172'];
    error: any;
  };

  /**
   * 차단된 회원 조회하기
   * @description ## 부가설명 및 특이사항
  내가 차단한 회원의 목록을 조회합니다.
   */
  '/profile/blocked-members': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: number;
        /**
         * @description 한 페이지당 노출 수
         * @example 1
         */
        pageSize: number;
        /**
         * @description 목록 카운트 포함 여부(false: 미포함(default), true: 포함)
         * @example false
         */
        hasTotalCount: boolean;
      };
    };
    body?: never;
    data: components['schemas']['profile-blocked-members-1099343813'];
    error: any;
  };

  /**
   * 휴면 회원 조회하기
   * @description ## 부가설명 및 특이사항
  휴면 해제 화면에 노출할 휴면 계정 정보를 조회합니다.
   */
  '/profile/dormancy': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-dormancy-1848330549'];
    error: any;
  };

  /**
   * 내 등급 조회하기
   * @description ## 부가설명 및 특이사항
  내 등급 정보를 가져옵니다.
   */
  '/profile/grade': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-grade127148107'];
    error: any;
  };

  /**
   * 아이디 찾기 v1.0
   * @description ## 부가설명 및 특이사항
  모바일 or 이메일 인증 후 아이디를 조회할 수 있는 API 입니다.
  버전 v1.0 API입니다. 업데이트 된 v1.1 API가 있습니다.
   */
  '/profile/id': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 법인번호
         * @example 111
         */
        companyNo: number;
        /**
         * @description 이름 (쇼핑몰 회원가입 정보 설정에서 회원명을 사용함 또는 필수로 지정한 경우 필수입력)
         * @example 홍길동
         */
        memberName: string;
        /**
         * @description 휴대전화 번호 (SMS 인증 찾기로 인증번호 전송시 입력)
         * @example 010-1234-5678
         */
        mobileNo: string;
        /**
         * @description 이메일 (이메일 찾기로 인증번호 전송시 입력)
         * @example test@shopby.com
         */
        email: string;
        /**
         * @description CI
         * @example ABC1010
         */
        ci: string;
        /**
         * @description 인증번호
         * @example 123456
         */
        certificationNumber: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-id-490464478'];
    error: any;
  };

  /**
   * 회원 요약 정보 조회하기
   * 
   * @description ## 부가설명 및 특이사항
  회원 쇼핑몰 요약 정보를 조회합니다.
  
  ## 화면 예시
  [![summary example](https://image.toast.com/aaaaahb/api-description/member/profile/get_profile_summary.png?autox150)](https://image.toast.com/aaaaahb/api-description/member/profile/get_profile_summary.png)
  
  - orders, claims, orderCountByStatus는 최근 30일간의 주문 정보만 표시합니다.
  
  마이페이지를 위한 요약정보가 필요한데 비해 응답이 비대하고, 각 항목별로 조회할 수 있는 API가 존재하여 이 API는 deprecated 되었습니다.
  각 항목별 API는 아래 목록을 참고해주세요.
  
  ### 운영
  
  - [1:1 문의 조회](https://docs.shopby.co.kr/?urls.primaryName=manage#/Inquiry/1%3A1%20%EB%AC%B8%EC%9D%98%20%EB%82%B4%EC%97%AD%20%EC%A1%B0%ED%9A%8C)
  - [적립금 내역 조회](https://docs.shopby.co.kr/?urls.primaryName=manage#/Reward%20Cash%20(Accumulation)/Inquiry%20of%20the%20accumulations%20details%20for%20each%20member)
  
  ### 클레임
  
  - [클레임 조회](https://docs.shopby.co.kr/?urls.primaryName=claim#/%5B%ED%9A%8C%EC%9B%90%5D/%ED%81%B4%EB%A0%88%EC%9E%84%20%EB%AA%A9%EB%A1%9D%EC%9D%84%20%EC%A1%B0%ED%9A%8C%ED%95%9C%EB%8B%A4.)
  
  ### 주문
  
  - [주문 내역 조회](https://docs.shopby.co.kr/?urls.primaryName=order#/%5BProfile%5D%20%3E%20MyOrder/%EC%A3%BC%EB%AC%B8%20%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%A1%B0%ED%9A%8C)
  - [상태별 주문 수량 조회](https://docs.shopby.co.kr/?urls.primaryName=order#/[Profile]%20%3E%20MyOrder/%EC%83%81%ED%83%9C%EB%B3%84%20%EC%A3%BC%EB%AC%B8%20%EC%88%98%EB%9F%89)
  - [배송지 목록 조회](https://docs.shopby.co.kr/?urls.primaryName=order#/[Shop%20Shipping%20Addresses]/%EB%B0%B0%EC%86%A1%EC%A7%80%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0)
  
  ### 전시
  
  - [상품평 조회](https://docs.shopby.co.kr/?urls.primaryName=display#/[Review]/%EB%82%B4%20%EC%83%81%ED%92%88%ED%8F%89%20%EB%AA%A9%EB%A1%9D)
  - [상품평 작성 가능한 상품 조회](https://docs.shopby.co.kr/?urls.primaryName=display#/[Review]/%EB%82%B4%20%EC%83%81%ED%92%88%ED%8F%89%20%EC%9E%91%EC%84%B1%20%EA%B0%80%EB%8A%A5%20%EB%AA%A9%EB%A1%9D)
  
  ### 상품
  
  - [좋아요 상품 조회](https://docs.shopby.co.kr/?urls.primaryName=product#/%5BProfile%5D/%ED%9A%8C%EC%9B%90%EC%9D%B4%20%EC%A2%8B%EC%95%84%ED%95%98%EB%8A%94%20%EC%83%81%ED%92%88%EB%AA%A9%EB%A1%9D%20%EC%A1%B0%ED%9A%8C)
  
  ### 프로모션
  
  - [쿠폰 조회](https://docs.shopby.co.kr/?urls.primaryName=promotion#/%5BCOUPON%5D/%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80))
   */
  '/profile/summary': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-summary-1564074611'];
    error: any;
  };

  /**
   * CI 중복확인하기
   * @description ## 부가설명 및 특이사항
   쇼핑몰에 동일한 CI를 사용중인 회원이 있는지 확인합니다.
   현재 회원이 로그인중인 경우, 엑세스 토큰을 함께 전달하면 본인을 제외하고 동일한 CI를 사용중인 회원이 있는지 확인합니다.
  
   휴대폰 본인인증을 사용하는 경우 여러 사용자가 동일한 CI로 회원가입할 수 없습니다.
   회원가입 / 수정 전 CI를 반드시 확인해주세요.
  
   ci는 특수문자를 포함하고 있기때문에, 인코딩을 한 뒤에 전달해야합니다.
   */
  '/profile/ci/exists': {
    params: {
      path?: never;
      query: {
        /**
         * @description CI
         * @example abcde
         */
        ci: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-ci-exists1428048428'];
    error: any;
  };

  /**
   * 해당 쇼핑몰에 이메일 중복여부 체크하기
   * @description ## 부가설명 및 특이사항
   해당 쇼핑몰에 입력한 이메일을 가진 회원이 있는지 확인합니다.
   true가 회신되는 경우 이미 해당 이메일로 가입한 회원이 존재합니다. (이메일 중복 입력)
  
  ## Parameters
  | name | type | required | default value | description |
  | :---: | :---: | :---: | :---: | :--- |
  | email         | string   | Y | - | 이메일 |
  | memberTypes    | string    | N | - | 회원 유형(list) <br> MALL: 일반 회원<br>PAYCO: 페이코 회원<br>SYNC_ID: 연동형 회원<br>OPEN_ID: 간편로그인 회원 |
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_email_exist.png?autox150)
   */
  '/profile/email/exist': {
    params: {
      path?: never;
      query: {
        /**
         * @description 회원 이메일 주소
         * @example test@test.com
         */
        email: string;
        /** @description 회원유형 리스트 (기본 - 쇼핑몰 회원(MALL) */
        memberTypes: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-email-exist467148882'];
    error: any;
  };

  /**
   * 해당 쇼핑몰에 아이디 중복여부 체크하기
   * @description ## 부가설명 및 특이사항
   해당 쇼핑몰에 입력한 아이디로 가진 회원이 있는지 확인합니다.
   true가 회신되는 경우 이미 해당 아이디로 가입한 회원이 존재합니다. (아이디 중복 입력)
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_id_exist.png?autox150)
   */
  '/profile/id/exist': {
    params: {
      path?: never;
      query: {
        /**
         * @description 회원 ID
         * @example memberId
         */
        memberId: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-email-exist467148882'];
    error: any;
  };

  /**
   * 해당 쇼핑몰에 휴대폰 번호 중복여부 확인하기
   * @description ## 부가설명 및 특이사항
  해당 쇼핑몰에 입력한 휴대폰번호가 있는지 확인하는 API 입니다.
   */
  '/profile/mobile/exist': {
    params: {
      path?: never;
      query: {
        /**
         * @description 휴대전화 번호
         * @example 01012345678
         */
        mobileNo: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-mobile-exist2037066060'];
    error: any;
  };

  /**
   * 해당 쇼핑몰에 닉네임 중복여부 체크하기
   * @description ## 부가설명 및 특이사항
   해당 쇼핑몰에 입력한 닉네임으로 가진 회원이 있는지 확인합니다.
   true가 회신되는 경우 이미 해당 닉네임으로 가입한 회원이 존재합니다. (닉네임 중복 입력)
   */
  '/profile/nickname/exist': {
    params: {
      path?: never;
      query: {
        /**
         * @description 회원 닉네임
         * @example jinsu
         */
        nickname: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-email-exist467148882'];
    error: any;
  };

  /**
   * 비밀번호 찾기를 위한 계정 조회하기
   * @description ## 부가설명 및 특이사항
   비밀번호 찾기를 위한 계정 정보를 조회합니다.
   개인정보 항목인 이름, 휴대폰번호, 이메일은 마스킹된 값으로 조회됩니다.
   */
  '/profile/password/search-account': {
    params: {
      path?: never;
      query: {
        /**
         * @description 검색할 회원 아이디
         * @example memberId
         */
        memberId: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-password-search-account-340796099'];
    error: any;
  };

  /**
   * 해당 쇼핑몰 아이디, 이름, 이메일 검증하기
   * @description ## 부가설명 및 특이사항
   해당 쇼핑몰에 입력한 아이디, 이름, 이메일과 동일한 회원이 있는지 여부 확인합니다.
   true이면 회원이 존재합니다.
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_member_equals_with-mobile1.png?autox150)
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_member_equals_with-mobile2.png?autox150)
   */
  '/profile/member/equals/with-email': {
    params: {
      path?: never;
      query: {
        /** @description 아이디 */
        memberId: string;
        /** @description 이름 */
        memberName: string;
        /** @description 이메일 */
        email: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-email-exist467148882'];
    error: any;
  };

  /**
   * 해당 쇼핑몰 아이디, 이름, 휴대폰 번호 검증하기
   * @description ## 부가설명 및 특이사항
   해당 쇼핑몰에 입력한 아이디, 이름, 휴대폰 번호와 동일한 사용자가 있는지 여부 확인합니다.
   true이면 회원이 존재합니다.
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_member_equals_with-mobile1.png?autox150)
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/get_profile_member_equals_with-mobile2.png?autox150)
   */
  '/profile/member/equals/with-mobile': {
    params: {
      path?: never;
      query: {
        /**
         * @description 아이디
         * @example test001
         */
        memberId: string;
        /**
         * @description 이름
         * @example 홍길동
         */
        memberName: string;
        /**
         * @description 휴대폰 번호
         * @example aaa@bbb.ccc
         */
        mobileNo: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-email-exist467148882'];
    error: any;
  };
}

export interface Head {}

export interface Post {
  /**
   * 프로필 생성하기
   * @description ## 부가설명 및 특이사항
  회원 프로필 등록 시 사용하는 API 입니다.
  
  회원가입 화면구현 관련 자세한 내용은 [스킨개발가이드](https://shopby.works/guide/skin/dev-cover/join?lv=11) 참고하시길 바랍니다.
   */
  '/profile': {
    params?: never;
    body?: components['schemas']['profile-1802189837'];
    data: components['schemas']['profile-401210172'];
    error: any;
  };

  /**
   * 회원 차단하기
   * @description ## 부가설명 및 특이사항
  회원을 차단합니다. 차단 시 즉시 차단한 회원이 작성한 상품평, 게시글, 1:1문의 등의 내용을 차단합니다.
   */
  '/profile/blocked-members': {
    params?: never;
    body?: components['schemas']['profile-blocked-members-1463040538'];
    data: any;
    error: any;
  };

  /**
   * 브랜드 회원 회원가입 처리하기
   * @description ## 부가설명 및 특이사항
  브랜드 회원의 회원 가입 처리 API입니다.
  
  브랜드 로그인으로 서브몰에서 최초 로그인한 회원인 경우 위 API를 호출하여 가입 완료 처리를 해야합니다.
  가입 처리시 약관 및 수신 동의 여부를 받을 수 있습니다.
   */
  '/profile/brand-oauth': {
    params?: never;
    body?: components['schemas']['profile-brand-oauth737242750'];
    data: components['schemas']['profile-openid705174444'];
    error: any;
  };

  /**
   * 비밀번호 변경
   * @description ## 부가설명 및 특이사항
  회원 인증 후 비밀번호를 변경합니다. 기존에 사용중이던 비밀번호와 동일한 비밀번호로 변경할 수 없습니다.
   */
  '/profile/change-password-after-cert': {
    params?: never;
    body?: components['schemas']['profile-change-password-after-cert1373938464'];
    data: any;
    error: any;
  };

  /**
   * 비밀번호 확인하기
   * @description ## 부가설명 및 특이사항
   현재 로그인한 사용자가 맞는지 비밀번호를 한번 더 체크할 때 사용하는 API 입니다.
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/post_profile_check-password.png?autox150)
   */
  '/profile/check-password': {
    params?: never;
    body?: components['schemas']['profile-non-masking67271596'];
    data: any;
    error: components['schemas']['profile-check-password755598787'];
  };

  /**
   * 아이디 찾기
   * @description ## 부가설명 및 특이사항
  회원가입시 입력한 정보로 내 아이디를 검색합니다.
  
  
  - 운영자가 이름을 필수 항목으로 설정한 경우 회원 이름을 같이 전달해야합니다.
  - 운영자가 인증번호 확인을 필수로 설정한 경우 인증번호를 같이 전달해야합니다.
  - 인증번호 확인 또는 휴대폰 본인인증을 사용하지 않은 경우 아이디, 이름, 휴대폰번호, 이메일은 마스킹된 결과가 노출됩니다.
   */
  '/profile/find-id': {
    params?: never;
    body?: components['schemas']['profile-find-id1684397436'];
    data: components['schemas']['profile-find-id-307171953'];
    error: any;
  };

  /**
   * 비밀번호 찾기
   * @description ## 부가설명 및 특이사항
  회원 정보의 이메일로 비밀번호 재설정 주소 전달
  
  ## 화면 예시
  [![img](http://image.toast.com/aaaaahb/api-description/member/profile/put_profile_password_sending-email-with-url.png?autox150)](http://image.toast.com/aaaaahb/api-description/member/profile/put_profile_password_sending-email-with-url.png)
   */
  '/profile/find-password': {
    params?: never;
    body?: components['schemas']['profile-find-password-88917142'];
    data: components['schemas']['profile-find-password1822051151'];
    error: any;
  };

  /**
   * 마스킹 해제된 회원정보 조회하기
   * @description ## 부가설명 및 특이사항
   비밀번호 인증으로 마스킹 해제된 회원정보를 조회합니다.
   (mallName은 조회되지 않습니다.)
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/post_profile_check-password.png?autox150)
   */
  '/profile/non-masking': {
    params?: never;
    body?: components['schemas']['profile-non-masking67271596'];
    data: components['schemas']['profile-non-masking-399139774'];
    error: any;
  };

  /**
   * 오픈 아이디 회원가입 처리하기
   * @description ## 부가설명 및 특이사항
  오픈 아이디를 사용한 회원 가입 처리입니다.
  
  간편 로그인으로 신규 가입을 하는 회원인 경우 위 API를 호출하여 가입 완료 처리를 해야합니다.<br/>
  가입 처리시 추가적인 사용자 정보를 받을 수 있습니다.<br/>
  
  카카오싱크 회원의 경우 약관은 카카오싱크 연동과 동시에 저장되기 때문에 joinTermsAgreements는 null로 보내주시면 됩니다.
   */
  '/profile/openid': {
    params?: never;
    body?: components['schemas']['profile-openid-358191852'];
    data: components['schemas']['profile-openid705174444'];
    error: any;
  };

  /**
   * NHN KCP 본인인증으로 회원 개인정보 갱신하기
   * @description ## 부가설명 및 특이사항
   기존에 NHN KCP 본인인증을 안 한 회원이 본인인증 진행 시 개인정보를 갱신할 수 있습니다.
  
   NHN KCP에서 보내준 본인인증 확인키를 파라미터로 보내, 회원의 이름/성별/생년월일/CI 등의 정보를 본인인증 정보로 업데이트합니다.
  
   (※ 본인인증 키는 KCP 본인확인 절차를 참고바랍니다)
  
   단, 만약 이미 동일한 실명으로 인증된 회원이 있을 경우 본인인증 정보가 갱신되지 않습니다.
   */
  '/profile/rename': {
    params?: never;
    body?: components['schemas']['profile-rename639574670'];
    data: any;
    error: any;
  };

  /**
   * 회원 신고하기
   * @description ## 부가설명 및 특이사항
  회원을 신고합니다.
   */
  '/profile/report': {
    params?: never;
    body?: components['schemas']['profile-report-1610725430'];
    data: any;
    error: any;
  };

  /**
   * 기존 회원을 오픈 아이디 회원으로 전환하기(카카오싱크 전용)
   * @description ## 부가설명 및 특이사항
  기존 회원을 오픈 아이디 회원으로 전환합니다.
  
  오픈 아이디 회원으로 가입시, 같은 이메일을 가진 기존 일반 회원을 합칠 때 사용합니다.
  
  일반 회원에서 오픈 아이디 회원으로 전환이 완료되면 가입 완료 처리가 됩니다.
  
  전환 완료시, 기존 토큰은 만료처리되고 새로운 토큰이 발급됩니다.
  
  이후, ID/PW 로그인을 불가능하며 전환한 오픈 아이디 회원으로 로그인이 가능합니다.
  
  현재는 카카오싱크 회원만 지원합니다.
   */
  '/profile/synchronize': {
    params?: never;
    body?: components['schemas']['profile-synchronize1831586937'];
    data: components['schemas']['profile-synchronize-1291073064'];
    error: any;
  };

  /**
   * ID 변경 메일 발송하기
   * @description ## 부가설명 및 특이사항
  ID를 변경할 수 있는 내용을 첨부한 email을 발송하는 API 입니다.
   */
  '/profile/id/email': {
    params?: never;
    body?: components['schemas']['profile-id-email1007069043'];
    data: components['schemas']['profile-id-email965079942'];
    error: any;
  };
}

export interface Put {
  /**
   * 회원정보 수정하기 v1.0
   * @description ## 부가설명 및 특이사항
  회원정보를 수정합니다.
  
   * V1.0 - 회원 정보를 수정합니다.
   * V1.1 - 회원의 현재 비밀번호를 입력받아 비밀번호 확인을 한 후 회원의 정보를 수정합니다.
   리퀘스트는 Examples에서 확인해주세요.
   */
  '/profile': {
    params?: never;
    body?: components['schemas']['profile1439626198'];
    data: components['schemas']['profile-61772240'];
    error: any;
  };

  /**
   * 프로필 주소 변경하기
   * @description ## 부가설명 및 특이사항
  회원의 주소를 변경하는 API 입니다.
   */
  '/profile/address': {
    params?: never;
    body?: components['schemas']['profile-address-74322410'];
    data: any;
    error: any;
  };

  /**
   * 휴면 해제하기
   * @description ## 부가설명 및 특이사항
  회원의 휴면 상태를 해제합니다.
   */
  '/profile/dormancy': {
    params?: never;
    body?: components['schemas']['profile-dormancy-969879824'];
    data: any;
    error: any;
  };

  /**
   * 비밀번호 검증 후 회원 탈퇴하기
   * @description ## 부가설명 및 특이사항
  
   쇼핑몰 회원일 경우 비밀번호 검증 후 회원 탈퇴합니다.
   */
  '/profile/expel': {
    params?: never;
    body?: components['schemas']['profile-expel662616769'];
    data: any;
    error: any;
  };

  /**
   * 회원 아이디 변경하기
   * @description ## 부가설명 및 특이사항
  인증 후 회원 아이디를 변경할 수 있는 API 입니다.
   */
  '/profile/id': {
    params?: never;
    body?: components['schemas']['profile-id-469582924'];
    data: any;
    error: any;
  };

  /**
   * 비밀번호 변경하기
   * @description ## 부가설명 및 특이사항
   인증이 완료된 사용자의 비밀번호를 변경합니다. (version 1.1)
   */
  '/profile/password': {
    params?: never;
    body?: components['schemas']['profile-password-1838978918'];
    data: any;
    error: any;
  };

  /**
   * 비밀번호 변경/초기화 URL의 이메일 발송하기
   * @description ## 부가설명 및 특이사항
   비밀번호 변경 또는 초기화하는 URL을 해당 사용자의 이메일로 발송합니다
  
  ## 화면 예시
   ![img](http://image.toast.com/aaaaahb/api-description/member/profile/put_profile_password_sending-email-with-url.png?autox150)
   */
  '/profile/password/sending-email-with-url': {
    params?: never;
    body?: components['schemas']['profile-password-sending-email-with-url653904592'];
    data: any;
    error: any;
  };

  /**
   * 본인인증 후 비밀번호 변경하기
   * @description ## 부가설명 및 특이사항
   로그인하지 않음 사용자의 비밀번호를 변경합니다.
   본인인증 후의 단계 이므로 이전단계인 본인인증 관련 API는 본인인증 API링크 참고 바랍니다. [본인인증](https://docs.shopby.co.kr/?urls.primaryName=auth#/%5BProfile%5D%20%3E%20KCPCertification/render_kcp_form)
  
  ## 화면 예시
  [![sample](https://image.toast.com/aaaaahb/api-description/member/profile/put_profile_password_no-authenication_after-certification.png?autox150)](https://image.toast.com/aaaaahb/api-description/member/profile/put_profile_password_no-authenication_after-certification.png)
   */
  '/profile/password/no-authentication/after-certification': {
    params?: never;
    body?: components['schemas']['profile-password-no-authentication-after-certification1927977452'];
    data: any;
    error: any;
  };

  /**
   * 이메일 인증 후 패스워드 변경하기.
   * @description ## 부가설명 및 특이사항
   로그인하지 않음 사용자의 비밀번호를 변경합니다.
   본인인증 후의 단계 이므로 이전단계인 본인인증 관련 API는 본인인증 API링크 참고 바랍니다. [본인인증](https://docs.shopby.co.kr/?urls.primaryName=auth#/%5BProfile%5D%20%3E%20KCPCertification/render_kcp_form)
   */
  '/profile/password/no-authentication/certificated-by-email': {
    params?: never;
    body?: components['schemas']['profile-password-no-authentication-certificated-by-sms971134018'];
    data: any;
    error: any;
  };

  /**
   * SMS 인증 후 패스워드 변경하기
   * @description ## 부가설명 및 특이사항
   로그인하지않은 사용자의 비밀번호를 변경합니다. (SMS 인증 사용)
   */
  '/profile/password/no-authentication/certificated-by-sms': {
    params?: never;
    body?: components['schemas']['profile-password-no-authentication-certificated-by-sms971134018'];
    data: any;
    error: any;
  };
}

export interface Patch {}

export interface Delete {
  /**
   * 회원 탈퇴하기
   * @description ## 부가설명 및 특이사항
  회원 탈퇴 시 사용하는 API 입니다.
   */
  '/profile': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 탈퇴 사유
         * @example 테스트용
         */
        reason: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };
}

export interface Options {}

export interface Trace {}
