/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '@/openapi-types/shopby-api-flatten/promotion-shop-public.d.ts';
export interface Get {
  /**
   * 내 쿠폰 가져오기
   * @description ## 부가설명 및 특이사항
  로그인한 사용자가 보유한 쿠폰중 사용가능한 쿠폰과 이미 사용한 쿠폰을 구분하여 조회합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0(%EB%A7%88%EC%9D%B4%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  '/coupons': {
    params: {
      path?: never;
      query: {
        /**
         * @description 쿠폰 번호
         * @example [1, 2, 3]
         */
        couponNos: string;
        /**
         * @description 내림차순 정렬 여부
         * @example false
         */
        desc: string;
        /**
         * @description 검색 종료 일 (지정 하지 않을 시 오늘 날짜까지 조회)
         * @example yyyy-MM-dd
         */
        endYmd: string;
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 30
         */
        pageSize: string;
        /**
         * @description 검색 시작 일 (지정 하지 않을 시 3개월 전 오늘 날짜부터 조회)
         * @example yyyy-MM-dd
         */
        startYmd: string;
        /**
         * @description 사용가능 여부 (true: 사용 가능 / false: 사용 불가능 / null: 조건 없음)
         * @example true
         */
        usable: string;
      };
    };
    body?: never;
    data: components['schemas']['coupons-1604558997'];
    error: any;
  };

  /**
   * 발급 가능한 쿠폰 조회하기
   * @description ## 부가설명 및 특이사항
  상품과 상관없이 오늘 날짜 기준으로 다운로드 가능한 쿠폰을 모두 조회합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_issuable%20%EC%98%A4%EB%8A%98%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EC%A1%B0%ED%9A%8C.png?autox150'></a>
   */
  '/coupons/issuable': {
    params?: never;
    body?: never;
    data: components['schemas']['coupons-issuable1175218347'];
    error: any;
  };

  /**
   * 내 쿠폰 요약정보 가져오기
   * @description ## 부가설명 및 특이사항
  로그인한 사용자가 보유한 쿠폰의 정보를 요약하여 조회합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_summary%20%EB%82%B4%20%EC%BF%A0%ED%8F%B0%20%EC%9A%94%EC%95%BD%EC%A0%95%EB%B3%B4.png?autox150'></a>
   */
  '/coupons/summary': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 만료일 - (현재 + 만료일)이 검색 조건에 포함됩니다.
         * @example 7
         */
        expireDay: string;
      };
    };
    body?: never;
    data: components['schemas']['coupons-summary1109451763'];
    error: any;
  };

  /**
   * 쿠폰번호로 제외 대상 조회하기
   * @description ## 부가설명 및 특이사항
  선택한 쿠폰번호에 해당하는 제외 대상의 목록을 조회합니다.
   */
  '/coupons/{couponNo}/exclude-targets': {
    params: {
      path: {
        /**
         * @description 쿠폰 번호
         * @example 1
         */
        couponNo: string;
      };
      query: {
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 50
         */
        pageSize: string;
      };
    };
    body?: never;
    data: components['schemas']['coupons-couponNo-exclude-targets-901367319'];
    error: any;
  };

  /**
   * 쿠폰번호로 대상 조회하기
   * @description ## 부가설명 및 특이사항
  선택한 쿠폰번호에 해당하는 대상의 목록을 조회합니다.
   */
  '/coupons/{couponNo}/targets': {
    params: {
      path: {
        /**
         * @description 쿠폰 번호
         * @example 1
         */
        couponNo: string;
      };
      query: {
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 50
         */
        pageSize: string;
      };
    };
    body?: never;
    data: components['schemas']['coupons-couponNo-exclude-targets-901367319'];
    error: any;
  };

  /**
   * 상품 번호로 발급 가능한 쿠폰 조회하기
   * @description ## 부가설명 및 특이사항
  해당 상품 상세정보에서 다운로드 할수 있는 모든 쿠폰을 조회합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[GET]%20coupons_products_issuable_coupons%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C%20%EA%B0%80%EB%8A%A5%ED%95%9C%20%EC%BF%A0%ED%8F%B0%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150'></a>
   */
  '/coupons/products/{productNo}/issuable/coupons': {
    params: {
      path: {
        /**
         * @description 상품번호
         * @example 1
         */
        productNo: string;
      };
      query?: {
        /**
         * @description 채널 타입
         * @example NAVER_EP, FACEBOOK
         */
        channelType: string;
      };
    };
    body?: never;
    data: components['schemas']['coupons-issuable1175218347'];
    error: any;
  };
}

export interface Head {}

export interface Post {
  /**
   * 코드 쿠폰 발급하기
   * @description ## 부가설명 및 특이사항
  등록된 프로모션 코드를 이용해 쿠폰을 발급받습니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_register-code_%EC%BF%A0%ED%8F%B0%EC%BD%94%EB%93%9C%EB%A1%9C%20%EC%BF%A0%ED%8F%B0%20%EB%B0%9C%EA%B8%89.png?autox150'></a>
   */
  '/coupons/register-code/{promotionCode}': {
    params: {
      path: {
        /**
         * @description 프로모션 코드
         * @example 2020EVENT
         */
        promotionCode: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['coupons-register-code-promotionCode-707212779'];
    error: any;
  };

  /**
   * 쿠폰 발급하기
   * @description ## 부가설명 및 특이사항
  선택한 쿠폰번호에 해당하는 다운로드 쿠폰을 발급받습니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_download%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.png?autox150'></a>
   */
  '/coupons/{couponNo}/download': {
    params: {
      path: {
        /**
         * @description 쿠폰번호
         * @example 1
         */
        couponNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['coupons-couponNo-download822432082'];
    data: components['schemas']['coupons-register-code-promotionCode-707212779'];
    error: any;
  };

  /**
   * 기획전 번호로 쿠폰 발급하기
   * @description ## 부가설명 및 특이사항
  해당 기획전에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_events_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%9D%B4%EB%B2%A4%ED%8A%B8%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  '/coupons/events/{eventNo}/download': {
    params: {
      path: {
        /**
         * @description 기획전 번호
         * @example 123
         */
        eventNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['coupons-products-productNo-download-1626840969'];
    error: any;
  };

  /**
   * 상품 번호로 쿠폰 발급하기
   * @description ## 부가설명 및 특이사항
  해당 상품에서 다운로드받을 수 있는 모든 쿠폰을 발급합니다.
  
  ## 화면 예시
  <a target='_blank' href='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png'><img src='http://image.toast.com/aaaaahb/api-description/order/coupon/[POST]%20coupons_products_download%20%EB%AA%A8%EB%93%A0%20%EC%BF%A0%ED%8F%B0%20%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C(%EC%83%81%ED%92%88%ED%8E%98%EC%9D%B4%EC%A7%80).png?autox150'></a>
   */
  '/coupons/products/{productNo}/download': {
    params: {
      path: {
        /**
         * @description 상품번호
         * @example 123412
         */
        productNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['coupons-products-productNo-download-112148540'];
    data: components['schemas']['coupons-products-productNo-download-1626840969'];
    error: any;
  };
}

export interface Put {}

export interface Patch {}

export interface Delete {}

export interface Options {}

export interface Trace {}
