/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '../well-generated-types/claim-shop-public.d.ts';
export interface Get {
  /**
   * 클레임 철회시 유효성 검증 타입 조회하기
   * @description ## 부가설명 및 특이사항
  클레임 철회시 유효성 검증 타입 조회하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png)
   */
  '/guest/claims/{claimNo}/check-withdraw': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['guest-claims-claimNo-check-withdraw-1325271807'];
    error: any;
  };

  /**
   * 클레임 상세보기(클레임 번호)
   * @description ## 부가설명 및 특이사항
  비회원을 위한 클레임 번호로 클레임 세부 내역을 조회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_claim_result%20클레임%20상세보기.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_claim_result%20클레임%20상세보기.png)
   */
  '/guest/claims/{claimNo}/result': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-result422439675'];
    error: any;
  };

  /**
   * 클레임 신청을 위한 정보 조회하기
   * @description ## 부가설명 및 특이사항
  클레임 목록을 조회하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%EC%A1%B0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%EC%A1%B0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%EC%A1%B0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%EC%A1%B0%ED%9A%8C%201-2.png)
   */
  '/guest/order-options/{orderOptionNo}/claims': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query: {
        /**
         * @description 클레임 타입(CANCEL: 취소, RETURN: 반품, EXCHANGE: 교환)
         * @example CANCEL
         */
        claimType: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims475985005'];
    error: any;
  };

  /**
   * 클레임시 변경되는 주문 환불금액 계산하기(단일옵션)
   * @description ## 부가설명 및 특이사항
  선택옵션을 취소할 경우 환불 예상금액을 미리 계산하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불%20계산%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불%20계산%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불%20계산%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불%20계산%201-2.png)
   */
  '/guest/order-options/{orderOptionNo}/claims/estimate': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query: {
        /**
         * @description 클레임사유(CHANGE_MIND: 단순변심(색상,사이즈 등), DEFECTIVE_PRODUCT: 상품불량/파손, WRONG_DELIVERY: 배송누락/오배송, OUT_OF_STOCK_SYSTEM: 재고부족(품절취소), CANCEL_BEFORE_PAY: 입금전취소, WRONG_PRODUCT_DETAIL: 상품상세 정보와 다름, DELAY_DELIVERY: 판매자 배송 지연, OTHERS_SELLER: 기타(판매자 귀책), OTHERS_BUYER: 기타(구매자 귀책), OUT_OF_STOCK: 상품 품절/재고 없음, LATER_INPUT_ORDER: 배송지 미입력 취소, LATER_INPUT_ORDER_RECEIVER_CANCEL: 선물거절취소)
         * @example CHANGE_MIND
         */
        claimReasonType: string;
        /**
         * @description 클레임타입(CANCEL: 취소, RETURN: 반품, EXCHANGE: 교환)
         * @example CANCEL
         */
        claimType: string;
        /**
         * @description 교환할수량(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeCnt: string;
        /**
         * @description 교환할옵션번호(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeOptionNo: string;
        /**
         * @description 교환할상품번호(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeProductNo: string;
        /**
         * @description 취소/반품할 제품수량
         * @example 1
         */
        productCnt: string;
        /**
         * @description 귀책 - responsibleObjectType이 null이면 ClaimReasonType에 매핑되는 귀책 적용(CHANGE_MIND, CANCEL_BEFORE_PAY, OTHERS_BUYER -> BUYER / DEFECTIVE_PRODUCT, WRONG_DELIVERY, OUT_OF_STOCK_SYSTEM, WRONG_PRODUCT_DETAIL, DELAY_DELIVERY, OUT_OF_STOCK, OTHERS_SELLER -> SELLER)(BUYER: 구매자귀책, SELLER: 판매자귀책)
         * @example BUYER
         */
        responsibleObjectType: string;
        /**
         * @description 반품상품 수거방법(SELLER_COLLECT: 판매자수거요청, BUYER_DIRECT_RETURN: 구매자직접반품)
         * @example SELLER_COLLECT
         */
        returnWayType: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-estimate565560004'];
    error: any;
  };

  /**
   * 클레임 상세보기(주문상품 옵션번호)
   * @description ## 부가설명 및 특이사항
  주문상품 옵션번호로 클레임 세부 내역을 조회하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_result%20클레임%20상세보기.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_order-options_claim_result%20클레임%20상세보기.png)
   */
  '/guest/order-options/{orderOptionNo}/claims/result': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-result422439675'];
    error: any;
  };

  /**
   * 회원 클레임 목록 조회하기
   * @description ## 부가설명 및 특이사항
  클레임 목록을 조회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EB%AA%A9%EB%A1%9D%20%EC%A1%B0%ED%9A%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EB%AA%A9%EB%A1%9D%20%EC%A1%B0%ED%9A%8C.png)
   */
  '/profile/claims': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 클레임 구분(null인 경우 전체)
         * @example CANCEL
         */
        claimTypes: string;
        /**
         * @description 조회 종료일(null인 경우 오늘)
         * @example yyyy-mm-dd
         */
        endYmd: string;
        /**
         * @description 목록 카운트 포함 여부(default: false)
         * @example false
         */
        hasTotalCount: string;
        /**
         * @description 페이지 번호
         * @example 1
         */
        pageNumber: string;
        /**
         * @description 한 페이지당 노출 수
         * @example 10
         */
        pageSize: string;
        /**
         * @description 조회 시작일(null인 경우 3개월 전)
         * @example yyyy-mm-dd
         */
        startYmd: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-claims-169614729'];
    error: any;
  };

  /**
   * 회원 클레임 철회시 유효성 검증 타입 조회하기
   * @description ## 부가설명 및 특이사항
  클레임 철회시 유효성 검증 타입 조회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png)
   */
  '/profile/claims/{claimNo}/check-withdraw': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['guest-claims-claimNo-check-withdraw-1325271807'];
    error: any;
  };

  /**
   * 회원 클레임 상세보기(클레임 번호)
   * @description ## 부가설명 및 특이사항
  클레임 번호로 클레임 세부 내역을 조회합니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-2.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-3.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-3.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-4.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_claims_result%20클레임%20상세보기%201-4.png)
   */
  '/profile/claims/{claimNo}/result': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-result422439675'];
    error: any;
  };

  /**
   * 회원 클레임 신청을 위한 정보 조회하기
   * @description ## 부가설명 및 특이사항
  선택옵션에 대한 클레임을 신청할 때 필요한 정보를 조회합니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%8B%A0%EC%B2%AD%EA%B0%80%EB%8A%A5%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query: {
        /**
         * @description 클레임 타입(CANCEL: 취소, RETURN: 반품, EXCHANGE: 교환)
         * @example CANCEL
         */
        claimType: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims475985005'];
    error: any;
  };

  /**
   * 회원 클레임시 변경되는 주문의 환불 예상금액 계산하기(단일옵션)
   * @description ## 부가설명 및 특이사항
  선택옵션을 취소할 경우 환불 예상금액을 미리 계산하는 API입니다.
  
  ## 참고
  ClaimType을 EXCHANGE로 요청 시 exchangeProductNo, exchangeOptionNo, exchangeCnt가 null일 경우
  동일상품, 동일옵션, 교환수량으로 환불예상금액을 조회합니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims/estimate': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query: {
        /**
         * @description 클레임사유(CHANGE_MIND: 단순변심(색상,사이즈 등), DEFECTIVE_PRODUCT: 상품불량/파손, WRONG_DELIVERY: 배송누락/오배송, OUT_OF_STOCK_SYSTEM: 재고부족(품절취소), CANCEL_BEFORE_PAY: 입금전취소, WRONG_PRODUCT_DETAIL: 상품상세 정보와 다름, DELAY_DELIVERY: 판매자 배송 지연, OTHERS_SELLER: 기타(판매자 귀책), OTHERS_BUYER: 기타(구매자 귀책), OUT_OF_STOCK: 상품 품절/재고 없음, LATER_INPUT_ORDER: 배송지 미입력 취소, LATER_INPUT_ORDER_RECEIVER_CANCEL: 선물거절취소)
         * @example CHANGE_MIND
         */
        claimReasonType: string;
        /**
         * @description 클레임타입(CANCEL: 취소, RETURN: 반품, EXCHANGE: 교환)
         * @example CANCEL
         */
        claimType: string;
        /**
         * @description 교환할수량(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeCnt: string;
        /**
         * @description 교환할옵션번호(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeOptionNo: string;
        /**
         * @description 교환할상품번호(claimType이 EXCHANGE인 경우)
         * @example 1
         */
        exchangeProductNo: string;
        /**
         * @description 취소/반품할 제품수량
         * @example 1
         */
        productCnt: string;
        /**
         * @description 귀책 - responsibleObjectType이 null이면 ClaimReasonType에 매핑되는 귀책 적용(CHANGE_MIND, CANCEL_BEFORE_PAY, OTHERS_BUYER -> BUYER / DEFECTIVE_PRODUCT, WRONG_DELIVERY, OUT_OF_STOCK_SYSTEM, WRONG_PRODUCT_DETAIL, DELAY_DELIVERY, OUT_OF_STOCK, OTHERS_SELLER -> SELLER)(BUYER: 구매자귀책, SELLER: 판매자귀책)
         * @example BUYER
         */
        responsibleObjectType: string;
        /**
         * @description 반품상품 수거방법(SELLER_COLLECT: 판매자수거요청, BUYER_DIRECT_RETURN: 구매자직접반품)
         * @example SELLER_COLLECT
         */
        returnWayType: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-estimate565560004'];
    error: any;
  };

  /**
   * 회원 클레임 상세보기(주문상품 옵션번호)
   * @description ## 부가설명 및 특이사항
  주문상품 옵션번호로 클레임 세부 내역을 조회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_result%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EB%B3%B4%EA%B8%B0%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_result%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EB%B3%B4%EA%B8%B0%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_result%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EB%B3%B4%EA%B8%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_result%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EB%B3%B4%EA%B8%B0%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims/result': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-order-options-orderOptionNo-claims-result422439675'];
    error: any;
  };
}

export interface Head {}

export interface Post {
  /**
   * 옵션취소 신청하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 취소신청하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png)
   */
  '/guest/claims/cancel': {
    params?: never;
    body?: components['schemas']['guest-claims-cancel507840867'];
    data: any;
    error: any;
  };

  /**
   * 클레임시 변경되는 주문 환불 예상금액 계산하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 취소할 경우 환불 예상금액을 미리 계산하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png)
   */
  '/guest/claims/estimate': {
    params?: never;
    body?: components['schemas']['guest-claims-estimate325146562'];
    data: components['schemas']['profile-order-options-orderOptionNo-claims-estimate565560004'];
    error: any;
  };

  /**
   * 반품 신청하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 반품하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claims_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claims_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claims_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claims_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png)
   */
  '/guest/claims/return': {
    params?: never;
    body?: components['schemas']['profile-claims-return1565457996'];
    data: any;
    error: any;
  };

  /**
   * [샵바이 프리미엄 전용] 나중 배송 입력 주문 취소하기
   * @description ## 부가설명 및 특이사항
  나중 배송 입력 주문을 취소하는 API입니다.
   */
  '/guest/later-input/shippings/claims/cancel': {
    params?: never;
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 옵션취소 신청하기
   * @description ## 부가설명 및 특이사항
  단일옵션을 취소신청하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png)
   */
  '/guest/order-options/{orderOptionNo}/claims/cancel': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-order-options-orderOptionNo-claims-cancel1362316211'];
    data: any;
    error: any;
  };

  /**
   * 교환 신청하기
   * @description ## 부가설명 및 특이사항
  비회원을 위한 선택옵션을 교환하는 API입니다.
  
  ## Request
  ### 참고사항
  - responsibleObjectType이 null이면 클레임 사유에 해당되는 귀책이 들어갑니다.
   */
  '/guest/order-options/{orderOptionNo}/claims/exchange': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['profile-order-options-orderOptionNo-claims-exchange-223624156'];
    data: any;
    error: any;
  };

  /**
   * 반품 신청하기(단일옵션)
   * @description ## 부가설명 및 특이사항
  단일옵션을 반품하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png)
   */
  '/guest/order-options/{orderOptionNo}/claims/return': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-order-options-orderOptionNo-claims-return-1267846947'];
    data: any;
    error: any;
  };

  /**
   * 주문취소 신청하기
   * @description ## 부가설명 및 특이사항
  주문을 취소신청하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png)
   */
  '/guest/orders/{orderNo}/claims/cancel': {
    params: {
      path: {
        /**
         * @description 주문 번호
         * @example 1
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-orders-orderNo-claims-cancel85707127'];
    data: any;
    error: any;
  };

  /**
   * 회원 옵션취소 신청하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 취소신청하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C.png)
   */
  '/profile/claims/cancel': {
    params?: never;
    body?: components['schemas']['guest-claims-cancel507840867'];
    data: any;
    error: any;
  };

  /**
   * 회원 클레임시 변경되는 주문의 환불 예상금액 계산하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 취소할 경우 환불 예상금액을 미리 계산하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_estimate%20클레임%20시%20변경되는%20주문%20환불계산%201-2.png)
   */
  '/profile/claims/estimate': {
    params?: never;
    body?: components['schemas']['guest-claims-estimate325146562'];
    data: components['schemas']['profile-order-options-orderOptionNo-claims-estimate565560004'];
    error: any;
  };

  /**
   * 회원 반품 신청하기(복수옵션)
   * @description ## 부가설명 및 특이사항
  다수의 선택옵션을 반품하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png)
   */
  '/profile/claims/return': {
    params?: never;
    body?: components['schemas']['profile-claims-return1565457996'];
    data: any;
    error: any;
  };

  /**
   * 회원 옵션취소 신청하기(단일옵션)
   * @description ## 부가설명 및 특이사항
  단일옵션을 취소신청하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims/cancel': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-order-options-orderOptionNo-claims-cancel1362316211'];
    data: any;
    error: any;
  };

  /**
   * 회원 클레임 교환 신청하기
   * @description ## 부가설명 및 특이사항
  선택옵션을 교환하는 API입니다.
   */
  '/profile/order-options/{orderOptionNo}/claims/exchange': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['profile-order-options-orderOptionNo-claims-exchange-223624156'];
    data: any;
    error: any;
  };

  /**
   * 회원 반품 신청하기(단일옵션)
   * @description ## 부가설명 및 특이사항
  단일옵션을 반품하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_order-options_claim_return%20%EB%B0%98%ED%92%88%EC%8B%A0%EC%B2%AD%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims/return': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-order-options-orderOptionNo-claims-return-1267846947'];
    data: any;
    error: any;
  };

  /**
   * 회원 주문취소 신청하기
   * @description ## 부가설명 및 특이사항
  주문을 취소신청하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_claim_cancle%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%201-2.png)
   */
  '/profile/orders/{orderNo}/claims/cancel': {
    params: {
      path: {
        /**
         * @description 주문 번호
         * @example 1
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-orders-orderNo-claims-cancel85707127'];
    data: any;
    error: any;
  };
}

export interface Put {
  /**
   * 환불 계좌 정보 수정하기
   * @description ## 부가설명 및 특이사항
  환불 계좌 정보를 수정하는 비회원용 API입니다.
   */
  '/guest/claims/{claimNo}/account': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-claims-claimNo-account122981901'];
    data: any;
    error: any;
  };

  /**
   * 클레임 철회하기(클레임번호)
   * @description ## 부가설명 및 특이사항
  클레임 번호로 신청된 클레임을 철회하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png)
   */
  '/guest/claims/{claimNo}/withdraw': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 클레임 철회하기(주문상품 옵션번호)
   * @description ## 부가설명 및 특이사항
  주문상품 옵션번호로 신청된 클레임을 철회하는 비회원용 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C.png)
   */
  '/guest/order-options/{orderOptionNo}/claims/withdraw': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 회원 환불 계좌 정보 수정하기
   * @description ## 부가설명 및 특이사항
  환불 계좌 정보를 수정하는 API입니다.
   */
  '/profile/claims/{claimNo}/account': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-claims-claimNo-account122981901'];
    data: any;
    error: any;
  };

  /**
   * 회원 클레임 철회하기(클레임번호)
   * @description ## 부가설명 및 특이사항
  클레임 번호로 신청된 클레임을 철회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_claims_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png)
   */
  '/profile/claims/{claimNo}/withdraw': {
    params: {
      path: {
        /**
         * @description 클레임 번호
         * @example 1
         */
        claimNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 회원 클레임 철회하기(주문상품 옵션번호)
   * @description ## 부가설명 및 특이사항
  주문상품 옵션번호로 신청된 클레임을 철회하는 API입니다.
  
  ## 화면 예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_claim_withdraw%20%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%B2%A0%ED%9A%8C%201-2.png)
   */
  '/profile/order-options/{orderOptionNo}/claims/withdraw': {
    params: {
      path: {
        /**
         * @description 주문 상품 옵션 번호
         * @example 1
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };
}

export interface Patch {}

export interface Delete {}

export interface Options {}

export interface Trace {}
