/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '../well-generated-types/order-shop-public.d.ts';

export interface Get {
  /**
   * 장바구니 가져오기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니 목록을 조회하기 위한 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png)
   */
  '/cart': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-subset84337202'];
    error: any;
  };

  /**
   * 장바구니에서 선택된 상품금액 계산하기
   * @description ## 부가설명 및 특이사항
  장바구니에서 선택된 상품만 계산하여 금액만 리턴하는 API 입니다.
  
  아래 화면예시에서 상품/옵션별 배송비는 업데이트(재계산)하지 못합니다.
  
  cartNo 파라미터 자체를 넘기지 않는 경우 : 장바구니 전체
  
  cartNo 에 빈 값을 넘기는 경우 : 0원
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_calculate%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EC%84%A0%ED%83%9D%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_calculate%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EC%84%A0%ED%83%9D%20%EA%B3%84%EC%82%B0.png)
   */
  '/cart/calculate': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 선택된 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-calculate-1315479487'];
    error: any;
  };

  /**
   * 장바구니에 담긴 상품 개수 가져오기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니에 담긴 상품 개수를 조회하기 위한 API 입니다.
   */
  '/cart/count': {
    params?: never;
    body?: never;
    data: components['schemas']['cart-1843750990'];
    error: any;
  };

  /**
   * 장바구니에서 선택된 항목만 장바구니 그룹별로 재계산하기
   * @description ## 부가설명 및 특이사항
  장바구니에서 선택된 상품만 계산하여 장바구니 상품들과 금액까지 포함해서 리턴하는 API 입니다.
  
  아래 화면예시에서 상품/옵션별 배송비를 함께 업데이트(재계산)할 수 있습니다.
  
  cartNo 파라미터 자체를 넘기지 않는 경우 : 장바구니 전체
  
  cartNo 에 빈 값을 넘기는 경우 : 0원
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_subset%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%EC%97%90%EC%84%9C%20%EC%84%A0%ED%83%9D%EB%90%9C%20%ED%95%AD%EB%AA%A9%EB%A7%8C%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B7%B8%EB%A3%B9%EB%B3%84%EB%A1%9C%20%EC%9E%AC%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_subset%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%EC%97%90%EC%84%9C%20%EC%84%A0%ED%83%9D%EB%90%9C%20%ED%95%AD%EB%AA%A9%EB%A7%8C%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B7%B8%EB%A3%B9%EB%B3%84%EB%A1%9C%20%EC%9E%AC%20%EA%B3%84%EC%82%B0.png)
   */
  '/cart/subset': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 선택된 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-subset84337202'];
    error: any;
  };

  /**
   * 장바구니에 저장된 모든 상품 구매 가능 여부 확인하기
   * @description ## 부가설명 및 특이사항
  장바구니에 저장된 모든 상품의 구매 가능 여부를 확인하는 API 입니다.
   */
  '/cart/validate': {
    params?: never;
    body?: never;
    data: components['schemas']['cart-validate1571487702'];
    error: any;
  };

  /**
   * 장바구니 기준 최대 쿠폰 할인 금액 가져오기
   * @description ## 부가설명 및 특이사항
  장바구니 기준으로 최대 할인이 가능한 쿠폰 정보를 조회합니다.
   */
  '/cart/coupons/maximum': {
    params: {
      path?: never;
      query: {
        /**
         * @description 장바구니 번호
         * @example 1
         */
        cartNo: number;
      };
    };
    body?: never;
    data: components['schemas']['cart-coupons-maximum-961317083'];
    error: any;
  };

  /**
   * 비회원 주문 상세 조회하기
   * @description ## 부가설명 및 특이사항
  비회원 주문의 상세정보를 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-2.png)
   */
  '/guest/orders/{orderNo}': {
    params: {
      path: {
        orderNo: string;
      };
      query?: {
        /**
         * @description 주문옵션타입 (ALL: 전체, CLAIM: 클레임진행, NORMAL: 클레임미진행)
         * @example CLAIM
         */
        orderRequestType: string;
      };
    };
    body?: never;
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * 비회원 주문 상세 조회하기 (클레임 상세사유 포함)
   * @description ## 부가설명 및 특이사항
  주문번호, 토큰으로 상세 데이터를 조회하는 API 입니다.
  
  클레임 상세사유를 포함합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-2.png)
   */
  '/guest/orders/{orderNo}/claim': {
    params: {
      path: {
        orderNo: string;
      };
      query?: {
        /**
         * @description 주문옵션타입 (ALL: 전체, CLAIM: 클레임진행, NORMAL: 클레임미진행)
         * @example CLAIM
         */
        orderRequestType: string;
        /**
         * @description 클레임타입 (CANCEL, RETURN, EXCHANGE, NONE)
         * @example CANCEL
         */
        claimType: string;
      };
    };
    body?: never;
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * 비회원 초기화된 주문 패스워드 전송하기
   * @description ## 부가설명 및 특이사항
  비밀번호를 분실한 사용자를 위해서 주문번호를 이용해 패스워드를 초기화 시키고, 입력한 e-mail 또는 sms로 초기화된 비밀번호를 전달하는 API 입니다.
  주문번호 외의 주문자명, 핸드폰번호, 이메일 등으로 추가 인증 처리를 하기 위해서는 설정 정보를 변경해야 하며, 해당 설정 정보는 샵바이 관리자에게 문의하여 수정 가능합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_forgot-password%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C%20%EC%9E%AC%EC%A0%84%EC%86%A1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[GET]%20guest_orders_forgot-password%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%ED%8C%A8%EC%8A%A4%EC%9B%8C%EB%93%9C%20%EC%9E%AC%EC%A0%84%EC%86%A1.png)
   */
  '/guest/orders/{orderNo}/forgot-password': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 202110081443456213
         */
        orderNo: string;
      };
      query: {
        /**
         * @description 비밀번호 받을 방식 (EMAIL: 이메일, SMS: sms)
         * @example EMAIL
         */
        replyType: string;
        /**
         * @description 주문자 핸드폰 번호
         * @example 01012345678
         */
        mobileNo: string;
        /**
         * @description 주문자 이메일
         * @example test@nhn.com
         */
        email: string;
        /**
         * @description 주문자명
         * @example 홍길동
         */
        name: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 지역별 추가 배송비 목록 조회하기 (배송비템플릿 번호 또는 암호화된 배송 번호 사용)
   * @description ## 부가설명 및 특이사항
  배송비템플릿 번호 또는 암호화된 배송번호로 지역별 추가 배송비 목록을 조회하는 API 입니다.
  (두 필드 중 하나만 입력해야 합니다.)
   */
  '/later-input/areafees': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 배송비 템플릿 번호
         * @example 12345
         */
        templateNo: string;
        /**
         * @description 암호화된 배송 번호
         * @example UFE3Ylo2aUlkSWVuZHVGQjYyS2pZZz09
         */
        encryptedShippingNo: string;
      };
    };
    body?: never;
    data: components['schemas']['later-input-areafees694667795'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 나중배송입력 주문 상세 조회하기
   * @description ## 부가명 및 특이사항
  암호화된 배송 번호로 주문 상세정보를 조회하는 API 입니다.
   */
  '/later-input/order': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 주문옵션타입 (ALL: 전체, CLAIM: 클레임진행, NORMAL: 클레임미진행)
         * @example ALL
         */
        orderRequestType: string;
      };
    };
    body?: never;
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 나중 입력 배송지 조회하기
   * @description ## 부가설명 및 특이사항
  나중에 입력된 배송지를 조회하는 API 입니다.
   */
  '/later-input/shippings': {
    params?: never;
    body?: never;
    data: components['schemas']['later-input-shippings-2025117647'];
    error: any;
  };

  /**
   * 비밀번호 변경 파라미터 조회하기
   * @description ## 부가설명 및 특이사항
  비밀번호 변경 webUI를 띄우기 위한 파라미터를 조회합니다.
   */
  '/my-pay/modify-password': {
    params: {
      path?: never;
      query: {
        /**
         * @description 결제수단 등록 완료 후 client 이동 url
         * @example https://www.nhn-commerce.com
         */
        clientReturnUrl: string;
        /** @description 고객의 CI */
        ci: string;
      };
    };
    body?: never;
    data: components['schemas']['my-pay-modify-password-1997353067'];
    error: any;
  };

  /**
   * 등록된 결제수단 조회하기
   * @description ## 부가설명 및 특이사항
  등록된 결제수단 리스트를 조회합니다.
   */
  '/my-pay/payment-infos': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 결제수단 코드 (신용카드: 01, 계좌: 16)
         * @example 01
         */
        payMethod: string;
        /**
         * @description 신용카드 : 카드사 코드, 계좌 : 은행 코드
         * @example 16
         */
        bankCardCode: string;
      };
    };
    body?: never;
    data: components['schemas']['my-pay-payment-infos1122892899'];
    error: any;
  };

  /**
   * 결제수단 등록 webUrl를 위한 정보 조회하기
   * @description ## 부가설명 및 특이사항
  결제수단 webUI를 띄우기 위한 파라미터를 조회합니다.
  
  payMethod에 입력한 값에 따라 다른 webUI를 응답합니다.
   */
  '/my-pay/register-payment': {
    params: {
      path?: never;
      query: {
        /**
         * @description 결제수단 등록 완료 후 client 이동 url
         * @example https://www.nhn-commerce.com
         */
        clientReturnUrl: string;
        /**
         * @description 결제수단 코드 (신용카드: 01, 계좌: 16)
         * @example 01
         */
        payMethod: string;
      };
    };
    body?: never;
    data: components['schemas']['my-pay-register-payment720401483'];
    error: any;
  };

  /**
   * 회원등록 webUrl를 위한 정보 조회하기
   * @description ## 부가설명 및 특이사항
  회원등록 webUI를 띄우기 위한 파라미터를 조회합니다.
   */
  '/my-pay/register-user': {
    params: {
      path?: never;
      query: {
        /**
         * @description 회원등록 완료 후 client 이동 url
         * @example https://www.nhn-commerce.com
         */
        clientReturnUrl: string;
      };
    };
    body?: never;
    data: components['schemas']['my-pay-register-user1853670927'];
    error: any;
  };

  /**
   * 회원등록후 결제수단 등록으로 바로 넘어갈 수 있도록 필요한 값 조회하기
   * @description ## 부가설명 및 특이사항
  회원등록 및 결제수단 등록을 함께 진행할때, 회원등록 webUI를 띄우기 위한 파라미터를 조회합니다.
  
  회원등록이 성공적으로 끝나면 clientBridgeUrl 로 결제수단등록에 필요한 파라미터들이 urlEncoding이 된 상태로 함께 redirect 됩니다.
   */
  '/my-pay/register-user-with-payment': {
    params: {
      path?: never;
      query: {
        /**
         * @description 회원등록, 결제수단 등록 완료 후 client 이동 url
         * @example https://www.nhn-commerce.com
         */
        clientReturnUrl: string;
        /**
         * @description 회원등록 후 결제수단 등록에 필요한 파라미터와 함께 redirect될 url
         * @example https://www.register-payment-bridge.com
         */
        clientBridgeUrl: string;
      };
    };
    body?: never;
    data: components['schemas']['my-pay-register-user1853670927'];
    error: any;
  };

  /**
   * 주문 설정 값 가져오기
   * @description ## 부가설명 및 특이사항
  주문 설정값을 조회하는 API 입니다.
   */
  '/order-configs': {
    params?: never;
    body?: never;
    data: components['schemas']['order-configs-2107962221'];
    error: any;
  };

  /**
   * 주문서 조회하기
   * @description ## 부가설명 및 특이사항
  주문서 번호를 이용하여 주문상품정보를 조회하는 API 입니다.
  
  비회원 주문인 경우, accessToken을 null로 보냅니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png)
   */
  '/order-sheets/{orderSheetNo}': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: {
        /**
         * @description 회원주소포함여부
         * @example false
         */
        includeMemberAddress: boolean;
      };
    };
    body?: never;
    data: components['schemas']['order-sheets-orderSheetNo515085756'];
    error: any;
  };

  /**
   * 적용할 수 있는 쿠폰 정보 조회하기
   * @description ## 부가설명 및 특이사항
  해당 주문에 적용할 수 있는 쿠폰을 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets_coupons%20%EC%A0%81%EC%9A%A9%ED%95%A0%20%EC%88%98%20%EC%9E%88%EB%8A%94%20%EC%BF%A0%ED%8F%B0%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[GET]%20order-sheets_coupons%20%EC%A0%81%EC%9A%A9%ED%95%A0%20%EC%88%98%20%EC%9E%88%EB%8A%94%20%EC%BF%A0%ED%8F%B0%20%EC%A0%95%EB%B3%B4%20%EC%A1%B0%ED%9A%8C.png)
   */
  '/order-sheets/{orderSheetNo}/coupons': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: {
        /**
         * @description 채널타입
         * @example NAVER_EP
         */
        channelType: string;
      };
    };
    body?: never;
    data: components['schemas']['order-sheets-orderSheetNo-coupons-maximum-1318207009'];
    error: any;
  };

  /**
   * 이전주문 검색
   * @description 이전주문 검색
   */
  '/previous-orders': {
    params: {
      path?: never;
      query: {
        /**
         * @description 검색 타입
         * @example ORDER_NO, ORDERER_NAME, PRODUCT_NAME
         */
        searchType: string;
        /**
         * @description 검색어
         * @example 홍길동
         */
        keyword: string;
        /**
         * @description 조회시작일
         * @example "2023-10-05T00:00:00.000Z"
         */
        startYmd: string;
        /**
         * @description 조회종료일
         * @example "2024-01-05T00:00:00.000Z"
         */
        endYmd: string;
        /**
         * @description 페이지 번호
         * @example 1
         */
        page: number;
        /**
         * @description 페이지당 노출 개수(최대 200)
         * @example 30
         */
        size: number;
      };
    };
    body?: never;
    data: components['schemas']['previous-orders-1111310132'];
    error: any;
  };

  /**
   * 이전주문 상세조회
   * @description 이전주문 상세조회
   */
  '/previous-orders/{orderNo}': {
    params: {
      path: {
        /**
         * @description 주문 번호
         * @example 202206151234567890
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['previous-orders-orderNo-942189284'];
    error: any;
  };

  /**
   * 비회원 이전주문 상세조회
   * @description 비회원 이전주문 상세조회
   */
  '/previous-orders/guest/{orderNo}': {
    params: {
      path: {
        /**
         * @description 주문 번호
         * @example 202206151234567890
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['previous-orders-orderNo-942189284'];
    error: any;
  };

  /**
   * 주문 리스트 조회하기
   * @description ## 부가설명 및 특이사항
  시작일 종료일 사이의 주문리스트를 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%A1%B0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%A1%B0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%A1%B0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EB%A6%AC%EC%8A%A4%ED%8A%B8%20%EC%A1%B0%ED%9A%8C%201-2.png)
   */
  '/profile/orders': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 주문상태 (DEPOSIT_WAIT: Deposit Wait, PAY_DONE: Pay Done, PRODUCT_PREPARE: Product Prepare, DELIVERY_PREPARE: Delivery Prepare, DELIVERY_ING: Delivering, DELIVERY_DONE: Delivery Done, BUY_CONFIRM: Buy Confirm, CANCEL_DONE: Cancel Done, RETURN_DONE: Return Done, EXCHANGE_DONE: Exchange Done, CANCEL_PROCESSING: 취소처리중, RETURN_PROCESSING: 반품처리중, EXCHANGE_WAITING: 교환대기중, EXCHANGE_PROCESSING: 교환처리중) * (null인 경우 전체)
         * @example DEPOSIT_WAIT,PAY_DONE
         */
        orderRequestTypes: string;
        /**
         * @description 페이지번호
         * @example 1
         */
        pageNumber: number;
        /**
         * @description 한 페이지당 노출 수(최대 200)
         * @example 10
         */
        pageSize: number;
        /**
         * @description 목록 카운트 포함 여부(default: false)
         * @example false
         */
        hasTotalCount: boolean;
        /**
         * @description 조회 시작일(yyyy-MM-dd), null인 경우 3개월 전 날짜로 조회
         * @example YYYY-MM-DD
         */
        startYmd: string;
        /**
         * @description 조회 종료일(yyyy-MM-dd), null인 경우 오늘 날짜로 조회
         * @example YYYY-MM-DD
         */
        endYmd: string;
        /**
         * @description 검색 타입
         * @example PRODUCT_NAME
         */
        searchType: string;
        /** @description 검색어 */
        keyword: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-orders898513268'];
    error: any;
  };

  /**
   * 배송지 목록 가져오기
   * @description ## 부가설명 및 특이사항
  주소지정보를 조회하는 API 입니다.
  
  기본 배송지(defaultAddress)가 가장 상단에 노출되며, 이후 최근 사용된 주소 순서로 나열됩니다 (최근 사용시간의 역순로 정렬)
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png)
   */
  '/profile/shipping-addresses': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-shipping-addresses1302588806'];
    error: any;
  };

  /**
   * 주문 상세 조회하기
   * @description ## 부가설명 및 특이사항
  주문번호로 상세 데이터를 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-2.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-3.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C%201-3.png)
   */
  '/profile/orders/{orderNo}': {
    params: {
      path: {
        orderNo: string;
      };
      query?: {
        /**
         * @description 주문옵션타입 (ALL: 전체, CLAIM: 클레임진행, NORMAL: 클레임미진행)
         * @example CLAIM
         */
        orderRequestType: string;
      };
    };
    body?: never;
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * 최근 배송지 가져오기
   * @description ## 부가설명 및 특이사항
  로그인한 사용자의 최근배송지 목록을 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses_recent%20%EC%B5%9C%EA%B7%BC%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses_recent%20%EC%B5%9C%EA%B7%BC%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png)
   */
  '/profile/shipping-addresses/recent': {
    params?: never;
    body?: never;
    data: components['schemas']['profile-shipping-addresses-recent-1693328833'];
    error: any;
  };

  /**
   * 배송지 가져오기
   * @description ## 부가설명 및 특이사항
  선택한 배송지의 세부 정보를 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png)
   */
  '/profile/shipping-addresses/{addressNo}': {
    params: {
      path: {
        /**
         * @description 배송지 번호
         * @example 1
         */
        addressNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-shipping-addresses-2110780552'];
    error: any;
  };

  /**
   * 주문 상태별 주문 옵션별 수량 조회하기
   * @description ## 부가설명 및 특이사항
  시작일 종료일 사이의 주문 상태별 주문 옵션별 수량을 조회하는 API 입니다.
  
  옵션별로 카운트 합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_summary_status%20%EC%83%81%ED%83%9C%EB%B3%84%20%EC%A3%BC%EB%AC%B8%20%EC%98%B5%EC%85%98%EB%B3%84%20%EC%88%98%EB%9F%89.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_summary_status%20%EC%83%81%ED%83%9C%EB%B3%84%20%EC%A3%BC%EB%AC%B8%20%EC%98%B5%EC%85%98%EB%B3%84%20%EC%88%98%EB%9F%89.png)
   */
  '/profile/order-options/summary/status': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 조회 시작일(yyyy-MM-dd), null인 경우 3개월 전 날짜로 조회
         * @example YYYY-MM-DD
         */
        startYmd: string;
        /**
         * @description 조회 종료일(yyyy-MM-dd), null인 경우 오늘 날짜로 조회
         * @example YYYY-MM-DD
         */
        endYmd: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-orders-summary-status1277891083'];
    error: any;
  };

  /**
   * 주문 상태별 주문 수량 및 금액 조회하기
   * @description ## 부가설명 및 특이사항
  시작일과 종료일 사이의 주문 상태별 주문 수량과 결제 금액 조회하는 API 입니다.
   */
  '/profile/orders/summary/amount': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 주문 상태 (DEPOSIT_WAIT: Deposit Wait, PAY_DONE: Pay Done, PRODUCT_PREPARE: Product Prepare, DELIVERY_PREPARE: Delivery Prepare, DELIVERY_ING: Delivering, DELIVERY_DONE: Delivery Done, BUY_CONFIRM: Buy Confirm, CANCEL_DONE: Cancel Done, RETURN_DONE: Return Done, EXCHANGE_DONE: Exchange Done, PAY_WAIT: Pay Wait, PAY_CANCEL: Pay Cancel, PAY_FAIL: Pay Fail, DELETE: Delete, EXCHANGE_WAIT: Exchange Wait, REFUND_DONE: Refund Done)
         * @example DEPOSIT_WAIT
         */
        orderStatusType: string;
        /**
         * @description 조회 시작일(yyyy-MM-dd), null인 경우 3개월 전 날짜로 조회
         * @example YYYY-MM-DD
         */
        startYmd: string;
        /**
         * @description 조회 종료일(yyyy-MM-dd), null인 경우 오늘 날짜로 조회
         * @example YYYY-MM-DD
         */
        endYmd: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-orders-summary-amount-1975758925'];
    error: any;
  };

  /**
   * 주문 상태별 주문 수량 조회하기
   * @description ## 부가설명 및 특이사항
  시작일 종료일 사이의 주문 상태별 주문 옵션별 수량을 조회하는 API 입니다.
  
  옵션별로 카운트 합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_summary_status%20%EC%83%81%ED%83%9C%EB%B3%84%20%EC%A3%BC%EB%AC%B8%20%EC%98%B5%EC%85%98%EB%B3%84%20%EC%88%98%EB%9F%89.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_order-options_summary_status%20%EC%83%81%ED%83%9C%EB%B3%84%20%EC%A3%BC%EB%AC%B8%20%EC%98%B5%EC%85%98%EB%B3%84%20%EC%88%98%EB%9F%89.png)
   */
  '/profile/orders/summary/status': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 조회 시작일(yyyy-MM-dd), null인 경우 3개월 전 날짜로 조회
         * @example YYYY-MM-DD
         */
        startYmd: string;
        /**
         * @description 조회 종료일(yyyy-MM-dd), null인 경우 오늘 날짜로 조회
         * @example YYYY-MM-DD
         */
        endYmd: string;
      };
    };
    body?: never;
    data: components['schemas']['profile-orders-summary-status1277891083'];
    error: any;
  };

  /**
   * 전체 주문취소를 위한 주문 상세 조회하기 (클레임 상세사유 포함)
   * @description ## 부가설명 및 특이사항
  주문번호로 상세 데이터를 조회하는 API 입니다.
  
  클레임 상세사유를 포합합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[GET]%20profile_orders_claim%20%EC%A0%84%EC%B2%B4%20%EC%A3%BC%EB%AC%B8%EC%B7%A8%EC%86%8C%EB%A5%BC%20%EC%9C%84%ED%95%9C%20%EC%A3%BC%EB%AC%B8%20%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C(%ED%81%B4%EB%A0%88%EC%9E%84%20%EC%83%81%EC%84%B8%EC%82%AC%EC%9C%A0%20%ED%8F%AC%ED%95%A8)%201-2.png)
   */
  '/profile/orders/{orderNo}/claim': {
    params: {
      path: {
        orderNo: string;
      };
      query: {
        /**
         * @description 주문옵션타입 (DEPOSIT_WAIT: Deposit Wait, PAY_DONE: Pay Done, PRODUCT_PREPARE: Product Prepare, DELIVERY_PREPARE: Delivery Prepare, DELIVERY_ING: Delivering, DELIVERY_DONE: Delivery Done, BUY_CONFIRM: Buy Confirm, CANCEL_DONE: Cancel Done, RETURN_DONE: Return Done, EXCHANGE_DONE: Exchange Done, PAY_WAIT: Pay Wait, PAY_CANCEL: Pay Cancel, PAY_FAIL: Pay Fail, DELETE: Delete, EXCHANGE_WAIT: Exchange Wait, REFUND_DONE: Refund Done)
         * @example CLAIM
         */
        orderRequestType: string;
        /**
         * @description 클레임타입 (CANCEL, RETURN, EXCHANGE, NONE)
         * @example CANCEL,RETURN,EXCHANGE
         */
        claimType: string;
      };
    };
    body?: never;
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 조회하기
   * @description ## 부가설명 및 특이사항
  정기결제를 조회하는 API 입니다.
   */
  '/recurring-payments': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 시작일
         * @example YYYY-MM-DD
         */
        startYmd: string;
        /**
         * @description 종료일
         * @example YYYY-MM-DD
         */
        endYmd: string;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments313754189'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 카드 조회하기
   * @description ## 부가설명 및 특이사항
  정기결제 카드를 조회하는 API 입니다.
  
  회원에게 등록된 정기결제 카드가 없을 시 400 에러로 응답합니다.
   */
  '/recurring-payments/card': {
    params?: never;
    body?: never;
    data: components['schemas']['recurring-payments-card247629157'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니 조회하기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니 목록을 조회하기 위한 API 입니다.
  
  참고: 500원 미만의 상품은 invalidProducts에 포함하여 응답합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0%201-2.png)
   */
  '/recurring-payments/cart': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-subset84337202'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 다음배송일자 조회하기
   * @description ## 부가설명 및 특이사항
  정기결제 다음 배송일자를 조회하는 API 입니다.
  
  정기결제 신청번호가 없으면 현재 날짜 기준으로 조회합니다.
   */
  '/recurring-payments/next-recurring-date': {
    params: {
      path?: never;
      query: {
        /**
         * @description 정기결제 신청번호
         * @example 202108251705594
         */
        recurringPaymentId: string;
        /**
         * @description 정기결제 주기
         * @example 1
         */
        cycle: number;
        /**
         * @description 정기결제 일시
         * @example 1
         */
        cycleDate: number;
        /** @description 정기결제 배송주기 타입^|(MONTH: Month, WEEK: Week) */
        cycleType: number;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-delivery-cycle-1813425842'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니에서 선택된 상품금액 계산하기
   * @description ## 부가설명 및 특이사항
  장바구니에서 선택된 상품만 계산하여 금액만 리턴하는 API 입니다.
  
  아래 화면예시에서 상품/옵션별 배송비는 업데이트(재계산)하지 못합니다.
  
  cartNo 파라미터 자체를 넘기지 않는 경우 : 장바구니 전체
  
  cartNo 에 빈 값을 넘기는 경우 : 0원
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_calculate%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EC%84%A0%ED%83%9D%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_calculate%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EC%84%A0%ED%83%9D%20%EA%B3%84%EC%82%B0.png)
   */
  '/recurring-payments/cart/calculate': {
    params: {
      path?: never;
      query: {
        /**
         * @description 선택된 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-calculate-1315479487'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니에서 선택된 항목만 장바구니 그룹별로 재계산하기
   * @description ## 부가설명 및 특이사항
  장바구니에서 선택된 상품만 계산하여 장바구니 상품들과 금액까지 포함해서 리턴하는 API 입니다.
  
  아래 화면예시에서 상품/옵션별 배송비를 함께 업데이트(재계산)할 수 있습니다.
  
  cartNo 파라미터 자체를 넘기지 않는 경우 : 장바구니 전체
  
  cartNo 에 빈 값을 넘기는 경우 : 0원
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_subset%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%EC%97%90%EC%84%9C%20%EC%84%A0%ED%83%9D%EB%90%9C%20%ED%95%AD%EB%AA%A9%EB%A7%8C%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B7%B8%EB%A3%B9%EB%B3%84%EB%A1%9C%20%EC%9E%AC%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/cart/[GET]%20cart_subset%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%EC%97%90%EC%84%9C%20%EC%84%A0%ED%83%9D%EB%90%9C%20%ED%95%AD%EB%AA%A9%EB%A7%8C%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B7%B8%EB%A3%B9%EB%B3%84%EB%A1%9C%20%EC%9E%AC%20%EA%B3%84%EC%82%B0.png)
   */
  '/recurring-payments/cart/subset': {
    params: {
      path?: never;
      query: {
        /**
         * @description 선택된 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: never;
    data: components['schemas']['recurring-payments-cart-subset84337202'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 주문서 가져오기
   * @description ## 부가설명 및 특이사항
  정기결제 주문서를 조회하는 API 입니다.
  
  참고 : 주문서 내에 가격이 500원 미만인 상품이 존재하면 400 에러를 응답합니다.
   */
  '/recurring-payments/order-sheets/{orderSheetNo}': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: {
        /**
         * @description 회원주소포함여부
         * @example false
         */
        includeMemberAddress: boolean;
      };
    };
    body?: never;
    data: components['schemas']['order-sheets-orderSheetNo515085756'];
    error: any;
  };

  /**
   * 배송 enum 정보 조회
   * @description 배송 enum 정보 조회
   */
  '/shippings/enums': {
    params?: never;
    body?: never;
    data: components['schemas']['shippings-enums-1215321466'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 나중 입력 배송지 조회하기
   * 
   * @description ## 부가설명 및 특이사항
  나중에 입력된 배송지를 조회하는 API 입니다.
   */
  '/shippings/{encryptedShippingNo}/later-input': {
    params: {
      path: {
        /**
         * @description 암호화된 배송 번호
         * @example UFE3Ylo2aUlkSWVuZHVGQjYyS2pZZz09
         */
        encryptedShippingNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['shippings-encryptedShippingNo-later-input-305682154'];
    error: any;
  };

  /**
   * [샵바이프로 전용] 미확인 입급자 조회하기
   * @description ## 부가설명 및 특이사항
  미확인 입금자를 조회하는 API 입니다.
   */
  '/unidentifiedDepositors': {
    params: {
      path?: never;
      query: {
        /**
         * @description 쇼핑몰 번호
         * @example 1
         */
        mallNo: string;
        /**
         * @description 입금일
         * @example YYYY-MM-DD
         */
        depositYmd: string;
        /**
         * @description 입금자명
         * @example test
         */
        name: string;
        /**
         * @description 페이지 번호
         * @example 1
         */
        page: string;
        /**
         * @description 페이지당 노출 개수
         * @example 30
         */
        size: string;
      };
    };
    body?: never;
    data: components['schemas']['unidentifiedDepositors2122825748'];
    error: any;
  };

  /**
   * [샵바이프로 전용] 미확인 입금자 설정 조회하기
   * @description ## 부가설명 및 특이사항
  미확인 입금자 설정을 조회하는 API 입니다.
   */
  '/unidentifiedDepositors/config': {
    params?: never;
    body?: never;
    data: components['schemas']['unidentifiedDepositors-config792080057'];
    error: any;
  };

  /**
   * 위시리스트 리스트 가져오기
   * @description ## 부가설명 및 특이사항
  위시리스트를 조회하는 API 입니다.
   */
  '/wish': {
    params?: never;
    body?: never;
    data: components['schemas']['wish-938362791'];
    error: any;
  };

  /**
   * 위시리스트 개수 가져오기
   * @description ## 부가설명 및 특이사항
  위시리스트 개수를 조회하는 API 입니다.
   */
  '/wish/count': {
    params?: never;
    body?: never;
    data: components['schemas']['wish-count655543630'];
    error: any;
  };
}

export interface Head {}

export interface Post {
  /**
   * 장바구니 등록하기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니에 상품(옵션)을 추가하는 API 입니다.
   */
  '/cart': {
    params?: never;
    body?: components['schemas']['cart977837260'];
    data: components['schemas']['cart-1843750990'];
    error: any;
  };

  /**
   * 비회원 장바구니 계산하기
   * @description ## 부가설명 및 특이사항
  비회원의 장바구니금액 및 합배송 상품을 계산하여 목록을 가져오는 API 입니다.
  
  쇼핑몰배송의 경우, 파트너명을 '쇼핑몰배송'으로 내려줍니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-2.png)
   */
  '/guest/cart': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: components['schemas']['guest-cart1944647664'];
    data: components['schemas']['recurring-payments-guest-cart816762413'];
    error: any;
  };

  /**
   * 비회원 주문 토큰 발급하기
   * @description ## 부가설명 및 특이사항
  주문번호, 패스워드, 이름, 핸드폰번호, 이메일로 주문 상세를 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%ED%86%A0%ED%81%B0%20%EB%B0%9C%EA%B8%89.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_orders%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%EC%A3%BC%EB%AC%B8%20%ED%86%A0%ED%81%B0%20%EB%B0%9C%EA%B8%89.png)
   */
  '/guest/orders/{orderNo}': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 2020010101012
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-orders-orderNo1327590381'];
    data: components['schemas']['guest-orders-orderNo-236010523'];
    error: any;
  };

  /**
   * [샵바이 프리미엄 사용 불가] 비회원 현금영수증 신청하기
   * @description ## 부가설명 및 특이사항
  구매자가 무통장입금 주문에 대하여 현금영수증을 발급하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_orders_cashReceipt%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%ED%98%84%EA%B8%88%EC%98%81%EC%88%98%EC%A6%9D%20%EC%8B%A0%EC%B2%AD.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_orders_cashReceipt%20%EB%B9%84%ED%9A%8C%EC%9B%90%20%ED%98%84%EA%B8%88%EC%98%81%EC%88%98%EC%A6%9D%20%EC%8B%A0%EC%B2%AD.png)
   */
  '/guest/orders/{orderNo}/cashReceipt': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 2020042100000001
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['guest-orders-orderNo-cashReceipt-2137606971'];
    data: components['schemas']['guest-orders-orderNo-cashReceipt704793082'];
    error: any;
  };

  /**
   * 주 결제수단 설정하기
   * @description ## 부가설명 및 특이사항
  주 결제수단을 설정합니다.
  
  신용카드와 계좌는 주 결제수단을 각각 관리합니다.
   */
  '/my-pay/modify-main-payment': {
    params?: never;
    body?: components['schemas']['my-pay-modify-main-payment667999033'];
    data: any;
    error: any;
  };

  /**
   * 주문서 작성하기
   * @description ## 부가설명 및 특이사항
  주문을 진행 할 상품정보를 전달하는 API 입니다.
  
  주문서 페이지 진입전에 실행합니다.
  
  비회원 주문인 경우 accessToken을 null로 보냅니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EC%83%9D%EC%84%B1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets%20%EC%A3%BC%EB%AC%B8%EC%84%9C%20%EC%83%9D%EC%84%B1.png)
   */
  '/order-sheets': {
    params?: never;
    body?: components['schemas']['order-sheets-1565420976'];
    data: components['schemas']['recurring-payments-order-sheets1613778223'];
    error: any;
  };

  /**
   * 쿠폰 및 배송지 정보가 적용된 금액 조회하기
   * @description ## 부가설명 및 특이사항
  쿠폰 및 배송비 계산이 적용된 주문서 금액을 조회하는 API 입니다.
  
  비회원 주문인 경우 accessToken을 null로 보냅니다.
  
  jibunAddress를 입력해줘야 지역별 추가배송비 계산이 가능합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_calculate%20%EC%BF%A0%ED%8F%B0%20%EB%B0%8F%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%A0%95%EB%B3%B4%EA%B0%80%20%EC%A0%81%EC%9A%A9%EB%90%9C%20%EA%B8%88%EC%95%A1%EC%9D%84%20%EB%85%B8%EC%B6%9C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_calculate%20%EC%BF%A0%ED%8F%B0%20%EB%B0%8F%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%A0%95%EB%B3%B4%EA%B0%80%20%EC%A0%81%EC%9A%A9%EB%90%9C%20%EA%B8%88%EC%95%A1%EC%9D%84%20%EB%85%B8%EC%B6%9C.png)
   */
  '/order-sheets/{orderSheetNo}/calculate': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['order-sheets-orderSheetNo-calculate-1073273719'];
    data: components['schemas']['order-sheets-orderSheetNo-calculate559250314'];
    error: any;
  };

  /**
   * 쿠폰 적용하기
   * @description ## 부가설명 및 특이사항
  해당 주문서에 선택된 쿠폰을 적용하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_apply%20%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_apply%20%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9.png)
   */
  '/order-sheets/{orderSheetNo}/coupons/apply': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['order-sheets-orderSheetNo-coupons-apply-1755276020'];
    data: components['schemas']['order-sheets-orderSheetNo-calculate559250314'];
    error: any;
  };

  /**
   * 쿠폰적용금액 계산하기
   * @description ## 부가설명 및 특이사항
  쿠폰을 적용한 금액을 미리 조회하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_calculate%20%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9%20%EA%B8%88%EC%95%A1%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_calculate%20%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9%20%EA%B8%88%EC%95%A1%20%EA%B3%84%EC%82%B0.png)
   */
  '/order-sheets/{orderSheetNo}/coupons/calculate': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['order-sheets-orderSheetNo-coupons-apply-1755276020'];
    data: components['schemas']['order-sheets-orderSheetNo-coupons-maximum-1318207009'];
    error: any;
  };

  /**
   * 최대쿠폰적용금액 계산하기
   * @description ## 부가설명 및 특이사항
  해당 주문서에서 최대로 할인 받을 수 있는 상품쿠폰을 계산하는 API 입니다.
  
  장바구니 쿠폰은 계산에서 제외됩니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_maximum%20%EC%B5%9C%EB%8C%80%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9%EA%B8%88%EC%95%A1%20%EA%B3%84%EC%82%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/ordersheet/[POST]%20order-sheets_coupons_maximum%20%EC%B5%9C%EB%8C%80%EC%BF%A0%ED%8F%B0%EC%A0%81%EC%9A%A9%EA%B8%88%EC%95%A1%20%EA%B3%84%EC%82%B0.png)
   */
  '/order-sheets/{orderSheetNo}/coupons/maximum': {
    params: {
      path: {
        orderSheetNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['order-sheets-orderSheetNo-coupons-maximum-441133280'];
    data: components['schemas']['order-sheets-orderSheetNo-coupons-maximum-1318207009'];
    error: any;
  };

  /**
   * 주문 예약하기
   * @description ## 부가설명 및 특이사항
  주문을 예약하는 API 입니다.
  
  [주문서화면](https://shopby.works/guide/skin/dev-cover/order#pay-button) 가이드의'결제편의모듈'항목 참고바랍니다.
  
  payType과 PgType 값은 [https://docs.shopby.co.kr/?url.primaryName=order/#/OrderSheet/get-order-sheet](https://docs.shopby.co.kr/?url.primaryName=order/#/OrderSheet/get-order-sheet) 응답값 내 availablePayTypes 참고부탁드립니다
  
  앱(iOS/AOS) 결제 개발 가이드: [https://workspace.shopby.co.kr/guide/skin/dev-cover/app-payment-module?lv=11](https://workspace.shopby.co.kr/guide/skin/dev-cover/app-payment-module?lv=11)
   */
  '/payments/reserve': {
    params?: never;
    body?: components['schemas']['payments-reserve1642123685'];
    data: components['schemas']['payments-reserve-92877080'];
    error: any;
  };

  /**
   * 네이버페이 주문서 생성하기
   * @description ## 부가설명 및 특이사항
  네이버페이 주문서를 생성하는 API 입니다.
   */
  '/payments/naver/ordersheet': {
    params?: never;
    body?: components['schemas']['payments-naver-ordersheet-1158900846'];
    data: components['schemas']['payments-naver-wish-list1116014589'];
    error: any;
  };

  /**
   * 네이버페이 찜 등록하기
   * @description ## 부가설명 및 특이사항
  네이버페이 찜을 등록하는 API 입니다.
   */
  '/payments/naver/wish-list': {
    params?: never;
    body?: components['schemas']['payments-naver-wish-list-1666491885'];
    data: components['schemas']['payments-naver-wish-list1116014589'];
    error: any;
  };

  /**
   * 이전주문 비회원 토큰 발급
   * @description 이전주문 비회원 토큰 발급
   */
  '/previous-orders/guest/{orderNo}': {
    params: {
      path: {
        /**
         * @description 주문 번호
         * @example 202206151234567890
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['payments-naver-wish-list1116014589'];
    data: components['schemas']['previous-orders-orderNo-942189284'];
    error: any;
  };

  /**
   * 배송지 등록하기
   * @description ## 부가설명 및 특이사항
  주소지정보를 추가하는 API 입니다.
  
  주소록 배송지(AddressType.BOOK)는 제한없이 등록이 가능하고 최근 배송지(AddressType.RECENT)는 최대 10개 까지 등록이 됩니다.
  
  최근 배송지가 10개가 등록된 상태에서 추가로 최근 배송지를 등록하면 기본 배송지가 아닌 최근 배송지중에 사용한지 가장 오래된 최근 배송지가 삭제 됩니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[GET]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EB%AA%A9%EB%A1%9D%20%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0.png)
   */
  '/profile/shipping-addresses': {
    params?: never;
    body?: components['schemas']['profile-shipping-addresses790608702'];
    data: components['schemas']['profile-shipping-addresses-2110780552'];
    error: any;
  };

  /**
   * [샵바이 프리미엄 사용 불가] 현금영수증 신청하기
   * @description ## 부가설명 및 특이사항
  구매자가 무통장입금 주문에 대하여 현금영수증을 발급하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_cashReceipt%20%ED%98%84%EA%B8%88%EC%98%81%EC%88%98%EC%A6%9D%20%EC%8B%A0%EC%B2%AD.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[POST]%20profile_orders_cashReceipt%20%ED%98%84%EA%B8%88%EC%98%81%EC%88%98%EC%A6%9D%20%EC%8B%A0%EC%B2%AD.png)
   */
  '/profile/orders/{orderNo}/cashReceipt': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 2020042100000001
         */
        orderNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['profile-orders-orderNo-cashReceipt-1665654877'];
    data: components['schemas']['profile-orders-orderNo-cashReceipt-2129761381'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 신청하기
   * @description ## 부가설명 및 특이사항
  정기결제를 신청하는 API 입니다.
  
  참고 : 정기결제 신청 시점에 가격이 500원 미만인 상품이 존재하면 400 에러를 응답합니다.
   */
  '/recurring-payments': {
    params?: never;
    body?: components['schemas']['recurring-payments1350971406'];
    data: components['schemas']['recurring-payments-976798933'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니에 추가하기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니에 상품(옵션)을 추가하는 API 입니다.
  
  상품금액이 500원 미만일 경우 장바구니 담기가 불가능합니다.
  
  참고:정기결제(배송) API화면가이드 https://shopby.works/support/forum/30659
   */
  '/recurring-payments/cart': {
    params?: never;
    body?: components['schemas']['cart977837260'];
    data: components['schemas']['recurring-payments-cart830330865'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 주문서 작성하기
   * @description ## 부가설명 및 특이사항
  정기결제 주문을 진행할 상품정보를 전달하는 API 입니다.
  
  주문서 페이지 진입전에 실행합니다.
  
  참고 : 주문서 생성시점에 가격이 500원 미만인 상품이 존재하면 400 에러를 응답합니다.
   */
  '/recurring-payments/order-sheets': {
    params?: never;
    body?: components['schemas']['recurring-payments-order-sheets-1030890519'];
    data: components['schemas']['recurring-payments-order-sheets1613778223'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 비회원 장바구니 계산하기
   * @description ## 부가설명 및 특이사항
  비회원의 장바구니금액 및 합배송 상품을 계산하여 목록을 가져오는 API 입니다.
  
  쇼핑몰배송의 경우, 파트너명을 '쇼핑몰배송'으로 내려줍니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[POST]%20guest_cart%20%EA%B2%8C%EC%8A%A4%ED%8A%B8%20%EC%9E%A5%EB%B0%94%EA%B5%AC%EB%8B%88%20%EA%B3%84%EC%82%B0%201-2.png)
   */
  '/recurring-payments/guest/cart': {
    params?: {
      path?: never;
      query?: {
        /**
         * @description 구매하지 못하는 상품 분할여부
         * @example true
         */
        divideInvalidProducts: boolean;
      };
    };
    body?: components['schemas']['recurring-payments-guest-cart-1583522844'];
    data: components['schemas']['recurring-payments-guest-cart816762413'];
    error: any;
  };

  /**
   * 위시리스트 등록하기
   * @description ## 부가설명 및 특이사항
  위시리스트를 등록하는 API 입니다.
   */
  '/wish': {
    params?: never;
    body?: components['schemas']['wish1402593107'];
    data: components['schemas']['wish-count655543630'];
    error: any;
  };
}

export interface Put {
  /**
   * 장바구니 수정하기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니의 상품 중 구매 수량과 사용자 입력형 옵션을 수정하는 API 입니다.
  
  옵션 종류는 변경할 수 없습니다.
  
  옵션변경은 변경할 옵션을 삭제한 후 신규등록하는 방법으로 수정합니다.
   */
  '/cart': {
    params?: never;
    body?: components['schemas']['cart752002737'];
    data: any;
    error: any;
  };

  /**
   * 비회원 상품 주문 구매확정 처리하기
   * @description ## 부가설명 및 특이사항
  배송중, 배송완료 상태의 상품주문을 구매확정 처리하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_confirm%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EA%B5%AC%EB%A7%A4%ED%99%95%EC%A0%95.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_confirm%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EA%B5%AC%EB%A7%A4%ED%99%95%EC%A0%95.png)
   */
  '/guest/order-options/{orderOptionNo}/confirm': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 121212
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 비회원 상품 주문 배송완료 처리하기
   * @description ## 부가설명 및 특이사항
  배송중 상태의 상품주문을 배송완료 처리하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_delivery-done%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EB%B0%B0%EC%86%A1%EC%99%84%EB%A3%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_order-options_delivery-done%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EB%B0%B0%EC%86%A1%EC%99%84%EB%A3%8C.png)
   */
  '/guest/order-options/{orderOptionNo}/delivery-done': {
    params: {
      path: {
        /**
         * @description 주문번호
         * @example 121212
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 비회원 주문단위 배송정보 수정하기
   * @description ## 부가설명 및 특이사항
  주문번호에 속한 배송정보를 일괄 수정하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95%201-1.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95%201-1.png)
  [![](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95%201-2.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/guest/[PUT]%20guest_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95%201-2.png)
   */
  '/guest/orders/{orderNo}/deliveries': {
    params: {
      path: {
        /**
         * @description 주문옵션번호
         * @example 2010121010
         */
        orderNo: string;
      };
      query?: {
        /**
         * @description 주소지 추가 여부
         * @example true
         */
        add: boolean;
      };
    };
    body?: components['schemas']['guest-orders-orderNo-deliveries1990893381'];
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 나중 입력 배송지 정보 수정하기
   * @description ## 부가설명 및 특이사항
  나중에 입력된 배송지 정보를 수정하는 API 입니다.
   */
  '/later-input/shippings': {
    params?: never;
    body?: components['schemas']['shippings-encryptedShippingNo-later-input350289840'];
    data: any;
    error: any;
  };

  /**
   * 네이버페이 상품구매 검증하기
   * @description ## 부가설명 및 특이사항
  네이버페이 상품구매 가능 여부를 검증하는 API 입니다.
   */
  '/payments/naver/validate': {
    params?: never;
    body?: components['schemas']['payments-naver-validate-1868535393'];
    data: components['schemas']['payments-naver-validate149892381'];
    error: any;
  };

  /**
   * 배송지 수정하기
   * @description ## 부가설명 및 특이사항
  선택한 배송지 주소를 수정하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[PUT]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%88%98%EC%A0%95.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[PUT]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%88%98%EC%A0%95.png)
   */
  '/profile/shipping-addresses/{addressNo}': {
    params: {
      path: {
        /**
         * @description 배송지 번호
         * @example 1
         */
        addressNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['profile-shipping-addresses-addressNo-635015904'];
    data: components['schemas']['profile-shipping-addresses-2110780552'];
    error: any;
  };

  /**
   * 상품 주문 구매 확정하기
   * @description ## 부가설명 및 특이사항
  배송중, 배송완료 상태의 상태주문을 구매확정 처리하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_confirm%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EA%B5%AC%EB%A7%A4%ED%99%95%EC%A0%95.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_confirm%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EA%B5%AC%EB%A7%A4%ED%99%95%EC%A0%95.png)
   */
  '/profile/order-options/{orderOptionNo}/confirm': {
    params: {
      path: {
        /**
         * @description 주문옵션번호
         * @example 123
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 상품 주문 배송완료 처리하기
   * @description ## 부가설명 및 특이사항
  배송중 상태의 상품주문을 배송완료 처리하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_delivery-done%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EB%B0%B0%EC%86%A1%EC%99%84%EB%A3%8C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_order-options_delivery-done%20%EC%83%81%ED%92%88%20%EC%A3%BC%EB%AC%B8%20%EB%B0%B0%EC%86%A1%EC%99%84%EB%A3%8C.png)
   */
  '/profile/order-options/{orderOptionNo}/delivery-done': {
    params: {
      path: {
        /**
         * @description 주문옵션번호
         * @example 123
         */
        orderOptionNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 주문단위 배송정보 수정하기
   * @description ## 부가설명 및 특이사항
  주문번호에 속한 배송정보를 일괄 수정하는 API 입니다.
  
  지역별 배송비가 변경되는 주소로는 배송정보를 변경할 수 없습니다.
  지역별 배송비는 receiverJibunAddress로 입력되는 지번주소를 기준으로 판단합니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/myorder/[PUT]%20profile_orders_deliveries%20%EC%A3%BC%EB%AC%B8%EB%8B%A8%EC%9C%84%20%EB%B0%B0%EC%86%A1%EC%A0%95%EB%B3%B4%20%EC%88%98%EC%A0%95.png)
   */
  '/profile/orders/{orderNo}/deliveries': {
    params: {
      path: {
        /**
         * @description 주문옵션번호
         * @example 2010121010
         */
        orderNo: string;
      };
      query?: {
        /**
         * @description 주소지 추가 여부
         * @example true
         */
        add: boolean;
      };
    };
    body?: components['schemas']['guest-orders-orderNo-deliveries1990893381'];
    data: any;
    error: any;
  };

  /**
   * 기본 배송지 수정하기
   * @description ## 부가설명 및 특이사항
  선택한 배송지를 기본배송지로 지정하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[PUT]%20profile_shipping-addresses_default%20%EA%B8%B0%EB%B3%B8%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%88%98%EC%A0%95.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[PUT]%20profile_shipping-addresses_default%20%EA%B8%B0%EB%B3%B8%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%88%98%EC%A0%95.png)
   */
  '/profile/shipping-addresses/{addressNo}/default': {
    params: {
      path: {
        /**
         * @description 배송지 번호
         * @example 1
         */
        addressNo: string;
      };
      query?: never;
    };
    body?: never;
    data: components['schemas']['profile-shipping-addresses-2110780552'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니 수정하기
   * @description ## 부가설명 및 특이사항
  로그인된 유저의 장바구니의 상품 중 구매 수량과 사용자 입력형 옵션을 수정하는 API 입니다.
  
  옵션 종류는 변경할 수 없습니다.
  
  옵션변경은 변경할 옵션을 삭제한 후 신규등록하는 방법으로 수정합니다.
   */
  '/recurring-payments/cart': {
    params?: never;
    body?: components['schemas']['recurring-payments-cart-890037452'];
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 배송주기 변경하기
   * @description ## 부가설명 및 특이사항
  정기결제 배송일을 변경하는 API 입니다.
   */
  '/recurring-payments/delivery-cycle': {
    params?: never;
    body?: components['schemas']['recurring-payments-delivery-cycle1814328293'];
    data: components['schemas']['recurring-payments-delivery-cycle-1813425842'];
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 해지하기
   * @description ## 부가설명 및 특이사항
  정기결제를 해지 처리하는 API 입니다.
  
  성공적으로 해지 완료 시 204(noContent) 응답을 반환합니다.
   */
  '/recurring-payments/close/{recurring-payment-no}': {
    params: {
      path: {
        'recurring-payment-no': string;
      };
      query?: never;
    };
    body?: components['schemas']['recurring-payments-close-recurring-payment-no1740267411'];
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 나중 입력 배송지 정보 수정하기
   * 
   * @description ## 부가설명 및 특이사항
  나중에 입력된 배송지 정보를 수정하는 API 입니다.
   */
  '/shippings/{encryptedShippingNo}/later-input': {
    params: {
      path: {
        /**
         * @description 암호화된 배송 번호
         * @example UFE3Ylo2aUlkSWVuZHVGQjYyS2pZZz09
         */
        encryptedShippingNo: string;
      };
      query?: never;
    };
    body?: components['schemas']['shippings-encryptedShippingNo-later-input350289840'];
    data: any;
    error: any;
  };

  /**
   * 위시리스트 수정하기
   * @description ## 부가설명 및 특이사항
  위시리스트를 수정하는 API 입니다.
   */
  '/wish': {
    params?: never;
    body?: components['schemas']['wish929069921'];
    data: any;
    error: any;
  };
}

export interface Patch {}

export interface Delete {
  /**
   * 장바구니 삭제하기
   * @description ## 부가설명 및 특이사항
  장바구니 목록에서 장바구니를 삭제하는 API 입니다.
  
  cartNo를 List형으로 전달해야 합니다.
   */
  '/cart': {
    params: {
      path?: never;
      query: {
        /**
         * @description 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
      };
    };
    body?: never;
    data: components['schemas']['cart-1843750990'];
    error: any;
  };

  /**
   * 등록된 결제수단 삭제하기
   * @description ## 부가설명 및 특이사항
  등록된 결제수단을 삭제합니다.
   */
  '/my-pay/payment-infos': {
    params: {
      path?: never;
      query: {
        /**
         * @description 이니시스에서 발행한 SEED wpaytoken
         * @example LL3E994QcmzSFH0JCiZOFw==
         */
        payToken: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 회원서비스 해제하기
   * @description ## 부가설명 및 특이사항
  회원서비스를 해제합니다.
   */
  '/my-pay/user': {
    params?: never;
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 배송지 삭제하기
   * @description ## 부가설명 및 특이사항
  등록된 배송지를 삭제하는 API 입니다.
  
  ## 화면예시
  [![](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[DELETE]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%82%AD%EC%A0%9C.png?autox150)](http://image.toast.com/aaaaahb/api-description/order/shipping-address/[DELETE]%20profile_shipping-addresses%20%EB%B0%B0%EC%86%A1%EC%A7%80%20%EC%82%AD%EC%A0%9C.png)
   */
  '/profile/shipping-addresses/{addressNo}': {
    params: {
      path: {
        /**
         * @description 배송지 번호
         * @example 1
         */
        addressNo: string;
      };
      query?: never;
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 카드 삭제하기
   * @description ## 부가설명 및 특이사항
  정기결제 카드를 삭제하는 API 입니다.
   */
  '/recurring-payments/card': {
    params?: never;
    body?: never;
    data: any;
    error: any;
  };

  /**
   * [샵바이프리미엄 전용] 정기결제 장바구니 삭제하기
   * @description ## 부가설명 및 특이사항
  장바구니 목록에서 장바구니를 삭제하는 API 입니다.
  
  cartNo를 List형으로 전달해야 합니다.
   */
  '/recurring-payments/cart': {
    params: {
      path?: never;
      query: {
        /**
         * @description 장바구니 번호
         * @example 1,2,3
         */
        cartNo: string;
      };
    };
    body?: never;
    data: components['schemas']['cart-1843750990'];
    error: any;
  };

  /**
   * 위시리스트 삭제하기
   * @description ## 부가설명 및 특이사항
  위시리스트를 삭제하는 API 입니다.
   */
  '/wish': {
    params: {
      path?: never;
      query: {
        /**
         * @description 위 번호
         * @example 1,2,3
         */
        wishNos: number;
      };
    };
    body?: never;
    data: components['schemas']['wish-count655543630'];
    error: any;
  };
}

export interface Options {}

export interface Trace {}
