/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '@/shopby-api/openapi-types/shopby-api-types/auth-shop-public.d.ts';

export interface Get {
  /**
   * 인증번호 확인하기
   * @description ## 부가설명 및 특이사항
  연락처로 전달받은 인증번호를 확인하는 API 입니다
   */
  '/authentications': {
    params: {
      path?: never;
      query: {
        /**
         * @description 인증 타입 (SMS: SMS 인증, EMAIL: 이메일 인증)
         * @example EMAIL
         */
        type: string;
        /**
         * @description 사용 용도 (FIND_ID: 아이디 찾기, FIND_PASSWORD: 비밀번호 찾기, RELEASE_DORMANT: 휴면 해제, JOIN: 가입인증, CHANGE_ID: 아이디 변경, CHANGE_EMAIL: 이메일 변경, CHANGE_MOBILE_NO: 휴대폰번호 변경)
         * @example FIND_ID
         */
        usage: string;
        /**
         * @description 인증 번호
         * @example 123456
         */
        certificatedNumber: string;
        /** @description 회원 번호 */
        memberNo: number;
        /** @description 이메일 주소 | 휴대폰 번호 */
        notiAccount: string;
      };
    };
    body?: never;
    data: any;
    error: components['schemas']['authentications1547003243'];
  };

  /**
   * 이메일로 전달받은 인증코드 확인하기
   * @description ## 부가설명 및 특이사항
  이메일로 전달받은 인증번호를 확인하는 API 입니다
   */
  '/authentications/email': {
    params: {
      path?: never;
      query: {
        /**
         * @description 사용 용도 (FIND_ID: 아이디 찾기, FIND_PASSWORD: 비밀번호 찾기, RELEASE_DORMANT: 휴면 해제, JOIN_URI: 가입인증)
         * @example FIND_ID
         */
        usage: string;
        /**
         * @description 이메일 주소
         * @example gildong@nhn.com
         */
        email: string;
        /**
         * @description 인증 번호
         * @example 123456
         */
        certificatedNumber: string;
      };
    };
    body?: never;
    data: components['schemas']['authentications-email237551932'];
    error: any;
  };

  /**
   * SMS로 전달받은 인증코드 확인하기
   * @description ## 부가설명 및 특이사항
  휴대전화번호로 전달받은 인증번호를 확인하는 API 입니다
   */
  '/authentications/sms': {
    params: {
      path?: never;
      query: {
        /**
         * @description 사용 용도 (FIND_ID: 아이디 찾기, FIND_PASSWORD: 비밀번호 찾기, RELEASE_DORMANT: 휴면 해제, JOIN: 가입인증, CHANGE_MOBILE_NO: 휴대폰번호 변경)
         * @example CHANGE_MOBILE_NO
         */
        usage: string;
        /**
         * @description 휴대전화 번호
         * @example 01012341234
         */
        mobileNo: string;
        /**
         * @description 인증 번호
         * @example 123456
         */
        key: string;
      };
    };
    body?: never;
    data: components['schemas']['authentications-email237551932'];
    error: any;
  };

  /**
   * 캡챠 이미지 생성하기
   * @description ## 부가설명 및 특이사항
  이미지 캡챠 생성을 위한 API 입니다.
  
  요청한 캡챠 이미지는 KEY 기준으로 10분 동안 유지 됩니다.
   */
  '/captcha/image': {
    params: {
      path?: never;
      query: {
        /** @description 캡챠 구분키 */
        key: string;
      };
    };
    body?: never;
    data: components['schemas']['captcha-image258801235'];
    error: any;
  };

  /**
   * KCP 본인인증 요청하기
   * @description ## 부가설명 및 특이사항
  KCP 본인인증을 위한 form을 생성하기 위한 API 입니다
  
  자세한 내용은 [KCP 본인인증 가이드](https://shopby.works/guide/skin/dev-cover/verify?lv=11) 및 [테스트 페이지](https://gitlab-themes.shopby.co.kr/NHN-COMMERCE/kcp-front-test)를 참고 부탁드립니다.
   */
  '/kcp/id-verification/form': {
    params: {
      path?: never;
      query: {
        /**
         * @description 본인인증 완료 후 호출할 클라이언트 페이지
         * @example http://localhost:8080/path/to/comeback
         */
        returnUrl: string;
        /**
         * @description 내국인 여부 (true : 내국인, false : 외국인 , null : 내국인 전용 QR 신청 본인인증)
         * @example false
         */
        domestic: string;
      };
    };
    body?: never;
    data: components['schemas']['kcp-id-verification-form1116014589'];
    error: any;
  };

  /**
   * KCP 본인인증 결과 조회하기
   * @description ## 부가설명 및 특이사항
  KCP 본인인증 결과를 확인하는 API 입니다
   */
  '/kcp/id-verification/response': {
    params: {
      path?: never;
      query: {
        /**
         * @description 본인인증 키
         * @example 20210101000000
         */
        key: string;
      };
    };
    body?: never;
    data: components['schemas']['kcp-id-verification-response-1191495885'];
    error: any;
  };

  /**
   * KCP 본인인증 결과 복호화 요청
   * 
   * @description ## 부가설명 및 특이사항
  KCP 본인인증 결과 복호화 요청하기 위한 API 입니다.
   */
  '/kcp-certification/member/result-decrypt': {
    params: {
      path?: never;
      query: {
        /**
         * @description key
         * @example key
         */
        key: string;
      };
    };
    body?: never;
    data: components['schemas']['kcp-certification-member-result-decrypt967119927'];
    error: any;
  };

  /**
   * OAuth 로그인 페이지 열기
   * @description ## 부가설명 및 특이사항
  간편 로그인을 위한 로그인 URL을 조회한 후 해당 주소로 리다이렉트하는 API 입니다.
  
  * /oauth/begin -> 간편 로그인 페이지 -> /oauth/callback -> nextUrl 순으로 리다이렉트됩니다.
  
  * nextUrl을 이용하여 로그인 성공 후 돌아갈 callback URL을 설정할 수 있습니다.
  
  * 쇼핑몰 운영자가 기본 도메인을 등록한 경우 /로 시작하는 상대 주소를 사용할 수 있고, 그 외의 경우에는 올바른 HTTP URL을 전달해야 합니다.
   */
  '/oauth/begin': {
    params: {
      path?: never;
      query: {
        /** @description API 사용을 위한 클라이언트 아이디 */
        clientId: string;
        /** @description 간편 로그인 제공사(ncp_naver, ncp_kakao, ncp_kakao-sync, ncp_line, ncp_facebook, ncp_payco) */
        provider: string;
        /**
         * @description 로그인 성공 이후 로드할 페이지 주소 (callback URL)
         * @example /
         */
        nextUrl: string;
        /**
         * @description 클라이언트 플랫폼(PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform: string;
        /** @description CSRF 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰 */
        state: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * OAuth callback 처리하기(AccessToken 발급하기)
   * @description ## 부가설명 및 특이사항
  OpenId 회원의 AccessToken 발급하기 위한 API 입니다.
  
  * /oauth/begin -> 간편 로그인 페이지 -> /oauth/callback -> nextUrl 순으로 리다이렉트됩니다.
  
  * 간편 로그인 성공후 받은 인증 코드를 통해 회원 토큰을 발급하고, 리다이렉트될 nexUrl의 쿼리에 토큰 정보를 담아 전달합니다.
  
  * ex) https://test.shopby.co.kr?accessToken=test-access-token&expireIn=3599&daysFromLastPasswordChange=17
  
  * 쿼리 파라미터는 /oauth/begin에서 정의한 값이 간편 로그인 페이지를 통해 넘어와야하며, 임의로 변경해서는 안됩니다.
   */
  '/oauth/callback': {
    params: {
      path?: never;
      query: {
        /** @description 클라이언트 아이디 */
        clientId: string;
        /** @description OAuth2 프로바이더 */
        provider: string;
        /** @description 인증 코드 */
        code: string;
        /** @description CSRF 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰 */
        state: string;
        /** @description 로그인 성공 이후 로드할 페이지 주소 (callback URL) */
        nextUrl: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * OpenId 로그인 url 조회하기
   * @description ## 부가설명 및 특이사항
  OpenId 로그인 url 조회하기 위한 API 입니다.
  
  ## 화면예시
  [![login URL](http://image.toast.com/aaaaahb/api-description/member/authentication/post_oauth_login-url.png)](http://image.toast.com/aaaaahb/api-description/member/authentication/post_oauth_login-url.png)
   */
  '/oauth/login-url': {
    params: {
      path?: never;
      query: {
        /**
         * @description 간편 로그인 제공사(ncp_naver, ncp_kakao, ncp_kakao-sync, ncp_line, ncp_facebook, ncp_payco)
         * @example ncp_naver
         */
        provider: string;
        /** @description redirect URL */
        redirectUri: string;
        /** @description CSRF 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰 */
        state: string;
      };
    };
    body?: never;
    data: components['schemas']['oauth-login-url-1249944640'];
    error: any;
  };

  /**
   * OpenId AccessToken 발급하기
   * @description ## 부가설명 및 특이사항
  OpenId 회원의 AccessToken 발급하기 위한 get 방식의 API 입니다.
  
  보안을 위해 post 방식의 API 사용을 권장드립니다.
  
  * 자동 로그인을 위해 **keepLogin**을 **true**로 요청하면 유효 기간이 90일인 토큰이 생성됩니다.
  * 유효 기간이 길기 때문에 토큰 탈취시 보안에 취약할 수 있습니다.
  
  외부 IdP(Identity Provider, 아이디 제공자)를 이용하는 회원이 로그인할 때 사용합니다.
  
  지원하는 IdP 크게 (1) 간편 로그인을 지원하는 IdP, (2) 자체 연동형 IdP(자체적으로 회원 서비스를 지원하는 경우 사용)로 나뉩니다.
  
  ## (1) 간편 로그인
  각 개발자센터에서 쇼핑몰에 맞는 올바른 설정을 먼저 진행해야합니다.
  
  [간편 로그인 가이드](https://shopby.works/guide/skin/dev-cover/easy-login?lv=11)
  
  ## 간편 로그인 유형별 필수값
  
  | provider | code  | redirectUri | state |
  | :------: | :---: | :---: | :---: |
  | ncp_naver  |   O   |   X   |   △   |
  | ncp_kakao  |   O   |   O   |   X   |
  | ncp_kakao-sync  |   O   |   X   |   △   |
  | ncp_line   |   O   |   O   |   O   |
  | ncp_facebook |   O   |   O   |   X   |
  | ncp_payco  |   O   |   X   |   △   |
  
  ## 참고
  
  - [네이버 개발자센터](https://developers.naver.com/main)
  - [카카오 개발자센터](https://developers.kakao.com/)
  - [라인 개발자센터](https://developers.line.biz/en/)
  - [페이스북 개발자센터](https://developers.facebook.com/)
  - [페이코 개발자센터](https://developers.payco.com/)
  
  ## (2) 자체 회원 연동 (프리미엄 전용)
  자세한 사항은 아래 가이드와 서비스 담당자에게 문의해주시길 바랍니다.
  
  [자체회원 연동 가이드](https://shopby.works/support/recommendedContents/23046)
  
  ## 자체 회원 연동 필수값
  
  | provider | openAccessToken |
  | :------: | :---: |
  | ncpstore |  O   |
   */
  '/oauth/openid': {
    params: {
      path?: never;
      query: {
        /** @description 간편 로그인 제공사(ncp_naver, ncp_kakao, ncp_kakao-sync, ncp_line, ncp_facebook, ncp_payco) */
        provider: string;
        /** @description IdP(Identity Provider, 아이디 제공자)로부터 받은 인증코드(authorization code) - 간편 로그인 사용시 필수 */
        code: string;
        /** @description 개발자센터에 등록된 redirect URI */
        redirectUri: string;
        /** @description CSRF 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰 */
        state: string;
        /** @description 자동로그인 여부(**true**로 요청하면 유효 기간이 90일인 토큰이 생성) */
        keepLogin: string;
        /** @description 클라이언트 플랫폼(PC, MOBILE_WEB, AOS, IOS) */
        platformType: string;
      };
    };
    body?: never;
    data: components['schemas']['oauth-openid-link-1411956587'];
    error: any;
  };

  /**
   * SNS 연동하기
   * @description ## 부가설명 및 특이사항
  일반 회원에 SNS 연동을 하는 API 입니다.
  
  외부 IdP(Identity Provider, 아이디 제공자)를 이용하는 회원이 로그인할 때 사용합니다.
  
  ## 간편 로그인
  각 개발자센터에서 쇼핑몰에 맞는 올바른 설정을 먼저 진행해야합니다.
  
  [간편 로그인 가이드](https://shopby.works/guide/skin/dev-cover/easy-login?lv=11)
  
  ## 간편 로그인 유형별 필수값
  
  | provider | code  | redirectUri | state |
  | :------: | :---: | :---: | :---: |
  | ncp_naver  |   O   |   X   |   △   |
  | ncp_kakao  |   O   |   O   |   X   |
  | ncp_kakao-sync  |   O   |   X   |   △   |
  | ncp_line   |   O   |   O   |   O   |
  | ncp_facebook |   O   |   O   |   X   |
  | ncp_payco  |   O   |   X   |   △   |
  
  ## 참고
  
  - [네이버 개발자센터](https://developers.naver.com/main)
  - [카카오 개발자센터](https://developers.kakao.com/)
  - [라인 개발자센터](https://developers.line.biz/en/)
  - [페이스북 개발자센터](https://developers.facebook.com/)
  - [페이코 개발자센터](https://developers.payco.com/)
   */
  '/oauth/openid/link': {
    params: {
      path?: never;
      query: {
        /** @description 간편 로그인 제공사(ncp_naver, ncp_kakao, ncp_kakao-sync, ncp_line, ncp_facebook, ncp_payco) */
        provider: string;
        /** @description IdP(Identity Provider, 아이디 제공자)로부터 받은 인증코드(authorization code) - 간편 로그인 사용시 필수 */
        code: string;
        /** @description IdP(Identity Provider, 아이디 제공자) 엑세스 토큰 - 연동형 IdP(Identity Provider, 아이디 제공자) 사용시 필수 */
        openAccessToken: string;
        /** @description 개발자센터에 등록된 redirect URI */
        redirectUri: string;
        /** @description CSRF 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰 */
        state: string;
        /** @description 자동로그인 여부(**true**로 요청하면 유효 기간이 90일인 토큰이 생성) */
        keepLogin: string;
        /** @description 클라이언트 플랫폼(PC, MOBILE_WEB, AOS, IOS) */
        platformType: string;
      };
    };
    body?: never;
    data: components['schemas']['oauth-openid-link-1411956587'];
    error: any;
  };

  /**
   * SNS 연동 내역 조회
   * @description ## 부가설명 및 특이사항
  연동된 SNS를 조회하는 API 입니다.
   */
  '/oauth/openid/list': {
    params?: never;
    body?: never;
    data: components['schemas']['oauth-openid-list-1563013012'];
    error: any;
  };

  /**
   * AccessToken 조회하기
   * @description ## 부가설명 및 특이사항
  OpenId 서비스 제공자의 AccessToken 조회하기 위한 API 입니다.
  
  응답의 프로바이더 토큰 정보는 현재 로그인한 회원이 간편로그인을 통한 인증을 할 때 사용한 토큰 정보입니다.
  
  따라서 아이디와 비밀번호를 사용해 로그인한 사용자는 응답이 모두 null 입니다.
  
  또한 서버는 프로바이더 토큰을 로그인 외에는 사용하지 않기 때문에 프로바이더 토큰 갱신 등은 사용자가 직접 해야 합니다.
   */
  '/openid/token': {
    params?: never;
    body?: never;
    data: components['schemas']['openid-token-1732903447'];
    error: any;
  };
}

export interface Head {}

export interface Post {
  /**
   * 인증번호 발송하기
   * @description ## 부가설명
  회원의 연락처 또는 입력한 연락처로 인증번호를 발송하는 API 입니다
  
  1. 회원번호로 보내는 경우, 해당 회원번호를 가진 회원의 연락처로 인증번호를 발송합니다.
  2. 연락처(notiAccount)와 회원이름을 보내는 경우, 해당 정보와 일치하는 회원이 있는 경우, 입력한 연락처로 인증번호를 발송합니다.
  
  ## 주의사항
  만약, 회원번호 + 연락처 & 이름 을 보내는 경우, 회원번호를 우선하여 인증번호를 발송합니다.
  따라서, 회원번호 / 연락처 & 이름 2가지 경우 중 하나만 사용해야합니다.
   */
  '/authentications': {
    params?: never;
    body?: components['schemas']['authentications2123066576'];
    data: components['schemas']['authentications1664299215'];
    error: any;
  };

  /**
   * 비즈몰 가입 권한 확인하기
   * @description ## 부가설명 및 특이사항
  비즈몰 사번을 확인하여 가입 가능 여부를 확인하는 API 입니다
   */
  '/authentications/bizmall': {
    params?: never;
    body?: components['schemas']['authentications-bizmall1331022487'];
    data: components['schemas']['authentications-bizmall-537100746'];
    error: any;
  };

  /**
   * 이메일로 인증번호 발송하기
   * @description ## 부가설명 및 특이사항
  이메일로 인증번호를 발송하는 API 입니다
   */
  '/authentications/email': {
    params?: never;
    body?: components['schemas']['authentications-email131382975'];
    data: components['schemas']['authentications1664299215'];
    error: any;
  };

  /**
   * 휴대폰 점유 인증을 위해 인증코드(6자리) SMS 발송하기
   * @description ## 부가설명 및 특이사항
  휴대전화번호로 인증번호를 발송하는 API 입니다
   */
  '/authentications/sms': {
    params?: never;
    body?: components['schemas']['authentications-sms-1002112365'];
    data: components['schemas']['authentications1664299215'];
    error: any;
  };

  /**
   * 캡챠 인증코드 확인하기
   * @description ## 부가설명 및 특이사항
  캡챠 인증코드 확인하기 위한 API 입니다.
   */
  '/captcha/verify': {
    params: {
      path?: never;
      query: {
        /** @description 캡챠 인증코드 */
        code: string;
        /** @description 캡챠 구분키 */
        key: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * 회원 성인인증하기
   * @description ## 부가설명 및 특이사항
  회원 성인인증 여부를 갱신하기 위한 API 입니다.
  
  * KCP 본인인증 서비스를 이용해 회원의 성인인증 여부를 갱신합니다.
  * 한 번 성인인증을 완료한 회원은 인증을 완료한 시점부터 1년동안 인증 기록이 유지됩니다.
  * 기간 내에 다시 인증에 성공할 경우 성인인증 일시와 만료일은 갱신됩니다.
   */
  '/kcp/age-verification': {
    params: {
      path?: never;
      query: {
        /**
         * @description 본인인증 키
         * @example 20210101000000
         */
        key: string;
      };
    };
    body?: never;
    data: components['schemas']['kcp-age-verification-1064179165'];
    error: any;
  };

  /**
   * KCP 본인인증 요청
   * 
   * @description ## 부가설명 및 특이사항
  KCP 본인인증 요청을 위한 API 입니다.
   */
  '/kcp-certification/member': {
    params?: never;
    body?: components['schemas']['kcp-certification-member1121708161'];
    data: components['schemas']['kcp-certification-member2087213742'];
    error: any;
  };

  /**
   * OpenId AccessToken 발급하기 - POST 방식
   * @description ## 부가설명 및 특이사항
  OpenId 회원의 AccessToken 발급하기 위한 post 방식의 API 입니다.
  
  * 자동 로그인을 위해 **keepLogin**을 **true**로 요청하면 유효 기간이 90일인 토큰이 생성됩니다.
  * 유효 기간이 길기 때문에 토큰 탈취시 보안에 취약할 수 있습니다.
  
  외부 IdP(Identity Provider, 아이디 제공자)를 이용하는 회원이 로그인할 때 사용합니다.
  
  지원하는 IdP 크게 (1) 간편 로그인을 지원하는 IdP, (2) 자체 연동형 IdP(자체적으로 회원 서비스를 지원하는 경우 사용)로 나뉩니다.
  
  ## (1) 간편 로그인
  각 개발자센터에서 쇼핑몰에 맞는 올바른 설정을 먼저 진행해야합니다.
  
  [간편 로그인 가이드](https://shopby.works/guide/skin/dev-cover/easy-login?lv=11)
  
  ## 간편 로그인 유형별 필수값
  
  | provider | code  | redirectUri | state |
  | :------: | :---: | :---: | :---: |
  | ncp_naver  |   O   |   X   |   △   |
  | ncp_kakao  |   O   |   O   |   X   |
  | ncp_kakao-sync  |   O   |   X   |   △   |
  | ncp_line   |   O   |   O   |   O   |
  | ncp_facebook |   O   |   O   |   X   |
  | ncp_payco  |   O   |   X   |   △   |
  
  ## 참고
  
  - [네이버 개발자센터](https://developers.naver.com/main)
  - [카카오 개발자센터](https://developers.kakao.com/)
  - [라인 개발자센터](https://developers.line.biz/en/)
  - [페이스북 개발자센터](https://developers.facebook.com/)
  - [페이코 개발자센터](https://developers.payco.com/)
  
  ## (2) 자체 회원 연동 (프리미엄 전용)
  자세한 사항은 아래 가이드와 서비스 담당자에게 문의해주시길 바랍니다.
  
  [자체회원 연동 가이드](https://shopby.works/support/recommendedContents/23046)
  
  ## 자체 회원 연동 필수값
  
  | provider | openAccessToken |
  | :------: | :---: |
  | ncpstore |  O   |
   */
  '/oauth/openid': {
    params?: never;
    body?: components['schemas']['oauth-openid495200803'];
    data: components['schemas']['oauth-openid-link-1411956587'];
    error: any;
  };

  /**
   * AccessToken 발급하기
   * @description ## 부가설명 및 특이사항
  * 샵바이 회원의 AccessToken 발급하기 위한 API 입니다.
  
  * 회원 엑세스 토큰의 기본 유효 기간은 12시간이며,
  
  * 자동 로그인을 위해 **keepLogin**을 **true**로 요청하면 유효 기간이 90일인 토큰이 생성됩니다.
  
  * 유효 기간이 길기 때문에 토큰 탈취시 보안에 취약할 수 있습니다.
  
  ## ID/PW 기반 외부 회원 연동
  
  * body 값 중 provider 를 shopbystore 로 보내야합니다.
  
  * 자세한 사항은 아래 가이드와 서비스 담당자에게 문의해주시길 바랍니다.
  
  * [자체회원 연동 가이드 중 ID/PW 기반 연동](https://shopby.works/support/recommendedContents/23046)
  
  ## 자체 회원 연동 필수값
  
  | provider |
  | :------: |
  | shopbystore |
  
  ### 캡챠(추후 서비스 제공 예정)
  * 10회 이상 로그인 실패 등 사유로 로그인이 실패할 경우, 캡챠 기능에 사용할 수 있는 key 값이 에러와 함께 리턴됩니다.
  
  * 해당 key 값을 이용하여, 차후 캡챠 기능에 사용할 수 있습니다.
  
  *휴면계정일 경우, dormantMemberResponse에 실린 정보를 이용하여, 휴면 해제에 활용할 수 있습니다.
   */
  '/oauth/token': {
    params?: never;
    body?: components['schemas']['oauth-token1261496601'];
    data: components['schemas']['oauth-token-1916652149'];
    error: components['schemas']['oauth-token-1364515864'];
  };
}

export interface Put {}

export interface Patch {}

export interface Delete {
  /**
   * SNS 연동 해제하기
   * @description ## 부가설명 및 특이사항
  SNS연동을 해제하는 API 입니다.
  
  ## 참고
  
  - [네이버 개발자센터](https://developers.naver.com/main)
  - [카카오 개발자센터](https://developers.kakao.com/)
  - [라인 개발자센터](https://developers.line.biz/en/)
  - [페이스북 개발자센터](https://developers.facebook.com/)
  - [페이코 개발자센터](https://developers.payco.com/)
   */
  '/oauth/openid': {
    params: {
      path?: never;
      query: {
        /** @description 간편 로그인 제공사(ncp_naver, ncp_kakao, ncp_kakao-sync, ncp_line, ncp_facebook, ncp_payco) */
        provider: string;
      };
    };
    body?: never;
    data: any;
    error: any;
  };

  /**
   * AccessToken 반환하기
   * @description ## 부가설명 및 특이사항
  AccessToken 만료 처리(ncp, payco 회원 동일)를 하기 위한 API 입니다.
  
  회원의 엑세스 토큰을 삭제하여 로그아웃합니다.
   */
  '/oauth/token': {
    params?: never;
    body?: never;
    data: any;
    error: any;
  };
}

export interface Options {}

export interface Trace {}
