/**
 * This file was generated by openapi-typescript-flatten
 */

import type { components } from '@/shopby-api/openapi-types/shopby-api-types/workspace-shop-public.d.ts';

export interface Get {
  /**
   * 외부스크립트 조회하기
   * @description ## 부가설명 및 특이사항
  외부스크립트 조회
  
  몰에서 사용중인 외부 스크립트 리스트를 불러옵니다.
   */
  '/external-scripts': {
    params?: never;
    body?: never;
    data: components['schemas']['external-scripts176357485'];
    error: any;
  };
}

export interface Head {}

export interface Post {}

export interface Put {}

export interface Patch {}

export interface Delete {}

export interface Options {}

export interface Trace {}
