/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/malls': {
    /**
     * 몰 정보 조회하기
     * @description ## 부가설명 및 특이사항
     * 몰 정보를 조회하는 API입니다.
     *
     * 몰 진입 시 전체 카테고리 조회 후 응답값을 localStorage(web), SharedPreference(android), NSUserDefaults(ios)와 같은 로컬 저장소에 두고 재사용하는 방식을 권장합니다.
     *
     * expire time은 익일 0시로 설정을 권장합니다.
     *
     * 카테고리는 변경 가능하므로 상품상세 API의 카테고리 번호가 로컬 저장소에는 없을 수 있습니다.
     *
     * 그런 경우에는 카테고리 조회 API를 이용하여 로컬 저장소를 갱신해 주십시오.
     *
     *
     * ## CDN으로 대체하면 더 좋은 성능을 낼 수 있습니다.
     * 해당 API는 상점 정보를 DB를 통해 조회하며, DB에서 데이터를 가져올 때 트래픽이 발생하는 경우 병목 현상으로 인해 API응답이 지연이 되는 경우가 있습니다.
     *
     * 하지만 CDN을 활용해 상점 정보를 가져오게 되면 트래픽 대부분을 CDN캐시 서버에서 처리하기 때문에 트래픽 폭주로 인한 서비스 장애를 사전에 방지할 수 있습니다.
     *
     * 또한 CDN 리소스를  최종 클라이언트에게 전달할 때, 일반 인터넷망이 아닌 전용선을 사용하여 빠르고 안전한 성능을 기대할 수 있습니다.
     *
     * CDN경로에는 해당 API의 응답값과 동일한 상점 정보가 포함되어있고 해당 정보가 변경되면 5초이내로 CDN파일을 갱신하고 있습니다.
     *
     * 기존과 같이 응답값을 localStorage(web), SharedPreference(android), NSUserDefaults(ios)와 같은 로컬저장소에 두고 재사용하는 방식을 권장합니다.
     *
     * 자세한 개발방법은 아래 링크를 참조하세요.
     *
     * [https://shopby.works/guide/skin/dev-cover/call-api#call-info](https://shopby.works/guide/skin/dev-cover/call-api#call-info)
     */
    get: operations['get-malls'];
  };
  '/malls/internationalization': {
    /**
     * 현재 몰의 다국어, 환율 설정 조회
     * @description ## 부가설명 및 특이사항
     * 현재 몰의 다국어, 환율 설정 조회을 조회하는 API 입니다.
     */
    get: operations['get-malls-i18n'];
  };
  '/malls/partners': {
    /**
     * [샵바이프리미엄 전용] 몰과 계약한 파트너 목록 조회하기
     * @description ## 부가설명 및 특이사항
     * 몰과 계약한 파트너 목록을 조회하는 API입니다.
     */
    get: operations['get-malls-partners'];
  };
  '/malls/ssl': {
    /**
     * 현재 도메인의 보안서버정보 조회하기
     * @description ## 부가설명 및 특이사항
     * 현재 도메인의 보안서버정보를 조회하는 API입니다.
     */
    get: operations['get-malls-ssl'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    'malls-partners-200843305': {
      /**
       * @description 파트너 번호
       * @example 0
       */
      partnerNo: number;
      /**
       * @description 대표자명 (nullable)
       * @example string
       */
      ownerName?: string;
      /**
       * @description FAX 번호 (nullable)
       * @example string
       */
      faxNo?: string;
      /**
       * @description 판매자명 (nullable)
       * @example string
       */
      partnerName?: string;
      /**
       * @description 사업장 주소
       * @example string
       */
      officeAddressLabel: string;
      /**
       * @description 상호명 (nullable)
       * @example string
       */
      companyName?: string;
      /**
       * @description 사업자 번호 (nullable)
       * @example string
       */
      businessRegistrationNo?: string;
      /**
       * @description 통신판매신고번호 (nullable)
       * @example string
       */
      onlineMarketingBusinessDeclarationNo?: string;
      /**
       * @description 대표 이메일 (nullable)
       * @example string
       */
      email?: string;
      /**
       * @description 대표번호 (nullable)
       * @example string
       */
      phoneNo?: string;
    }[];
    'malls-ssl-953646756': {
      /**
       * @description 디바이스타입
       * @example PC
       */
      deviceType: string;
      /**
       * @description 도메인
       * @example aaa.co.kr
       */
      domain: string;
      /**
       * @description 몰번호
       * @example 1
       */
      mallNo: number;
      /**
       * @description 보안서버 인증서 씰 스크립트 (nullable)
       * @example trustSeal-script
       */
      trustSeal?: string;
    }[];
    'malls-internationalization-996890286': {
      /**
       * @description 다국어 설정
       * @example [KO]
       */
      languages: (Record<string, never> | boolean | string | number)[];
      /** @description 통화 설정^|[CurrencyResponse(exchangeTo=KRW, exchangeRate=1)] */
      currencies: {
        /**
         * @description 통화
         * @example KRW
         */
        exchangeTo: string;
        /**
         * @description 비율
         * @example 1
         */
        exchangeRate: number;
      }[];
    };
    malls1221953710: {
      /** @description 회원 가입 설정 */
      memberJoinConfig: {
        /**
         * @description 생년월일 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        birthday?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 비밀번호 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        password?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 주소 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        address?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 국적 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        nationality?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 성별 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        sex?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 닉네임 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        nickname?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 회원명 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        memberName?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 휴대전화번호 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        mobileNo?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 전화번호 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        phoneNo?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 이메일 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        email?: 'USED' | 'REQUIRED' | 'NOT_USED';
        /**
         * @description 아이디 필수 여부 (nullable)
         * @example NOT_USED
         * @enum {string}
         */
        memberId?: 'USED' | 'REQUIRED' | 'NOT_USED';
      };
      /** @description 1:1문의 유형 목록 */
      inquiryType: {
        /**
         * @description 1:1문의 유형 설명
         * @example 네이버페이 사용 시 네이버페이를 통해서 접수되는 문의가 연동되는 유형입니다.
         */
        inquiryTypeDescription: string;
        /**
         * @description 1:1문의 유형 번호
         * @example 6276
         */
        inquiryTypeNo: number;
        /**
         * @description 1:1문의 유형 이름
         * @example 네이버페이문의
         */
        inquiryTypeName: string;
      }[];
      /** @description 쇼핑몰 계좌 정보 */
      bankAccountInfo: {
        /**
         * @description 계좌번호 (nullable)
         * @example 123456789
         */
        bankAccount?: string;
        /**
         * @description 예금주명 (nullable)
         * @example 커머스
         */
        bankDepositorName?: string;
        /**
         * @description 은행명 (nullable)
         * @example 우리은행
         */
        bankName?: string;
      };
      /** @description 은행 목록 */
      bankType: {
        /**
         * @description KCP 은행 관리코드
         * @example 04
         * @enum {string}
         */
        kcpCode:
          | '02'
          | '03'
          | '04'
          | '05'
          | '07'
          | '08'
          | '11'
          | '12'
          | '20'
          | '23'
          | '27'
          | '31'
          | '32'
          | '34'
          | '35'
          | '37'
          | '39'
          | '45'
          | '48'
          | '54'
          | '64'
          | '71'
          | '81'
          | '26'
          | '89'
          | '90'
          | '92'
          | '209'
          | '218'
          | '238'
          | '238'
          | '240'
          | '243'
          | '247'
          | '261'
          | '262'
          | '263'
          | '264'
          | '265'
          | '266'
          | '267'
          | '268'
          | '269'
          | '270'
          | '278'
          | '279'
          | '280'
          | '287'
          | '290'
          | '291'
          | '292';
        /**
         * @description 은행 코드
         * @example 004
         * @enum {string}
         */
        code:
          | '000'
          | '002'
          | '003'
          | '004'
          | '005'
          | '007'
          | '008'
          | '011'
          | '012'
          | '020'
          | '023'
          | '027'
          | '031'
          | '032'
          | '034'
          | '035'
          | '037'
          | '039'
          | '045'
          | '048'
          | '050'
          | '054'
          | '055'
          | '064'
          | '071'
          | '081'
          | '088'
          | '089'
          | '090'
          | '092'
          | '209'
          | '218'
          | '230'
          | '238'
          | '240'
          | '243'
          | '247'
          | '261'
          | '262'
          | '263'
          | '264'
          | '265'
          | '266'
          | '267'
          | '268'
          | '269'
          | '270'
          | '278'
          | '279'
          | '280'
          | '287'
          | '290'
          | '291'
          | '292'
          | '901'
          | '905'
          | '909'
          | '910';
        /**
         * @description 은행명
         * @example 국민은행
         * @enum {string}
         */
        name:
          | '미확인은행'
          | '산업은행'
          | '기업은행'
          | '국민은행'
          | '외환은행'
          | '수협'
          | '수출입은행'
          | 'NH농협은행'
          | '지역농축협'
          | '우리은행'
          | 'SC제일은행'
          | '한국씨티은행'
          | '대구은행'
          | '부산은행'
          | '광주은행'
          | '제주은행'
          | '전북은행'
          | '경남은행'
          | '새마을금고'
          | '신협'
          | '상호저축은행'
          | 'HSBC은행'
          | '도이치은행'
          | '산림조합중앙회'
          | '우체국'
          | 'KEB하나은행'
          | '신한은행'
          | '케이뱅크'
          | '카카오뱅크'
          | '토스뱅크'
          | '유안타증권'
          | 'KB증권'
          | '미래에셋증권'
          | '미래에셋대우증권'
          | '삼성증권'
          | '한국투자증권'
          | 'NH투자증권'
          | '교보증권'
          | '하이투자증권'
          | 'HMC투자증권'
          | '키움증권'
          | '이베스트투자증권'
          | 'SK증권'
          | '대신증권'
          | '솔로몬증권'
          | '한화투자증권'
          | '하나금융투자'
          | '신한금융투자'
          | 'DB금융투자'
          | '유진투자증권'
          | '메리츠종합금융증권'
          | '부국증권'
          | '신영증권'
          | '케이프투자증권'
          | '미즈호은행'
          | 'UFJ은행'
          | '미쓰이스미토모은행'
          | '리소나은행';
        /**
         * @description 은행 영문 관리명
         * @example KB
         * @enum {string}
         */
        value:
          | 'ANONYMOUS'
          | 'KDB'
          | 'IBK'
          | 'KB'
          | 'KEB'
          | 'SUHYUP'
          | 'KEXIM'
          | 'NH'
          | 'NHLOCAL'
          | 'WOORI'
          | 'SC'
          | 'CITY'
          | 'DAEGU'
          | 'PUSAN'
          | 'GWANGJU'
          | 'JEJU'
          | 'JEONBUK'
          | 'GYEONGNAM'
          | 'KFCC'
          | 'CU'
          | 'SANGHO'
          | 'HSBC'
          | 'DEUTSCHE'
          | 'NFCF'
          | 'EPOST'
          | 'KEBHANA'
          | 'SHINHAN'
          | 'KBANK'
          | 'KAKAO'
          | 'TOSS'
          | 'YUANTA'
          | 'KBSEC'
          | 'MIRAE'
          | 'MIRAEDAEWOO'
          | 'SAMSUNG'
          | 'HANKOOK'
          | 'NH_INVEST'
          | 'KYOBO'
          | 'HI_INVEST'
          | 'HMC_INVEST'
          | 'KIWOOM'
          | 'EBEST'
          | 'SK'
          | 'DAISHIN'
          | 'SOLOMON_INVEST'
          | 'HANHWA'
          | 'HANA_INVEST'
          | 'SHINHAN_INVEST'
          | 'DONGBU'
          | 'EUGENE_INVEST'
          | 'MERITZ_COMPREHENSIVE'
          | 'BOOKOOK'
          | 'SHINYOUNG'
          | 'CAPE'
          | 'MIZUHO'
          | 'UFJ'
          | 'SMBC'
          | 'RESONA';
      }[];
      /** @description 주문상태 목록 */
      orderStatusType: {
        /**
         * @description 주문상태 명칭
         * @example 입금대기
         * @enum {string}
         */
        label:
          | '입금대기'
          | '결제완료'
          | '상품준비중'
          | '배송준비중'
          | '배송중'
          | '배송완료'
          | '구매확정'
          | '취소완료'
          | '반품완료'
          | '교환완료'
          | '결제대기'
          | '결제포기'
          | '결제실패'
          | '삭제'
          | '교환대기'
          | '환불완료';
        /**
         * @description 주문상태 값
         * @example DEPOSIT_WAIT
         * @enum {string}
         */
        value:
          | 'DEPOSIT_WAIT'
          | 'PAY_DONE'
          | 'PRODUCT_PREPARE'
          | 'DELIVERY_PREPARE'
          | 'DELIVERY_ING'
          | 'DELIVERY_DONE'
          | 'BUY_CONFIRM'
          | 'CANCEL_DONE'
          | 'RETURN_DONE'
          | 'EXCHANGE_DONE'
          | 'PAY_WAIT'
          | 'PAY_CANCEL'
          | 'PAY_FAIL'
          | 'DELETE'
          | 'EXCHANGE_WAIT'
          | 'REFUND_DONE';
      }[];
      /** @description 쇼핑몰 정보 */
      mall: {
        /**
         * @description 커머스 상점번호
         * @example 1234
         */
        godoSno: string;
        /**
         * @description 쇼핑몰명
         * @example 테스트 쇼핑몰
         */
        mallName: string;
        /** @description 인트로 페이지 설정정보 */
        introRedirection: {
          /**
           * @description 인트로 페이지 PC 웹 설정정보
           * @example ONLY_MEMBER
           * @enum {string}
           */
          pc: 'NONE' | 'NO_ACCESS' | 'ONLY_MEMBER' | 'ONLY_ADULT';
          /**
           * @description 인트로 페이지 모바일 웹 설정정보
           * @example ONLY_ADULT
           * @enum {string}
           */
          mobile: 'NONE' | 'NO_ACCESS' | 'ONLY_MEMBER' | 'ONLY_ADULT';
        };
        /**
         * @description 쇼핑몰 서비스 국가
         * @example KR
         */
        countryCode: string;
        /**
         * @description 쇼핑몰 생성일
         * @example yyyy-MM-dd HH:mm:ss
         */
        createdDateTime: string;
        /** @description 등급 */
        grades: {
          /** @description 적립금 자동지급 */
          reserveAutoSupplying: {
            /**
             * @description 적립금 자동지급 적립금액
             * @example 100
             */
            amount: number;
            /**
             * @description 적립금 자동지급 사용여부
             * @example true
             */
            used: boolean;
            /**
             * @description 적립금 자동지급 유형
             * @example MONTHLY
             * @enum {string}
             */
            type: 'NONE' | 'ONCE' | 'MONTHLY';
          };
          /** @description 회원 등급 평가 조건 */
          evaluationCondition: {
            /**
             * @description 최소 구매 금액
             * @example 100000
             */
            minimumPayment: number;
            /**
             * @description 최소 구매 횟수
             * @example 10
             */
            minimumCount: number;
          };
          /** @description 회원 등급에 발급된 쿠폰 */
          coupons: {
            /**
             * @description 쿠폰 발급 유형
             * @example CODE_DESIGNATE_ADMIN_ONLY
             * @enum {string}
             */
            issueType:
              | 'DOWNLOAD'
              | 'CODE_DESIGNATE'
              | 'CODE_RANDOM'
              | 'INSERT'
              | 'CODE_DESIGNATE_ADMIN_ONLY';
            /**
             * @description 최대 할인금액 (정률할인시)
             * @example 10
             */
            maximumDiscountAmount: number;
            /**
             * @description 쿠폰 이름
             * @example 실버쿠폰
             */
            couponName: string;
            /**
             * @description 할인률 (정률할인시)
             * @example 10
             */
            discountPercent: number;
            /**
             * @description 할인금액 (정액할인시)
             * @example 1000
             */
            discountAmount: number;
            /**
             * @description 쿠폰 할인 유형
             * @example PERCENT
             * @enum {string}
             */
            discountType: 'AMOUNT' | 'PERCENT';
            /**
             * @description 쿠폰 번호
             * @example 2345
             */
            couponNo: number;
          }[];
          /**
           * @description 등급 설명
           * @example 기본등급입니다.
           */
          description: string;
          /**
           * @description 등급명
           * @example 기본등급
           */
          label: string;
          /**
           * @description 등급 사용 여부
           * @example true
           */
          used: boolean;
          /** @description 적립금 혜택 */
          reserveBenefit: {
            /**
             * @description 적립금 혜택 적립률
             * @example 10
             */
            reserveRate: number;
            /**
             * @description 적립금 혜택 사용여부
             * @example true
             */
            used: boolean;
          };
        }[];
        /** @description 서비스센터 정보 */
        serviceCenter: {
          /**
           * @description 서비스센터 전화번호
           * @example 010-1111-1111
           */
          phoneNo: string;
          /**
           * @description 서비스센터 이메일
           * @example test@test.com
           */
          email: string;
        };
        /** @description 에스크로 로고정보 */
        escrowLogo: {
          /**
           * @description 로고 노출에 필요한 HTML 코드 (이니시스만 반환됨) (nullable)
           * @example <div>LOGO</div>
           */
          logoHtml?: string;
          /**
           * @description PG사
           * @example KCP
           * @enum {string}
           */
          pgType:
            | 'PAYCO'
            | 'PAYPAL'
            | 'STRIPE'
            | 'KCP'
            | 'INICIS'
            | 'KCP_MOBILE'
            | 'KCP_APP'
            | 'NAVER_PAY'
            | 'LIIVMATE'
            | 'PAYPALPRO'
            | 'ATHOR_NET'
            | 'KAKAO_PAY'
            | 'NAVER_EASY_PAY'
            | 'TOSS_PAYMENTS'
            | 'CHAI'
            | 'VERITRANS'
            | 'EXIMBAY_GLOBAL';
          /**
           * @description 에스크로 이미지 노출여부
           * @example true
           */
          exposure: boolean;
        };
        /** @description 접속 URL */
        url: {
          /**
           * @description PC 접속 URL
           * @example http://test.e-ncp.com
           */
          pc: string;
          /**
           * @description 안드로이드 마켓 URL
           * @example http://and.com/aa23
           */
          android: string;
          /**
           * @description 모바일웹 접속 URL
           * @example http://test.e-ncp.com
           */
          mobile: string;
          /**
           * @description 앱스토어 URL
           * @example http://ios.com/aa23
           */
          ios: string;
        };
      };
      /** @description 클레임 사유 목록 */
      claimReasonType: {
        /**
         * @description 클레임 사유 명칭
         * @example 입금전취소
         * @enum {string}
         */
        label:
          | '단순변심(색상,사이즈)'
          | '상품불량/파손'
          | '배송누락/오배송'
          | '재고부족(시스템)'
          | '입금전취소'
          | '상품상세 정보와 다름'
          | '판매자 배송 지연'
          | '상품 품절/재고 없음'
          | '기타(판매자 귀책)'
          | '기타(구매자 귀책)';
        /**
         * @description 클레임 사유 값
         * @example CANCEL_BEFORE_PAY
         * @enum {string}
         */
        value:
          | 'CHANGE_MIND'
          | 'DEFECTIVE_PRODUCT'
          | 'WRONG_DELIVERY'
          | 'OUT_OF_STOCK_SYSTEM'
          | 'CANCEL_BEFORE_PAY'
          | 'WRONG_PRODUCT_DETAIL'
          | 'DELAY_DELIVERY'
          | 'OUT_OF_STOCK'
          | 'OTHERS_SELLER'
          | 'OTHERS_BUYER';
      }[];
      /** @description 쇼핑몰 기본정보 */
      serviceBasicInfo: {
        /**
         * @description 주소 (nullable)
         * @example 서울특별시 구로구 구로동 디지털로26길 72
         */
        address?: string;
        /**
         * @description 대표 이메일 (nullable)
         * @example cs@nhn-commerce.com
         */
        representEmail?: string;
        /**
         * @description 회사명 (nullable)
         * @example 엔에이치엔커머스
         */
        companyName?: string;
        /**
         * @description 개인정보보호 책임자명 (nullable)
         * @example 김종승
         */
        privacyManagerName?: string;
        /**
         * @description 지번 주소 (nullable)
         * @example 서울특별시 구로구 구로동 222-22
         */
        jibunAddress?: string;
        /**
         * @description 통신판매업신고 번호 (nullable)
         * @example 2015-서울구로-0049
         */
        onlineMarketingBusinessDeclarationNo?: string;
        /**
         * @description 업태 (nullable)
         * @example 정보통신업
         */
        businessCondition?: string;
        /**
         * @description 우편번호 (nullable)
         * @example 08393
         */
        zipCd?: string;
        /**
         * @description 상세주소 (nullable)
         * @example 3층
         */
        addressDetail?: string;
        /**
         * @description 팩스번호 (nullable)
         * @example 02-567-3744
         */
        faxNo?: string;
        /**
         * @description 개인정보보호 책임자 전화번호 (nullable)
         * @example 1688-7662
         */
        privacyManagerPhoneNo?: string;
        /**
         * @description 사업자등록번호 (nullable)
         * @example 120-86-46911
         */
        businessRegistrationNo?: string;
        /**
         * @description 대표 전화번호 (nullable)
         * @example 1688-7662
         */
        representPhoneNo?: string;
        /**
         * @description 업종 (nullable)
         * @example 통신판매업
         */
        businessType?: string;
        /**
         * @description 샵바이 서비스 플랜명
         * @example PREMIUM
         */
        plan: string;
        /**
         * @description 지번 상세주소 (nullable)
         * @example 3층
         */
        jibunAddressDetail?: string;
        /**
         * @description 대표자명 (nullable)
         * @example 이윤식
         */
        representativeName?: string;
      };
      /** @description 공정거래 로고 정보 */
      termsConfig: {
        /**
         * @description 공정거래 로고 사용 여부 (nullable)
         * @example false
         */
        fairLogoUsed?: boolean;
        /**
         * @description 공정거래 로고 이미지 URL (nullable)
         * @example http://test.com
         */
        fairLogoUrl?: string;
      };
      /** @description 오픈아이디 설정 정보 */
      openIdJoinConfig: {
        /**
         * @description 오픈아이디 회원인증 수단 (nullable)
         * @example SMS_OCCUPANCY_AUTHENTICATION
         * @enum {string}
         */
        authenticationType?:
          | 'AUTHENTICATION_BY_PHONE'
          | 'SMS_AUTHENTICATION'
          | 'SMS_OCCUPANCY_AUTHENTICATION'
          | 'AUTHENTICATION_BY_EMAIL'
          | 'NOT_USED';
        /**
         * @description 오픈아이디 회원인증 시점 (nullable)
         * @example JOIN_TIME
         * @enum {string}
         */
        authenticationTimeType?:
          | 'JOIN_TIME'
          | 'PAYMENT_TIME'
          | 'AFTER_JOIN_TIME'
          | 'NONE';
        /**
         * @description 지원하는 오픈아이디 (nullable)
         * @example ["payco","kakao"]
         */
        providers?: (
          | 'PAYCO'
          | 'NAVER'
          | 'KAKAO'
          | 'KAKAO_SYNC'
          | 'FACEBOOK'
          | 'LINE'
          | 'APPLE'
          | 'GOOGLE'
        )[];
      };
      /** @description 외부 서비스 설정 */
      externalServiceConfig: {
        kakaoMap?: {
          /**
           * @description 카카오맵 경도 (nullable)
           * @example 70
           */
          kakaoMapLongitude?: string;
          /**
           * @description 카카오맵 위도 (nullable)
           * @example 30
           */
          kakaoMapLatitude?: string;
          /**
           * @description 카카오맵 Appkey (nullable)
           * @example kakaoMapKey
           */
          kakaoMapKey?: string;
        };
        /**
         * @description 구글 통계 추적 ID (nullable)
         * @example googleAnalytics-value
         */
        googleAnalytics?: string;
        /**
         * @description 외부스크립트 사용여부 (nullable)
         * @example false
         */
        useScript?: boolean;
        /**
         * @description 네이버 웹마스터 Appkey (nullable)
         * @example naverWebmaster-value
         */
        naverWebmaster?: string;
      };
      /** @description 클레임상태 목록 */
      claimStatusType: {
        /**
         * @description 클레임상태 명칭
         * @example 취소완료[환불없음]
         * @enum {string}
         */
        label:
          | '취소완료[환불없음]'
          | '취소신청[승인대기]'
          | '취소처리[환불보류]'
          | '취소처리[환불대기]'
          | '취소완료[환불완료]'
          | '반품신청[승인대기]'
          | '반품신청[철회대기]'
          | '반품처리[수거진행]'
          | '반품처리[환불보류]'
          | '반품처리[환불대기]'
          | '반품완료[환불완료]'
          | '교환처리[조정요청]'
          | '교환신청[승인대기]'
          | '교환처리[철회대기]'
          | '교환처리[수거진행]'
          | '교환처리[결제대기]'
          | '교환처리[환불보류]'
          | '교환처리[처리대기]'
          | '교환완료'
          | '교환처리[입금처리대기]'
          | '교환처리[환불대기]'
          | '교환완료[결제완료]'
          | '교환완료[환불완료]';
        /**
         * @description 클레임상태 값
         * @example CANCEL_NO_REFUND
         * @enum {string}
         */
        value:
          | 'CANCEL_NO_REFUND'
          | 'CANCEL_REQUEST'
          | 'CANCEL_PROC_REQUEST_REFUND'
          | 'CANCEL_PROC_WAITING_REFUND'
          | 'CANCEL_DONE'
          | 'RETURN_REQUEST'
          | 'RETURN_REJECT_REQUEST'
          | 'RETURN_PROC_BEFORE_RECEIVE'
          | 'RETURN_PROC_REQUEST_REFUND'
          | 'RETURN_PROC_WAITING_REFUND'
          | 'RETURN_DONE'
          | 'RETURN_REFUND_AMT_ADJUST_REQUESTED'
          | 'EXCHANGE_REQUEST'
          | 'EXCHANGE_REJECT_REQUEST'
          | 'EXCHANGE_PROC_BEFORE_RECEIVE'
          | 'EXCHANGE_PROC_REQUEST_PAY'
          | 'EXCHANGE_PROC_REQUEST_REFUND'
          | 'EXCHANGE_PROC_WAITING'
          | 'EXCHANGE_DONE'
          | 'EXCHANGE_PROC_WAITING_PAY'
          | 'EXCHANGE_PROC_WAITING_REFUND'
          | 'EXCHANGE_DONE_PAY_DONE'
          | 'EXCHANGE_DONE_REFUND_DONE';
      }[];
      /** @description 장바구니 설정 */
      cartConfig: {
        /**
         * @description 최대 보관 일수 (nullable)
         * @example 7
         */
        storagePeriod?: number;
        /**
         * @description 장바구니 상품 추가 타입 (nullable)
         * @example QUANTITY
         * @enum {string}
         */
        cartEquivalentOptionUnitType?: 'QUANTITY' | 'ROW';
        /**
         * @description 무제한 보관 설정 (nullable)
         * @example false
         */
        storagePeriodNoLimit?: boolean;
        /**
         * @description 장바구니 보관 최대 수량 (nullable)
         * @example 100
         */
        storageMaxQuantity?: number;
      };
      /** @description 상품평 신고 유형 목록 */
      productReviewReportType: {
        /**
         * @description 상품평 신고 유형 명칭
         * @example 저작권 침해 및 기타사유
         * @enum {string}
         */
        label: '저작권 침해 및 기타사유' | '욕설 또는 비방';
        /**
         * @description 상품평 신고 유형 값
         * @example COPYRIGHT
         * @enum {string}
         */
        value: 'COPYRIGHT' | 'SLANDER';
      }[];
      /** @description 상품문의 유형 목록 */
      productInquiryType: {
        /**
         * @description 상품문의 유형 명칭
         * @example 상품
         * @enum {string}
         */
        label: '상품' | '배송' | '취소' | '반품' | '교환' | '환불' | '기타';
        /**
         * @description 상품문의 유형 값
         * @example PRODUCT
         * @enum {string}
         */
        value:
          | 'PRODUCT'
          | 'DELIVERY'
          | 'CANCEL'
          | 'RETURN'
          | 'EXCHANGE'
          | 'REFUND'
          | 'OTHER';
      }[];
      /** @description 쇼핑몰 회원 인증 수단 */
      mallJoinConfig: {
        /**
         * @description 쇼핑몰 회원 인증 수단 (nullable)
         * @example SMS_OCCUPANCY_AUTHENTICATION
         * @enum {string}
         */
        authenticationType?:
          | 'AUTHENTICATION_BY_PHONE'
          | 'SMS_AUTHENTICATION'
          | 'SMS_OCCUPANCY_AUTHENTICATION'
          | 'AUTHENTICATION_BY_EMAIL'
          | 'NOT_USED';
        /**
         * @description 쇼핑몰 회원 인증 시점 (nullable)
         * @example JOIN_TIME
         * @enum {string}
         */
        authenticationTimeType?:
          | 'JOIN_TIME'
          | 'PAYMENT_TIME'
          | 'AFTER_JOIN_TIME'
          | 'NONE';
      };
      accumulationConfig?: {
        /**
         * @description 적립금 만료 알림 사용여부 (nullable)
         * @example false
         */
        useExpireNotification?: boolean;
        /**
         * @description 회원가입 적립금 사용여부 (nullable)
         * @example false
         */
        useSignUpAccumulation?: boolean;
        /**
         * @description 운영자 메모 (nullable)
         * @example 적립금 지급
         */
        adminMemo?: string;
        /**
         * @description 적립금 단위 (nullable)
         * @example 포인트
         */
        accumulationUnit?: string;
        /**
         * @description 적립금 지급 시점 (nullable)
         * @example AFTER_A_WEEK
         * @enum {string}
         */
        accumulationGivePoint?:
          | 'IMMEDIATE'
          | 'NEXTDAY'
          | 'DAY_AFTER_TOMMOROW'
          | 'AFTER_A_WEEK'
          | 'AFTER_TWO_WEEK'
          | 'AFTER_TWENTY_DAYS'
          | 'AFTER_THIRTY_DAYS'
          | 'NEXT_MONTH';
        /**
         * @description 적립금 기본 적립률 (nullable)
         * @example 10
         */
        accumulationRate?: number;
        /**
         * @description 적립금 사용 최대 적립금 제한 여부 (nullable)
         * @example false
         */
        limitMaxRate?: boolean;
        /**
         * @description 적립금 사용 최소 상품금액 제한 여부 (nullable)
         * @example false
         */
        limitMinProductPrice?: boolean;
        /**
         * @description 적립금 사용 최소 적립금 (nullable)
         * @example 1000
         */
        accumulationUseMinPrice?: number;
        /**
         * @description 적립금 노출 설정 (nullable)
         * @example FIXED_AMT
         * @enum {string}
         */
        accumulationDisplayFormatType?:
          | 'FIXED_AMT'
          | 'FIXED_RATE'
          | 'FIRST_FIXED_RATE'
          | 'FIRST_FIXED_AMT';
        reviewsAccumulationDetail?: {
          /**
           * @description 포토 상품평 적립금 (nullable)
           * @example 150
           */
          photoReviewsAccumulation?: number;
          /**
           * @description 포토 상품평 글자수 (nullable)
           * @example 10
           */
          photoReviewsLength?: number;
          /**
           * @description 상품평 글자수 (nullable)
           * @example 10
           */
          reviewsLength?: number;
          /**
           * @description 상품평 적립금 (nullable)
           * @example 100
           */
          reviewsAccumulation?: number;
        };
        /**
         * @description 적립금 만료 알림 시점 (day 기준) (nullable)
         * @example 30
         */
        expireNotificationPoint?: number;
        /**
         * @description 적립금 유효기간 (month 기준) (nullable)
         * @example 3
         */
        accumulationValidPeriod?: number;
        /**
         * @description 상품 적립 사용여부 (nullable)
         * @example false
         */
        useProductAccumulation?: boolean;
        /**
         * @description 적립금 사용 최대비율 (nullable)
         * @example false
         */
        excludingReservePayAccumulation?: boolean;
        /**
         * @description 적립금 사용 최소 적립금 제한 여부 (nullable)
         * @example false
         */
        limitMinPrice?: boolean;
        /**
         * @description 적립금 사용 최소 상품금액 (nullable)
         * @example 5000
         */
        accumulationUseMinProductPrice?: number;
        /**
         * @description 회원가입 적립금 (nullable)
         * @example 1000
         */
        signUpAccumulation?: number;
        /**
         * @description 적립금 사용 최대비율 (nullable)
         * @example 100
         */
        accumulationUseMaxRate?: number;
        /**
         * @description 상품평 적립금 사용여부 (nullable)
         * @example false
         */
        useReviewsAccumulation?: boolean;
        /**
         * @description 상품 금액 기준 설정 (nullable)
         * @example null
         * @enum {string}
         */
        productAccumulationBasisType?:
          | 'SALE_PRICE'
          | 'SALE_STANDARD_PRICE'
          | 'SALE_PROMOTION_PRICE'
          | 'DISCOUNTED_PRICE'
          | 'DISCOUNTED_STANDARD_PRICE'
          | 'DISCOUNTED_PROMOTION_PRICE';
        /**
         * @description 적립금명 (nullable)
         * @example 구매 적립금
         */
        accumulationName?: string;
        /**
         * @description 쿠폰할인 결제시 적립금 지급 제외여부 (nullable)
         * @example false
         */
        excludingReservePayCoupon?: boolean;
        /**
         * @description 회원 적립 사용여부 (nullable)
         * @example false
         */
        useMemberAccumulation?: boolean;
      };
      categories?: {
        /** @description 카테고리 목록(계층) */
        multiLevelCategories: {
          /**
           * @description 뎁스
           * @example 1
           */
          depth: number;
          /** @description 2차 카테고리 */
          children: {
            /**
             * @description 카테고리 뎁스 (nullable)
             * @example 2
             */
            depth?: number;
            /** @description 3차 카테고리 */
            children: {
              /**
               * @description 카테고리 뎁스 (nullable)
               * @example 3
               */
              depth?: number;
              /** @description 4차 카테고리 */
              children: {
                /**
                 * @description 카테고리 뎁스 (nullable)
                 * @example 4
                 */
                depth?: number;
                /** @description 5차 카테고리 */
                children: {
                  /**
                   * @description 카테고리 뎁스 (nullable)
                   * @example 5
                   */
                  depth?: number;
                  children?: Record<string, never>;
                  /**
                   * @description 카테고리 아이콘 (nullable)
                   * @example //image.nhn-commerce.com/icon.png
                   */
                  icon?: string;
                  /**
                   * @description 카테고리 번호 (nullable)
                   * @example 5
                   */
                  categoryNo?: number;
                  /**
                   * @description 카테고리 이름 (nullable)
                   * @example 게임기 컨트롤러
                   */
                  label?: string;
                  /**
                   * @description 카테고리 카테고리 상세(HTML) (nullable)
                   * @example <div>아이콘</div>
                   */
                  content?: string;
                }[];
                /**
                 * @description 카테고리 아이콘 (nullable)
                 * @example //image.nhn-commerce.com/icon.png
                 */
                icon?: string;
                /**
                 * @description 카테고리 번호 (nullable)
                 * @example 4
                 */
                categoryNo?: number;
                /**
                 * @description 카테고리 이름 (nullable)
                 * @example 악세사리
                 */
                label?: string;
                /**
                 * @description 카테고리 카테고리 상세(HTML) (nullable)
                 * @example <div>아이콘</div>
                 */
                content?: string;
              }[];
              /**
               * @description 카테고리 아이콘 (nullable)
               * @example //image.nhn-commerce.com/icon.png
               */
              icon?: string;
              /**
               * @description 카테고리 번호 (nullable)
               * @example 3
               */
              categoryNo?: number;
              /**
               * @description 카테고리 이름 (nullable)
               * @example 닌텐도
               */
              label?: string;
              /**
               * @description 카테고리 카테고리 상세(HTML) (nullable)
               * @example <div>아이콘</div>
               */
              content?: string;
            }[];
            /**
             * @description 카테고리 아이콘 (nullable)
             * @example //image.nhn-commerce.com/icon.png
             */
            icon?: string;
            /**
             * @description 카테고리 번호 (nullable)
             * @example 2
             */
            categoryNo?: number;
            /**
             * @description 카테고리 이름 (nullable)
             * @example 게임기 주변기기
             */
            label?: string;
            /**
             * @description 카테고리 카테고리 상세(HTML) (nullable)
             * @example <div>아이콘</div>
             */
            content?: string;
          }[];
          /**
           * @description 아이콘
           * @example //image.nhn-commerce.com/icon.png
           */
          icon: string;
          /**
           * @description 카테고리 번호
           * @example 1
           */
          categoryNo: number;
          /**
           * @description 카테고리 이름
           * @example 게임
           */
          label: string;
          /**
           * @description 카테고리 상세(HTML)
           * @example <div>아이콘</div>
           */
          content: string;
        }[];
        /** @description 카테고리 목록 */
        flatCategories: {
          /**
           * @description 카테고리 번호(5차)
           * @example 5
           */
          depth5CategoryNo: number;
          /**
           * @description 카테고리 순서(2차)
           * @example 1
           */
          depth2DisplayOrder: number;
          /**
           * @description 카테고리 아이콘(3차) (nullable)
           * @example //image.nhn-commerce.com/icon.png
           */
          depth3Icon?: string;
          /**
           * @description 카테고리 순서(1차)
           * @example 1
           */
          depth1DisplayOrder: number;
          /**
           * @description 카테고리 번호(3차)
           * @example 3
           */
          depth3CategoryNo: number;
          /**
           * @description 카테고리 아이콘(2차) (nullable)
           * @example //image.nhn-commerce.com/icon.png
           */
          depth2Icon?: string;
          /**
           * @description 카테고리 명(4차)
           * @example 악세사리
           */
          depth4Label: string;
          /**
           * @description 카테고리 명(1차)
           * @example 게임
           */
          depth1Label: string;
          /**
           * @description 카테고리 아이콘(4차) (nullable)
           * @example //image.nhn-commerce.com/icon.png
           */
          depth4Icon?: string;
          /**
           * @description 카테고리 명(2차)
           * @example 게임기 주변기기
           */
          depth2Label: string;
          /**
           * @description 카테고리 명(5차)
           * @example 게임기 컨트롤러
           */
          depth5Label: string;
          /**
           * @description 카테고리 아이콘(5차) (nullable)
           * @example //image.nhn-commerce.com/icon.png
           */
          depth5Icon?: string;
          /**
           * @description 카테고리 번호(2차)
           * @example 2
           */
          depth2CategoryNo: number;
          /**
           * @description 카테고리 명(3차)
           * @example 닌텐도
           */
          depth3Label: string;
          /**
           * @description 카테고리 번호(1차)
           * @example 1
           */
          depth1CategoryNo: number;
          /**
           * @description 카테고리 상세 HTML(5차) (nullable)
           * @example <div>아이콘</div>
           */
          depth5Content?: string;
          /**
           * @description 카테고리 아이콘(1차) (nullable)
           * @example //image.nhn-commerce.com/icon.png
           */
          depth1Icon?: string;
          /**
           * @description 1~5차 카테고리 명
           * @example 카테고리
           */
          fullCategoryName: string;
          /**
           * @description 카테고리 순서(5차)
           * @example 1
           */
          depth5DisplayOrder: number;
          /**
           * @description 카테고리 순서(4차)
           * @example 1
           */
          depth4DisplayOrder: number;
          /**
           * @description 카테고리 상세 HTML(3차) (nullable)
           * @example <div>아이콘</div>
           */
          depth3Content?: string;
          /**
           * @description 카테고리 번호(4차)
           * @example 4
           */
          depth4CategoryNo: number;
          /**
           * @description 카테고리 상세 HTML(2차) (nullable)
           * @example <div>아이콘</div>
           */
          depth2Content?: string;
          /**
           * @description 카테고리 상세 HTML(1차) (nullable)
           * @example <div>아이콘</div>
           */
          depth1Content?: string;
          /**
           * @description 카테고리 상세 HTML(4차) (nullable)
           * @example <div>아이콘</div>
           */
          depth4Content?: string;
          /**
           * @description 카테고리 순서(3차)
           * @example 1
           */
          depth3DisplayOrder: number;
        }[];
      };
      /** @description 쇼핑몰 계좌 정보 목록 */
      bankAccountInfos: {
        /**
         * @description 계좌번호 (nullable)
         * @example 123456789
         */
        bankAccount?: string;
        /**
         * @description 예금주명 (nullable)
         * @example 커머스
         */
        bankDepositorName?: string;
        /**
         * @description 은행명 (nullable)
         * @example 우리은행
         */
        bankName?: string;
      }[];
      /** @description 게시판 카테고리 목록 */
      boardsCategories: {
        /**
         * @description 썸네일 이미지 사용 여부
         * @example true
         */
        thumbnailUsed: boolean;
        /**
         * @description 답글 작성 가능 여부
         * @example false
         */
        replied: boolean;
        /**
         * @description 회원 작성 가능 여부
         * @example false
         */
        memberWrite: boolean;
        /**
         * @description 게시판 사용 여부
         * @example true
         */
        used: boolean;
        /**
         * @description 비밀글 작성 가능 여부
         * @example false
         */
        secreted: boolean;
        /**
         * @description 게시판 이름
         * @example 자유게시판
         */
        boardName: string;
        /**
         * @description 비회원 작성 가능 여부
         * @example false
         */
        guestWrite: boolean;
        /**
         * @description 리스트 이미지 유형
         * @example NOT_USED
         * @enum {string}
         */
        imageDisplayType: 'NOT_USED' | 'ATTACHMENT' | 'PRODUCT';
        /**
         * @description 게시판 노출 유형
         * @example LIST
         * @enum {string}
         */
        displayType: 'LIST' | 'CARD' | 'REPLY' | 'INQUIRY';
        /**
         * @description 카테고리 사용 여부
         * @example true
         */
        categoryUsed: boolean;
        /**
         * @description 첨부파일 사용 여부
         * @example false
         */
        attachmentUsed: boolean;
        /**
         * @description 게시판 ID (nullable)
         * @example freeboard
         */
        boardId?: string;
        /** @description 게시판 카테고리 정보 */
        categories: {
          /**
           * @description 게시판 카테고리 번호
           * @example 1
           */
          categoryNo: number;
          /**
           * @description 게시판 카테고리 명칭
           * @example 질문
           */
          label: string;
        }[];
        /**
         * @description 게시판 번호
         * @example 1
         */
        boardNo: number;
      }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers?: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * 몰 정보 조회하기
   * @description ## 부가설명 및 특이사항
   * 몰 정보를 조회하는 API입니다.
   *
   * 몰 진입 시 전체 카테고리 조회 후 응답값을 localStorage(web), SharedPreference(android), NSUserDefaults(ios)와 같은 로컬 저장소에 두고 재사용하는 방식을 권장합니다.
   *
   * expire time은 익일 0시로 설정을 권장합니다.
   *
   * 카테고리는 변경 가능하므로 상품상세 API의 카테고리 번호가 로컬 저장소에는 없을 수 있습니다.
   *
   * 그런 경우에는 카테고리 조회 API를 이용하여 로컬 저장소를 갱신해 주십시오.
   *
   *
   * ## CDN으로 대체하면 더 좋은 성능을 낼 수 있습니다.
   * 해당 API는 상점 정보를 DB를 통해 조회하며, DB에서 데이터를 가져올 때 트래픽이 발생하는 경우 병목 현상으로 인해 API응답이 지연이 되는 경우가 있습니다.
   *
   * 하지만 CDN을 활용해 상점 정보를 가져오게 되면 트래픽 대부분을 CDN캐시 서버에서 처리하기 때문에 트래픽 폭주로 인한 서비스 장애를 사전에 방지할 수 있습니다.
   *
   * 또한 CDN 리소스를  최종 클라이언트에게 전달할 때, 일반 인터넷망이 아닌 전용선을 사용하여 빠르고 안전한 성능을 기대할 수 있습니다.
   *
   * CDN경로에는 해당 API의 응답값과 동일한 상점 정보가 포함되어있고 해당 정보가 변경되면 5초이내로 CDN파일을 갱신하고 있습니다.
   *
   * 기존과 같이 응답값을 localStorage(web), SharedPreference(android), NSUserDefaults(ios)와 같은 로컬저장소에 두고 재사용하는 방식을 권장합니다.
   *
   * 자세한 개발방법은 아래 링크를 참조하세요.
   *
   * [https://shopby.works/guide/skin/dev-cover/call-api#call-info](https://shopby.works/guide/skin/dev-cover/call-api#call-info)
   */
  'get-malls': {
    parameters: {
      header?: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version?: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId?: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': components['schemas']['malls1221953710'];
        };
      };
    };
  };
  /**
   * 현재 몰의 다국어, 환율 설정 조회
   * @description ## 부가설명 및 특이사항
   * 현재 몰의 다국어, 환율 설정 조회을 조회하는 API 입니다.
   */
  'get-malls-i18n': {
    parameters: {
      header?: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version?: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId?: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': components['schemas']['malls-internationalization-996890286'];
        };
      };
    };
  };
  /**
   * [샵바이프리미엄 전용] 몰과 계약한 파트너 목록 조회하기
   * @description ## 부가설명 및 특이사항
   * 몰과 계약한 파트너 목록을 조회하는 API입니다.
   */
  'get-malls-partners': {
    parameters: {
      header?: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version?: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId?: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': components['schemas']['malls-partners-200843305'];
        };
      };
    };
  };
  /**
   * 현재 도메인의 보안서버정보 조회하기
   * @description ## 부가설명 및 특이사항
   * 현재 도메인의 보안서버정보를 조회하는 API입니다.
   */
  'get-malls-ssl': {
    parameters: {
      header?: {
        /**
         * @description API 버전
         * @example 1.0
         */
        Version?: string;
        /**
         * @description 쇼핑몰 클라이언트 아이디
         * @example test-client-id
         */
        clientId?: string;
        /**
         * @description 클라이언트 플랫폼 (PC, MOBILE_WEB, AOS, IOS)
         * @example PC
         */
        platform?: string;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': components['schemas']['malls-ssl-953646756'];
        };
      };
    };
  };
}
